
?_CONSTRUCTOR@ActionDeque@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ActionDeque@@QEAAPEAV1@XZ endp

; ActionDeque::ActionDeque();
??0ActionDeque@@QEAA@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+0*8]
??0ActionDeque@@QEAA@XZ endp

?_DESTRUCTOR@ActionDeque@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ActionDeque@@QEAAXXZ endp

; ActionDeque::~ActionDeque();
??1ActionDeque@@UEAA@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+1*8]
??1ActionDeque@@UEAA@XZ endp

; ActionDeque::getFirstTask();
?getFirstTask@ActionDeque@@QEBAPEBVTasker@@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+2*8]
?getFirstTask@ActionDeque@@QEBAPEBVTasker@@XZ endp

; ActionDeque::getFirstTask();
?getFirstTask@ActionDeque@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+3*8]
?getFirstTask@ActionDeque@@QEAAPEAVTasker@@XZ endp

; ActionDeque::getSecondTask();
?getSecondTask@ActionDeque@@QEBAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+4*8]
?getSecondTask@ActionDeque@@QEBAPEAVTasker@@XZ endp

; ActionDeque::getLastTask();
?getLastTask@ActionDeque@@QEBAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+5*8]
?getLastTask@ActionDeque@@QEBAPEAVTasker@@XZ endp

; ActionDeque::hasTask(class TaskMatch);
?hasTask@ActionDeque@@QEAA_NVTaskMatch@@@Z proc EXPORT
jmp function_pointers[_ActionDeque_base+6*8]
?hasTask@ActionDeque@@QEAA_NVTaskMatch@@@Z endp

; ActionDeque::insertTask(class Tasker *);
?insertTask@ActionDeque@@QEAAXPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_ActionDeque_base+7*8]
?insertTask@ActionDeque@@QEAAXPEAVTasker@@@Z endp

; ActionDeque::addTask(class Tasker *);
?addTask@ActionDeque@@QEAAXPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_ActionDeque_base+8*8]
?addTask@ActionDeque@@QEAAXPEAVTasker@@@Z endp

; ActionDeque::clearAndDelete();
?clearAndDelete@ActionDeque@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActionDeque_base+9*8]
?clearAndDelete@ActionDeque@@QEAAXXZ endp

; ActionDeque::clearOnly();
?clearOnly@ActionDeque@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActionDeque_base+10*8]
?clearOnly@ActionDeque@@QEAAXXZ endp

; ActionDeque::passOnCurrentTask();
?passOnCurrentTask@ActionDeque@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_ActionDeque_base+11*8]
?passOnCurrentTask@ActionDeque@@QEAAPEAVTasker@@XZ endp

; ActionDeque::isEmpty();
?isEmpty@ActionDeque@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ActionDeque_base+12*8]
?isEmpty@ActionDeque@@QEBA_NXZ endp

; ActionDeque::isOnlyOne();
?isOnlyOne@ActionDeque@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ActionDeque_base+13*8]
?isOnlyOne@ActionDeque@@QEBA_NXZ endp
