
; AI::_createTradingInfo();
?_createTradingInfo@AI@@QEAAXXZ proc EXPORT
jmp function_pointers[_AI_base+0*8]
?_createTradingInfo@AI@@QEAAXXZ endp

; AI::isWithinChoppingRange(class RootObjectBase *, bool);
?isWithinChoppingRange@AI@@QEAA_NPEAVRootObjectBase@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+1*8]
?isWithinChoppingRange@AI@@QEAA_NPEAVRootObjectBase@@_N@Z endp

; AI::setFunc(enum StateType, function  *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setFunc@AI@@SAXW4StateType@@P81@EAA_NAEBVhand@@AEBVVector3@Ogre@@@ZAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@4@Z proc EXPORT
jmp function_pointers[_AI_base+2*8]
?setFunc@AI@@SAXW4StateType@@P81@EAA_NAEBVhand@@AEBVVector3@Ogre@@@ZAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@4@Z endp

; AI::_setupGOAPFuncs();
?_setupGOAPFuncs@AI@@SAXXZ proc EXPORT
jmp function_pointers[_AI_base+3*8]
?_setupGOAPFuncs@AI@@SAXXZ endp

; AI::setTaskRepertoireFlag(unsigned int);
?setTaskRepertoireFlag@AI@@QEAAXI@Z proc EXPORT
jmp function_pointers[_AI_base+4*8]
?setTaskRepertoireFlag@AI@@QEAAXI@Z endp

; AI::clearTaskRepertoireFlag(unsigned int);
?clearTaskRepertoireFlag@AI@@QEAAXI@Z proc EXPORT
jmp function_pointers[_AI_base+5*8]
?clearTaskRepertoireFlag@AI@@QEAAXI@Z endp

; AI::forceOrderInsert(enum TaskType);
?forceOrderInsert@AI@@QEAAXW4TaskType@@@Z proc EXPORT
jmp function_pointers[_AI_base+6*8]
?forceOrderInsert@AI@@QEAAXW4TaskType@@@Z endp

?_NV_stateIsTrue@AI@@QEAA_NAEBVTaskStateData@@AEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_stateIsTrue@AI@@QEAA_NAEBVTaskStateData@@AEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::stateIsTrue(const class TaskStateData &, const class hand &, const class Ogre::Vector3 &);
?stateIsTrue@AI@@UEAA_NAEBVTaskStateData@@AEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+7*8]
?stateIsTrue@AI@@UEAA_NAEBVTaskStateData@@AEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::addAIGoalsFrom(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addAIGoalsFrom@AI@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AI_base+8*8]
?addAIGoalsFrom@AI@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AI::isWithinGivenRange(const class hand &, const class Ogre::Vector3 &, float);
?isWithinGivenRange@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_AI_base+9*8]
?isWithinGivenRange@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@M@Z endp

; AI::getSensoryData();
?getSensoryData@AI@@QEAAPEAVSensoryData@@XZ proc EXPORT
jmp function_pointers[_AI_base+10*8]
?getSensoryData@AI@@QEAAPEAVSensoryData@@XZ endp

; AI::getTaskSystem();
?getTaskSystem@AI@@QEBAPEAVAITaskSytem@@XZ proc EXPORT
jmp function_pointers[_AI_base+11*8]
?getTaskSystem@AI@@QEBAPEAVAITaskSytem@@XZ endp

; AI::getStateBroadcast();
?getStateBroadcast@AI@@QEAAPEAVStateBroadcastData@@XZ proc EXPORT
jmp function_pointers[_AI_base+12*8]
?getStateBroadcast@AI@@QEAAPEAVStateBroadcastData@@XZ endp

; AI::_notifyTaskComplete();
?_notifyTaskComplete@AI@@QEAAXXZ proc EXPORT
jmp function_pointers[_AI_base+13*8]
?_notifyTaskComplete@AI@@QEAAXXZ endp

; AI::getDestinationTown();
?getDestinationTown@AI@@QEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_AI_base+14*8]
?getDestinationTown@AI@@QEAAPEAVTownBase@@XZ endp

; AI::setPlatoon(class Platoon *);
?setPlatoon@AI@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_AI_base+15*8]
?setPlatoon@AI@@QEAAXPEAVPlatoon@@@Z endp

; AI::getPlatoon();
?getPlatoon@AI@@QEBAPEAVPlatoon@@XZ proc EXPORT
jmp function_pointers[_AI_base+16*8]
?getPlatoon@AI@@QEBAPEAVPlatoon@@XZ endp

?_NV_getFaction@AI@@QEAAPEAVFaction@@XZ proc EXPORT
?_NV_getFaction@AI@@QEAAPEAVFaction@@XZ endp

; AI::getFaction();
?getFaction@AI@@UEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_AI_base+17*8]
?getFaction@AI@@UEAAPEAVFaction@@XZ endp

; AI::getBlackboard();
?getBlackboard@AI@@QEAAPEAVBlackboard@@XZ proc EXPORT
jmp function_pointers[_AI_base+18*8]
?getBlackboard@AI@@QEAAPEAVBlackboard@@XZ endp

; AI::getHandle();
?getHandle@AI@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_AI_base+19*8]
?getHandle@AI@@QEBA?AVhand@@XZ endp

?_CONSTRUCTOR@AI@@QEAAPEAV1@PEAVStateBroadcastData@@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@AI@@QEAAPEAV1@PEAVStateBroadcastData@@PEAVCharacter@@@Z endp

; AI::AI(class StateBroadcastData *, class Character *);
??0AI@@QEAA@PEAVStateBroadcastData@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+20*8]
??0AI@@QEAA@PEAVStateBroadcastData@@PEAVCharacter@@@Z endp

?_DESTRUCTOR@AI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AI@@QEAAXXZ endp

; AI::~AI();
??1AI@@UEAA@XZ proc EXPORT
jmp function_pointers[_AI_base+21*8]
??1AI@@UEAA@XZ endp

; AI::create(class CharBody *, class Inventory *, class CharStats *, class MedicalSystem *, class Platoon *);
?create@AI@@QEAAXPEAVCharBody@@PEAVInventory@@PEAVCharStats@@PEAVMedicalSystem@@PEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_AI_base+22*8]
?create@AI@@QEAAXPEAVCharBody@@PEAVInventory@@PEAVCharStats@@PEAVMedicalSystem@@PEAVPlatoon@@@Z endp

?_NV_update4Frame@AI@@QEAAXM@Z proc EXPORT
?_NV_update4Frame@AI@@QEAAXM@Z endp

; AI::update4Frame(float);
?update4Frame@AI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AI_base+23*8]
?update4Frame@AI@@UEAAXM@Z endp

?_NV_periodicUpdate@AI@@QEAAXM@Z proc EXPORT
?_NV_periodicUpdate@AI@@QEAAXM@Z endp

; AI::periodicUpdate(float);
?periodicUpdate@AI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AI_base+24*8]
?periodicUpdate@AI@@UEAAXM@Z endp

; AI::periodicUpdate_KOed(float);
?periodicUpdate_KOed@AI@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AI_base+25*8]
?periodicUpdate_KOed@AI@@QEAAXM@Z endp

; AI::sendMessage(enum CharacterMessage, const class hand &, const class hand &);
?sendMessage@AI@@QEAAXW4CharacterMessage@@AEBVhand@@1@Z proc EXPORT
jmp function_pointers[_AI_base+26*8]
?sendMessage@AI@@QEAAXW4CharacterMessage@@AEBVhand@@1@Z endp

; AI::underMeleeAttack(class Character *, bool, bool);
?underMeleeAttack@AI@@QEAAXPEAVCharacter@@_N1@Z proc EXPORT
jmp function_pointers[_AI_base+27*8]
?underMeleeAttack@AI@@QEAAXPEAVCharacter@@_N1@Z endp

; AI::underRangedAttack(class Character *, bool);
?underRangedAttack@AI@@QEAAXPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+28*8]
?underRangedAttack@AI@@QEAAXPEAVCharacter@@_N@Z endp

; AI::isTargetOutsideTheGates(class RootObject *);
?isTargetOutsideTheGates@AI@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_AI_base+29*8]
?isTargetOutsideTheGates@AI@@QEAA_NPEAVRootObject@@@Z endp

; AI::amILockedWithinTownWalls();
?amILockedWithinTownWalls@AI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AI_base+30*8]
?amILockedWithinTownWalls@AI@@QEAA_NXZ endp

; AI::isEnemy(const class hand &, const class Ogre::Vector3 &);
?isEnemy@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+31*8]
?isEnemy@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isEnemy(class RootObjectBase *);
?isEnemy@AI@@QEAA_NPEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_AI_base+32*8]
?isEnemy@AI@@QEAA_NPEAVRootObjectBase@@@Z endp

; AI::load(class GameData *);
?load@AI@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AI_base+33*8]
?load@AI@@QEAAXPEAVGameData@@@Z endp

; AI::save(class GameData *);
?save@AI@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AI_base+34*8]
?save@AI@@QEAAXPEAVGameData@@@Z endp

; AI::getPosWithinChoppingRange(class RootObjectBase *, const class Ogre::Vector3 &);
?getPosWithinChoppingRange@AI@@QEAA?AVVector3@Ogre@@PEAVRootObjectBase@@AEBV23@@Z proc EXPORT
jmp function_pointers[_AI_base+35*8]
?getPosWithinChoppingRange@AI@@QEAA?AVVector3@Ogre@@PEAVRootObjectBase@@AEBV23@@Z endp

; AI::chooseBestAttackTarget(class RootObject * *, class lektor<Character *> &, float &, class hand, bool, bool);
?chooseBestAttackTarget@AI@@QEAA_NPEAPEAVRootObject@@AEAV?$lektor@PEAVCharacter@@@@AEAMVhand@@_N4@Z proc EXPORT
jmp function_pointers[_AI_base+36*8]
?chooseBestAttackTarget@AI@@QEAA_NPEAPEAVRootObject@@AEAV?$lektor@PEAVCharacter@@@@AEAMVhand@@_N4@Z endp

; AI::setAggressionLevel(enum AI::AIAggressionOrders);
?setAggressionLevel@AI@@QEAAXW4AIAggressionOrders@1@@Z proc EXPORT
jmp function_pointers[_AI_base+37*8]
?setAggressionLevel@AI@@QEAAXW4AIAggressionOrders@1@@Z endp

; AI::setManuveringFreedomLevel(enum AI::AIManuverabilityOrders);
?setManuveringFreedomLevel@AI@@QEAAXW4AIManuverabilityOrders@1@@Z proc EXPORT
jmp function_pointers[_AI_base+38*8]
?setManuveringFreedomLevel@AI@@QEAAXW4AIManuverabilityOrders@1@@Z endp

; AI::setCenterOfMovement(const class Ogre::Vector3 &);
?setCenterOfMovement@AI@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+39*8]
?setCenterOfMovement@AI@@QEAAXAEBVVector3@Ogre@@@Z endp

; AI::setCenterOfMovementTarget(const class hand &);
?setCenterOfMovementTarget@AI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_AI_base+40*8]
?setCenterOfMovementTarget@AI@@QEAAXAEBVhand@@@Z endp

?_NV_getCombatTarget@AI@@QEAA?AVhand@@XZ proc EXPORT
?_NV_getCombatTarget@AI@@QEAA?AVhand@@XZ endp

; AI::getCombatTarget();
?getCombatTarget@AI@@UEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_AI_base+41*8]
?getCombatTarget@AI@@UEAA?AVhand@@XZ endp

?_NV_updateStateBroadcast@AI@@QEAAXM@Z proc EXPORT
?_NV_updateStateBroadcast@AI@@QEAAXM@Z endp

; AI::updateStateBroadcast(float);
?updateStateBroadcast@AI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AI_base+42*8]
?updateStateBroadcast@AI@@UEAAXM@Z endp

; AI::buySomething(class Building *);
?buySomething@AI@@QEAA_NPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_AI_base+43*8]
?buySomething@AI@@QEAA_NPEAVBuilding@@@Z endp

; AI::IDontWantToLeaveTown();
?IDontWantToLeaveTown@AI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AI_base+44*8]
?IDontWantToLeaveTown@AI@@QEAA_NXZ endp

?_NV_getPosition@AI@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@AI@@QEAA?AVVector3@Ogre@@XZ endp

; AI::getPosition();
?getPosition@AI@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AI_base+45*8]
?getPosition@AI@@UEAA?AVVector3@Ogre@@XZ endp

?_NV_amMoving@AI@@QEAA_NXZ proc EXPORT
?_NV_amMoving@AI@@QEAA_NXZ endp

; AI::amMoving();
?amMoving@AI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AI_base+46*8]
?amMoving@AI@@UEAA_NXZ endp

?_NV_periodicUpdateStateBroadcast@AI@@QEAAXM@Z proc EXPORT
?_NV_periodicUpdateStateBroadcast@AI@@QEAAXM@Z endp

; AI::periodicUpdateStateBroadcast(float);
?periodicUpdateStateBroadcast@AI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AI_base+47*8]
?periodicUpdateStateBroadcast@AI@@UEAAXM@Z endp

; AI::getCharacter();
?getCharacter@AI@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_AI_base+48*8]
?getCharacter@AI@@QEAAPEAVCharacter@@XZ endp

; AI::getMyMissionTarget();
?getMyMissionTarget@AI@@QEAA?AVTargetInfo@@XZ proc EXPORT
jmp function_pointers[_AI_base+49*8]
?getMyMissionTarget@AI@@QEAA?AVTargetInfo@@XZ endp

; AI::getAllMyPermajobMachines(class boost::unordered::unordered_set<UseableStuff *,boost::hash<UseableStuff *>,std::equal_to<UseableStuff *>,Ogre::STLAllocator<UseableStuff *,Ogre::CategorisedAllocPolicy<0> > > &);
?getAllMyPermajobMachines@AI@@QEAAXAEAV?$unordered_set@PEAVUseableStuff@@U?$hash@PEAVUseableStuff@@@boost@@U?$equal_to@PEAVUseableStuff@@@std@@V?$STLAllocator@PEAVUseableStuff@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z proc EXPORT
jmp function_pointers[_AI_base+50*8]
?getAllMyPermajobMachines@AI@@QEAAXAEAV?$unordered_set@PEAVUseableStuff@@U?$hash@PEAVUseableStuff@@@boost@@U?$equal_to@PEAVUseableStuff@@@std@@V?$STLAllocator@PEAVUseableStuff@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z endp

; AI::hasPermajob(enum TaskType);
?hasPermajob@AI@@QEBA_NW4TaskType@@@Z proc EXPORT
jmp function_pointers[_AI_base+51*8]
?hasPermajob@AI@@QEBA_NW4TaskType@@@Z endp

?_NV_noneState@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_noneState@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::noneState(const class hand &, const class Ogre::Vector3 &);
?noneState@AI@@UEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+52*8]
?noneState@AI@@UEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_isAtLocation@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_isAtLocation@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtLocation(const class hand &, const class Ogre::Vector3 &);
?isAtLocation@AI@@UEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+53*8]
?isAtLocation@AI@@UEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isLocationAccessible(const class hand &, const class Ogre::Vector3 &);
?isLocationAccessible@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+54*8]
?isLocationAccessible@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDestinationAccessible(class RootObject *, bool);
?isDestinationAccessible@AI@@QEAA_NPEAVRootObject@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+55*8]
?isDestinationAccessible@AI@@QEAA_NPEAVRootObject@@_N@Z endp

; AI::isDestinationAccessible(const class hand &, const class Ogre::Vector3 &);
?isDestinationAccessible@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+56*8]
?isDestinationAccessible@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDestinationAccessibleAnimal(const class hand &, const class Ogre::Vector3 &);
?isDestinationAccessibleAnimal@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+57*8]
?isDestinationAccessibleAnimal@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtDoorOf(const class hand &, const class Ogre::Vector3 &);
?isAtDoorOf@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+58*8]
?isAtDoorOf@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtDoorOf_Inside(const class hand &, const class Ogre::Vector3 &);
?isAtDoorOf_Inside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+59*8]
?isAtDoorOf_Inside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtDoorOf_Outside(const class hand &, const class Ogre::Vector3 &);
?isAtDoorOf_Outside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+60*8]
?isAtDoorOf_Outside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtDoorOfCurrentLocation(const class hand &, const class Ogre::Vector3 &);
?isAtDoorOfCurrentLocation@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+61*8]
?isAtDoorOfCurrentLocation@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isBuildingComplete(const class hand &, const class Ogre::Vector3 &);
?isBuildingComplete@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+62*8]
?isBuildingComplete@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isSubjectInInventory(const class hand &, const class Ogre::Vector3 &);
?isSubjectInInventory@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+63*8]
?isSubjectInInventory@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isNoEnemiesInVicinity(const class hand &, const class Ogre::Vector3 &);
?isNoEnemiesInVicinity@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+64*8]
?isNoEnemiesInVicinity@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTargetDown(const class hand &, const class Ogre::Vector3 &);
?isTargetDown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+65*8]
?isTargetDown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetIsConscious(const class hand &, const class Ogre::Vector3 &);
?targetIsConscious@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+66*8]
?targetIsConscious@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isLeaderDown(const class hand &, const class Ogre::Vector3 &);
?isLeaderDown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+67*8]
?isLeaderDown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTargetEnemy(const class hand &, const class Ogre::Vector3 &);
?isTargetEnemy@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+68*8]
?isTargetEnemy@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::crowdLimit8(const class hand &, const class Ogre::Vector3 &);
?crowdLimit8@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+69*8]
?crowdLimit8@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasWeapon(const class hand &, const class Ogre::Vector3 &);
?hasWeapon@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+70*8]
?hasWeapon@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasWeaponEquipped(const class hand &, const class Ogre::Vector3 &);
?hasWeaponEquipped@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+71*8]
?hasWeaponEquipped@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasCrossbowEquipped(const class hand &, const class Ogre::Vector3 &);
?hasCrossbowEquipped@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+72*8]
?hasCrossbowEquipped@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasAnythingEquipped(const class hand &, const class Ogre::Vector3 &);
?hasAnythingEquipped@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+73*8]
?hasAnythingEquipped@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAlliesFighting(const class hand &, const class Ogre::Vector3 &);
?isAlliesFighting@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+74*8]
?isAlliesFighting@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isSquadmatesFighting(const class hand &, const class Ogre::Vector3 &);
?isSquadmatesFighting@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+75*8]
?isSquadmatesFighting@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iAmBeingMeleeAttacked_immediate(const class hand &, const class Ogre::Vector3 &);
?iAmBeingMeleeAttacked_immediate@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+76*8]
?iAmBeingMeleeAttacked_immediate@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iAmBeingMeleeAttacked_general(const class hand &, const class Ogre::Vector3 &);
?iAmBeingMeleeAttacked_general@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+77*8]
?iAmBeingMeleeAttacked_general@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAggressionTowards(const class hand &, const class Ogre::Vector3 &);
?isAggressionTowards@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+78*8]
?isAggressionTowards@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAggressionTowardsMe(const class hand &, const class Ogre::Vector3 &);
?isAggressionTowardsMe@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+79*8]
?isAggressionTowardsMe@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isGeneralAggressionLevel(const class hand &, const class Ogre::Vector3 &);
?isGeneralAggressionLevel@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+80*8]
?isGeneralAggressionLevel@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isItemLootable(const class hand &, const class Ogre::Vector3 &);
?isItemLootable@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+81*8]
?isItemLootable@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::amIdle(const class hand &, const class Ogre::Vector3 &);
?amIdle@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+82*8]
?amIdle@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::needsFirstAid(const class hand &, const class Ogre::Vector3 &);
?needsFirstAid@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+83*8]
?needsFirstAid@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::myLegsAreMessedUpButCouldBeFixed(const class hand &, const class Ogre::Vector3 &);
?myLegsAreMessedUpButCouldBeFixed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+84*8]
?myLegsAreMessedUpButCouldBeFixed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::haveFirstAidKit(const class hand &, const class Ogre::Vector3 &);
?haveFirstAidKit@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+85*8]
?haveFirstAidKit@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::needsFirstAid_robot(const class hand &, const class Ogre::Vector3 &);
?needsFirstAid_robot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+86*8]
?needsFirstAid_robot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::haveFirstAidKit_robot(const class hand &, const class Ogre::Vector3 &);
?haveFirstAidKit_robot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+87*8]
?haveFirstAidKit_robot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::needsSplint(const class hand &, const class Ogre::Vector3 &);
?needsSplint@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+88*8]
?needsSplint@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasSplintKit(const class hand &, const class Ogre::Vector3 &);
?hasSplintKit@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+89*8]
?hasSplintKit@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasTools(const class hand &, const class Ogre::Vector3 &);
?hasTools@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+90*8]
?hasTools@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCrouching(const class hand &, const class Ogre::Vector3 &);
?isCrouching@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+91*8]
?isCrouching@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCrouchingOrLying(const class hand &, const class Ogre::Vector3 &);
?isCrouchingOrLying@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+92*8]
?isCrouchingOrLying@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isLyingProne(const class hand &, const class Ogre::Vector3 &);
?isLyingProne@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+93*8]
?isLyingProne@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isMovementAllowed(const class hand &, const class Ogre::Vector3 &);
?isMovementAllowed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+94*8]
?isMovementAllowed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtHome(const class hand &, const class Ogre::Vector3 &);
?isAtHome@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+95*8]
?isAtHome@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtHomeTown(const class hand &, const class Ogre::Vector3 &);
?isAtHomeTown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+96*8]
?isAtHomeTown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetStandingStill(const class hand &, const class Ogre::Vector3 &);
?targetStandingStill@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+97*8]
?targetStandingStill@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasOneWorkingArm(const class hand &, const class Ogre::Vector3 &);
?hasOneWorkingArm@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+98*8]
?hasOneWorkingArm@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasTwoWorkingArms(const class hand &, const class Ogre::Vector3 &);
?hasTwoWorkingArms@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+99*8]
?hasTwoWorkingArms@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isReadyForAction(const class hand &, const class Ogre::Vector3 &);
?isReadyForAction@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+100*8]
?isReadyForAction@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iAmDown(const class hand &, const class Ogre::Vector3 &);
?iAmDown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+101*8]
?iAmDown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iAmProne(const class hand &, const class Ogre::Vector3 &);
?iAmProne@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+102*8]
?iAmProne@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::canGetUp(const class hand &, const class Ogre::Vector3 &);
?canGetUp@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+103*8]
?canGetUp@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreCanGetUp(const class hand &, const class Ogre::Vector3 &);
?scoreCanGetUp@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+104*8]
?scoreCanGetUp@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCarryingSomething(const class hand &, const class Ogre::Vector3 &);
?isCarryingSomething@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+105*8]
?isCarryingSomething@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCarriedDudeInBed(const class hand &, const class Ogre::Vector3 &);
?isCarriedDudeInBed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+106*8]
?isCarriedDudeInBed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCarriedDudeDead(const class hand &, const class Ogre::Vector3 &);
?isCarriedDudeDead@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+107*8]
?isCarriedDudeDead@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCarryingTarget(const class hand &, const class Ogre::Vector3 &);
?isCarryingTarget@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+108*8]
?isCarryingTarget@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::final_gotAKidnapVictim(const class hand &, const class Ogre::Vector3 &);
?final_gotAKidnapVictim@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+109*8]
?final_gotAKidnapVictim@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::final_foundAndPutInCage(const class hand &, const class Ogre::Vector3 &);
?final_foundAndPutInCage@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+110*8]
?final_foundAndPutInCage@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetIsArrested(const class hand &, const class Ogre::Vector3 &);
?targetIsArrested@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+111*8]
?targetIsArrested@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::alarmsInTheVicinity(const class hand &, const class Ogre::Vector3 &);
?alarmsInTheVicinity@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+112*8]
?alarmsInTheVicinity@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::intruderIsOutside(const class hand &, const class Ogre::Vector3 &);
?intruderIsOutside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+113*8]
?intruderIsOutside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::intruderIsOutsideGates(const class hand &, const class Ogre::Vector3 &);
?intruderIsOutsideGates@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+114*8]
?intruderIsOutsideGates@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::amSwimming(const class hand &, const class Ogre::Vector3 &);
?amSwimming@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+115*8]
?amSwimming@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTargetSwimming(const class hand &, const class Ogre::Vector3 &);
?isTargetSwimming@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+116*8]
?isTargetSwimming@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isBeingCarried(const class hand &, const class Ogre::Vector3 &);
?isBeingCarried@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+117*8]
?isBeingCarried@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasBuildingMaterials(const class hand &, const class Ogre::Vector3 &);
?hasBuildingMaterials@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+118*8]
?hasBuildingMaterials@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::buildingHasBuildingMaterials(const class hand &, const class Ogre::Vector3 &);
?buildingHasBuildingMaterials@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+119*8]
?buildingHasBuildingMaterials@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorBroken(const class hand &, const class Ogre::Vector3 &);
?isDoorBroken@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+120*8]
?isDoorBroken@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorOpen(const class hand &, const class Ogre::Vector3 &);
?isDoorOpen@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+121*8]
?isDoorOpen@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorOpenHere(const class hand &, const class Ogre::Vector3 &);
?isDoorOpenHere@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+122*8]
?isDoorOpenHere@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iAmInsideTargetBuilding(const class hand &, const class Ogre::Vector3 &);
?iAmInsideTargetBuilding@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+123*8]
?iAmInsideTargetBuilding@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::farmHasFood(const class hand &, const class Ogre::Vector3 &);
?farmHasFood@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+124*8]
?farmHasFood@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::amHungry(const class hand &, const class Ogre::Vector3 &);
?amHungry@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+125*8]
?amHungry@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iHaveSufficientLockSkill(const class hand &, const class Ogre::Vector3 &);
?iHaveSufficientLockSkill@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+126*8]
?iHaveSufficientLockSkill@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iHaveSufficientLockSkillForShackles(const class hand &, const class Ogre::Vector3 &);
?iHaveSufficientLockSkillForShackles@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+127*8]
?iHaveSufficientLockSkillForShackles@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreIAmInsideTargetBuilding(const class hand &, const class Ogre::Vector3 &);
?scoreIAmInsideTargetBuilding@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+128*8]
?scoreIAmInsideTargetBuilding@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreIAmOutsideTargetBuilding(const class hand &, const class Ogre::Vector3 &);
?scoreIAmOutsideTargetBuilding@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+129*8]
?scoreIAmOutsideTargetBuilding@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::machineHasEmptyInputs(const class hand &, const class Ogre::Vector3 &);
?machineHasEmptyInputs@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+130*8]
?machineHasEmptyInputs@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isMachineOutputFull(const class hand &, const class Ogre::Vector3 &);
?isMachineOutputFull@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+131*8]
?isMachineOutputFull@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::machineHasFullInputs(const class hand &, const class Ogre::Vector3 &);
?machineHasFullInputs@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+132*8]
?machineHasFullInputs@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isMachineOutputEmpty(const class hand &, const class Ogre::Vector3 &);
?isMachineOutputEmpty@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+133*8]
?isMachineOutputEmpty@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::haveSomeResourcesFrom(const class hand &, const class Ogre::Vector3 &);
?haveSomeResourcesFrom@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+134*8]
?haveSomeResourcesFrom@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::haveSomeResourcesFromThisMachineButWantThemGoneIfPossible(const class hand &, const class Ogre::Vector3 &);
?haveSomeResourcesFromThisMachineButWantThemGoneIfPossible@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+135*8]
?haveSomeResourcesFromThisMachineButWantThemGoneIfPossible@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::haveSomeResourcesFor(const class hand &, const class Ogre::Vector3 &);
?haveSomeResourcesFor@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+136*8]
?haveSomeResourcesFor@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isMachineJammed(const class hand &, const class Ogre::Vector3 &);
?isMachineJammed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+137*8]
?isMachineJammed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAnyMachineJammed(const class hand &, const class Ogre::Vector3 &);
?isAnyMachineJammed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+138*8]
?isAnyMachineJammed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isMachineInputInvalid(const class hand &, const class Ogre::Vector3 &);
?isMachineInputInvalid@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+139*8]
?isMachineInputInvalid@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::gotInventoryRoomForResources(const class hand &, const class Ogre::Vector3 &);
?gotInventoryRoomForResources@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+140*8]
?gotInventoryRoomForResources@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isRouteTraceBlocked(const class hand &, const class Ogre::Vector3 &);
?isRouteTraceBlocked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+141*8]
?isRouteTraceBlocked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorLocked(const class hand &, const class Ogre::Vector3 &);
?isDoorLocked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+142*8]
?isDoorLocked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorLockedHere(const class hand &, const class Ogre::Vector3 &);
?isDoorLockedHere@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+143*8]
?isDoorLockedHere@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorLockedAndMeInside(const class hand &, const class Ogre::Vector3 &);
?isDoorLockedAndMeInside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+144*8]
?isDoorLockedAndMeInside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDoorLockedAndMeOutside(const class hand &, const class Ogre::Vector3 &);
?isDoorLockedAndMeOutside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+145*8]
?isDoorLockedAndMeOutside@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isObjectMine(const class hand &, const class Ogre::Vector3 &);
?isObjectMine@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+146*8]
?isObjectMine@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isBuildingDamaged(const class hand &, const class Ogre::Vector3 &);
?isBuildingDamaged@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+147*8]
?isBuildingDamaged@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isBuildingDestroyed(const class hand &, const class Ogre::Vector3 &);
?isBuildingDestroyed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+148*8]
?isBuildingDestroyed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isFullyRested(const class hand &, const class Ogre::Vector3 &);
?isFullyRested@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+149*8]
?isFullyRested@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::machineHasFreeOperatorSlot(const class hand &, const class Ogre::Vector3 &);
?machineHasFreeOperatorSlot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+150*8]
?machineHasFreeOperatorSlot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isDialogDelivered(const class hand &, const class Ogre::Vector3 &);
?isDialogDelivered@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+151*8]
?isDialogDelivered@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isMessageDelivered(const class hand &, const class Ogre::Vector3 &);
?isMessageDelivered@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+152*8]
?isMessageDelivered@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isEnemyForceDefeated(const class hand &, const class Ogre::Vector3 &);
?isEnemyForceDefeated@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+153*8]
?isEnemyForceDefeated@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isInBed(const class hand &, const class Ogre::Vector3 &);
?isInBed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+154*8]
?isInBed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCarryingArmOK(const class hand &, const class Ogre::Vector3 &);
?isCarryingArmOK@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+155*8]
?isCarryingArmOK@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAtAShop(const class hand &, const class Ogre::Vector3 &);
?isAtAShop@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+156*8]
?isAtAShop@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::boughtShitComplete(const class hand &, const class Ogre::Vector3 &);
?boughtShitComplete@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+157*8]
?boughtShitComplete@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isInsideTargetBuilding(const class hand &, const class Ogre::Vector3 &);
?isInsideTargetBuilding@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+158*8]
?isInsideTargetBuilding@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::allDoorsLocked(const class hand &, const class Ogre::Vector3 &);
?allDoorsLocked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+159*8]
?allDoorsLocked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::destinationNotBlockedByFortifications(class RootObject *);
?destinationNotBlockedByFortifications@AI@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_AI_base+160*8]
?destinationNotBlockedByFortifications@AI@@QEAA_NPEAVRootObject@@@Z endp

; AI::destinationNotBlockedByFortifications(const class hand &, const class Ogre::Vector3 &);
?destinationNotBlockedByFortifications@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+161*8]
?destinationNotBlockedByFortifications@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::atLocationGate(const class hand &, const class Ogre::Vector3 &);
?atLocationGate@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+162*8]
?atLocationGate@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isAlly(const class hand &, const class Ogre::Vector3 &);
?isAlly@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+163*8]
?isAlly@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::buildingHasPower(const class hand &, const class Ogre::Vector3 &);
?buildingHasPower@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+164*8]
?buildingHasPower@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::hasDestinationTown(const class hand &, const class Ogre::Vector3 &);
?hasDestinationTown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+165*8]
?hasDestinationTown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isCarryingHealthyTarget(const class hand &, const class Ogre::Vector3 &);
?isCarryingHealthyTarget@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+166*8]
?isCarryingHealthyTarget@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::atDestinationTown(const class hand &, const class Ogre::Vector3 &);
?atDestinationTown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+167*8]
?atDestinationTown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::atPackageTarget(const class hand &, const class Ogre::Vector3 &);
?atPackageTarget@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+168*8]
?atPackageTarget@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::atATown(const class hand &, const class Ogre::Vector3 &);
?atATown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+169*8]
?atATown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetAtATown(const class hand &, const class Ogre::Vector3 &);
?targetAtATown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+170*8]
?targetAtATown@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTiredFromTravel(const class hand &, const class Ogre::Vector3 &);
?isTiredFromTravel@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+171*8]
?isTiredFromTravel@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreGetNextDestinationTown(const class hand &, const class Ogre::Vector3 &);
?scoreGetNextDestinationTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+172*8]
?scoreGetNextDestinationTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreWantsToGetUp_toFeet(const class hand &, const class Ogre::Vector3 &);
?scoreWantsToGetUp_toFeet@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+173*8]
?scoreWantsToGetUp_toFeet@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreWantsToGetUp_stayLow(const class hand &, const class Ogre::Vector3 &);
?scoreWantsToGetUp_stayLow@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+174*8]
?scoreWantsToGetUp_stayLow@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isNearTo(const class hand &, const class Ogre::Vector3 &);
?isNearTo@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+175*8]
?isNearTo@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isWithin50Meters(const class hand &, const class Ogre::Vector3 &);
?isWithin50Meters@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+176*8]
?isWithin50Meters@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isWithin10Meters(const class hand &, const class Ogre::Vector3 &);
?isWithin10Meters@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+177*8]
?isWithin10Meters@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isWithinMyBowRange(const class hand &, const class Ogre::Vector3 &);
?isWithinMyBowRange@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+178*8]
?isWithinMyBowRange@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTargetRestrainedOrKO(const class hand &, const class Ogre::Vector3 &);
?isTargetRestrainedOrKO@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+179*8]
?isTargetRestrainedOrKO@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isOccupantAlive(const class hand &, const class Ogre::Vector3 &);
?isOccupantAlive@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+180*8]
?isOccupantAlive@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::cagesAreAllFull(const class hand &, const class Ogre::Vector3 &);
?cagesAreAllFull@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+181*8]
?cagesAreAllFull@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iAmImprisoned(const class hand &, const class Ogre::Vector3 &);
?iAmImprisoned@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+182*8]
?iAmImprisoned@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetIsImprisoned(const class hand &, const class Ogre::Vector3 &);
?targetIsImprisoned@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+183*8]
?targetIsImprisoned@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetIsMySlave(const class hand &, const class Ogre::Vector3 &);
?targetIsMySlave@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+184*8]
?targetIsMySlave@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iveDitchedAllMyResources(const class hand &, const class Ogre::Vector3 &);
?iveDitchedAllMyResources@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+185*8]
?iveDitchedAllMyResources@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetHasBeenLootedOfResources(const class hand &, const class Ogre::Vector3 &);
?targetHasBeenLootedOfResources@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+186*8]
?targetHasBeenLootedOfResources@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetHasBeenLooted(const class hand &, const class Ogre::Vector3 &);
?targetHasBeenLooted@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+187*8]
?targetHasBeenLooted@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::usingTurret_Any(const class hand &, const class Ogre::Vector3 &);
?usingTurret_Any@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+188*8]
?usingTurret_Any@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::usingTurret_Target(const class hand &, const class Ogre::Vector3 &);
?usingTurret_Target@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+189*8]
?usingTurret_Target@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::strangersAreInMyBuilding(const class hand &, const class Ogre::Vector3 &);
?strangersAreInMyBuilding@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+190*8]
?strangersAreInMyBuilding@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::strangersAreInMyBuilding_andPrivate(const class hand &, const class Ogre::Vector3 &);
?strangersAreInMyBuilding_andPrivate@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+191*8]
?strangersAreInMyBuilding_andPrivate@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::buildingIsPublic(const class hand &, const class Ogre::Vector3 &);
?buildingIsPublic@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+192*8]
?buildingIsPublic@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::targetIsUnarmed(const class hand &, const class Ogre::Vector3 &);
?targetIsUnarmed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+193*8]
?targetIsUnarmed@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::_targetLooksLikeASlave(const class hand &, const class Ogre::Vector3 &);
?_targetLooksLikeASlave@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+194*8]
?_targetLooksLikeASlave@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::carryingExcessLoot(const class hand &, const class Ogre::Vector3 &);
?carryingExcessLoot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+195*8]
?carryingExcessLoot@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isWorking(const class hand &, const class Ogre::Vector3 &);
?isWorking@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+196*8]
?isWorking@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::gotAFoodItem(const class hand &, const class Ogre::Vector3 &);
?gotAFoodItem@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+197*8]
?gotAFoodItem@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::iHaveSomeSlaves(const class hand &, const class Ogre::Vector3 &);
?iHaveSomeSlaves@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+198*8]
?iHaveSomeSlaves@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::getALootableResourceItemFromTargetThatWeHaveStorageFor(class Character *);
?getALootableResourceItemFromTargetThatWeHaveStorageFor@AI@@QEAAPEAVItem@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+199*8]
?getALootableResourceItemFromTargetThatWeHaveStorageFor@AI@@QEAAPEAVItem@@PEAVCharacter@@@Z endp

; AI::targetLooksLikeASlave(class Character *);
?targetLooksLikeASlave@AI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+200*8]
?targetLooksLikeASlave@AI@@QEAA_NPEAVCharacter@@@Z endp

; AI::slaveIsEscaping(class Character *);
?slaveIsEscaping@AI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+201*8]
?slaveIsEscaping@AI@@QEAA_NPEAVCharacter@@@Z endp

; AI::slaveIsFollowingOrders(class Character *);
?slaveIsFollowingOrders@AI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+202*8]
?slaveIsFollowingOrders@AI@@QEAA_NPEAVCharacter@@@Z endp

; AI::isRunningAway(class Character *, class RootObject *);
?isRunningAway@AI@@QEAA_NPEAVCharacter@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_AI_base+203*8]
?isRunningAway@AI@@QEAA_NPEAVCharacter@@PEAVRootObject@@@Z endp

; AI::isWearingShackles(const class hand &, const class Ogre::Vector3 &);
?isWearingShackles@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+204*8]
?isWearingShackles@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isWearingShackles_locked(const class hand &, const class Ogre::Vector3 &);
?isWearingShackles_locked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+205*8]
?isWearingShackles_locked@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTargetEscapee(const class hand &, const class Ogre::Vector3 &);
?isTargetEscapee@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+206*8]
?isTargetEscapee@AI@@QEAA_NAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::isTargetInRangeForOrders(const class Ogre::Vector3 &);
?isTargetInRangeForOrders@AI@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+207*8]
?isTargetInRangeForOrders@AI@@QEAA_NAEBVVector3@Ogre@@@Z endp

; AI::isTargetInRangeForOrders(class RootObject *);
?isTargetInRangeForOrders@AI@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_AI_base+208*8]
?isTargetInRangeForOrders@AI@@QEAA_NPEAVRootObject@@@Z endp

; AI::isTargetInRangeForHOLDMode_hostiles(class Character *);
?isTargetInRangeForHOLDMode_hostiles@AI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+209*8]
?isTargetInRangeForHOLDMode_hostiles@AI@@QEAA_NPEAVCharacter@@@Z endp

; AI::getMaxTargetRangeForOrdersSq();
?getMaxTargetRangeForOrdersSq@AI@@QEAAMXZ proc EXPORT
jmp function_pointers[_AI_base+210*8]
?getMaxTargetRangeForOrdersSq@AI@@QEAAMXZ endp

; AI::targetMyself(const class hand &, class hand &, bool);
?targetMyself@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+211*8]
?targetMyself@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findWeapon(const class hand &, class hand &, bool);
?findWeapon@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+212*8]
?findWeapon@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSomebodyToLoot(const class hand &, class hand &, bool);
?findSomebodyToLoot@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+213*8]
?findSomebodyToLoot@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findAttackerOf(const class hand &, class hand &, bool);
?findAttackerOf@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+214*8]
?findAttackerOf@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findAggressiveFellows(const class hand &, class hand &, bool);
?findAggressiveFellows@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+215*8]
?findAggressiveFellows@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::wantGuardAggressionNeutralTargetCheck(class Character *);
?wantGuardAggressionNeutralTargetCheck@AI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+216*8]
?wantGuardAggressionNeutralTargetCheck@AI@@QEAA_NPEAVCharacter@@@Z endp

; AI::findBounty(const class hand &, class hand &, bool);
?findBounty@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+217*8]
?findBounty@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findKOIntruder(const class hand &, class hand &, bool);
?findKOIntruder@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+218*8]
?findKOIntruder@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findKOIntruder_town(const class hand &, class hand &, bool);
?findKOIntruder_town@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+219*8]
?findKOIntruder_town@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findTurretToUse(const class hand &, class hand &, bool);
?findTurretToUse@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+220*8]
?findTurretToUse@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findTurretToUseOnMyBuilding(const class hand &, class hand &, bool);
?findTurretToUseOnMyBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+221*8]
?findTurretToUseOnMyBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMeleeOpponentForTerritorialAggression(const class hand &, class hand &, bool);
?findMeleeOpponentForTerritorialAggression@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+222*8]
?findMeleeOpponentForTerritorialAggression@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMeleeOpponentForFightingSlave(const class hand &, class hand &, bool);
?findMeleeOpponentForFightingSlave@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+223*8]
?findMeleeOpponentForFightingSlave@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMeleeOpponentForTerritorialAggressionWithNeutrals(const class hand &, class hand &, bool);
?findMeleeOpponentForTerritorialAggressionWithNeutrals@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+224*8]
?findMeleeOpponentForTerritorialAggressionWithNeutrals@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMeleeOpponent(const class hand &, class hand &, bool);
?findMeleeOpponent@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+225*8]
?findMeleeOpponent@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMeleeOpponentNearMyTown(const class hand &, class hand &, bool);
?findMeleeOpponentNearMyTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+226*8]
?findMeleeOpponentNearMyTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMeleeOpponentFromSquad(const class hand &, class hand &, bool);
?findMeleeOpponentFromSquad@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+227*8]
?findMeleeOpponentFromSquad@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::shouldIFreeMySlaveBuddies(class Character *);
?shouldIFreeMySlaveBuddies@AI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AI_base+228*8]
?shouldIFreeMySlaveBuddies@AI@@QEAA_NPEAVCharacter@@@Z endp

; AI::findAllyInNeed(const class hand &, class hand &, bool);
?findAllyInNeed@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+229*8]
?findAllyInNeed@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findAllyInNeed_stayInTown(const class hand &, class hand &, bool);
?findAllyInNeed_stayInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+230*8]
?findAllyInNeed_stayInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSquadmateInNeed(const class hand &, class hand &, bool);
?findSquadmateInNeed@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+231*8]
?findSquadmateInNeed@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findHome(const class hand &, class hand &, bool);
?findHome@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+232*8]
?findHome@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findShopkeeperNode(const class hand &, class hand &, bool);
?findShopkeeperNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+233*8]
?findShopkeeperNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findDefensiveNode(const class hand &, class hand &, bool);
?findDefensiveNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+234*8]
?findDefensiveNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findGuardNodeForBuilding_inOrOut(const class hand &, class hand &, bool);
?findGuardNodeForBuilding_inOrOut@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+235*8]
?findGuardNodeForBuilding_inOrOut@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findGuardNodeForBuilding_indoorOnly(const class hand &, class hand &, bool);
?findGuardNodeForBuilding_indoorOnly@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+236*8]
?findGuardNodeForBuilding_indoorOnly@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findGuardNodeForBuilding_nearestPlayer(class hand &, bool);
?findGuardNodeForBuilding_nearestPlayer@AI@@QEAAMAEAVhand@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+237*8]
?findGuardNodeForBuilding_nearestPlayer@AI@@QEAAMAEAVhand@@_N@Z endp

; AI::findGuardNodeForTown(const class hand &, class hand &, bool);
?findGuardNodeForTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+238*8]
?findGuardNodeForTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findGeneralNode(const class hand &, class hand &, bool);
?findGeneralNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+239*8]
?findGeneralNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findGoodRecruitNode(const class hand &, class hand &, bool);
?findGoodRecruitNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+240*8]
?findGoodRecruitNode@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findPublicGeneralNodeInTown(const class hand &, class hand &, bool);
?findPublicGeneralNodeInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+241*8]
?findPublicGeneralNodeInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findWoundedAllies(const class hand &, class hand &, bool);
?findWoundedAllies@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+242*8]
?findWoundedAllies@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSplintableAllies(const class hand &, class hand &, bool);
?findSplintableAllies@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+243*8]
?findSplintableAllies@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findWoundedAllies_Robots(const class hand &, class hand &, bool);
?findWoundedAllies_Robots@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+244*8]
?findWoundedAllies_Robots@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::_findWoundedAllies(class hand &, bool);
?_findWoundedAllies@AI@@QEAAMAEAVhand@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+245*8]
?_findWoundedAllies@AI@@QEAAMAEAVhand@@_N@Z endp

; AI::findPrisonerFreeToGo(const class hand &, class hand &, bool);
?findPrisonerFreeToGo@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+246*8]
?findPrisonerFreeToGo@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findPrisonerToLiberate(const class hand &, class hand &, bool);
?findPrisonerToLiberate@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+247*8]
?findPrisonerToLiberate@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findPrisonerWithContraband(const class hand &, class hand &, bool);
?findPrisonerWithContraband@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+248*8]
?findPrisonerWithContraband@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::getCurrentBuilding(const class hand &, class hand &, bool);
?getCurrentBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+249*8]
?getCurrentBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::getDestinationBuilding(const class hand &, class hand &, bool);
?getDestinationBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+250*8]
?getDestinationBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findJammedMachine(const class hand &, class hand &, bool);
?findJammedMachine@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+251*8]
?findJammedMachine@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findResourceSourceForMe(const class hand &, class hand &, bool);
?findResourceSourceForMe@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+252*8]
?findResourceSourceForMe@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findResourceDestinationForMe(const class hand &, class hand &, bool);
?findResourceDestinationForMe@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+253*8]
?findResourceDestinationForMe@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findResourceDestinationFor(const class hand &, class hand &, bool);
?findResourceDestinationFor@AI@@QEAA_NAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+254*8]
?findResourceDestinationFor@AI@@QEAA_NAEBVhand@@AEAV2@_N@Z endp

; AI::findResourceDestinationForMyLoot(const class hand &, class hand &, bool);
?findResourceDestinationForMyLoot@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+255*8]
?findResourceDestinationForMyLoot@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMineToWorkAt(const class hand &, class hand &, bool);
?findMineToWorkAt@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+256*8]
?findMineToWorkAt@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findMineToWorkAt_pretend(const class hand &, class hand &, bool);
?findMineToWorkAt_pretend@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+257*8]
?findMineToWorkAt_pretend@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSomethingToDoInHome(const class hand &, class hand &, bool);
?findSomethingToDoInHome@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+258*8]
?findSomethingToDoInHome@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSomethingToDo_lazy(const class hand &, class hand &, bool);
?findSomethingToDo_lazy@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+259*8]
?findSomethingToDo_lazy@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findThrone(const class hand &, class hand &, bool);
?findThrone@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+260*8]
?findThrone@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findBuildingMaterials(const class hand &, class hand &, bool);
?findBuildingMaterials@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+261*8]
?findBuildingMaterials@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findTalkTarget(const class hand &, class hand &, bool);
?findTalkTarget@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+262*8]
?findTalkTarget@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findDisabledAlly(const class hand &, class hand &, bool);
?findDisabledAlly@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+263*8]
?findDisabledAlly@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findDisabledDude(unsigned int, unsigned int, bool);
?findDisabledDude@AI@@QEAA?AVhand@@II_N@Z proc EXPORT
jmp function_pointers[_AI_base+264*8]
?findDisabledDude@AI@@QEAA?AVhand@@II_N@Z endp

; AI::findDisabledNonAlly(const class hand &, class hand &, bool);
?findDisabledNonAlly@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+265*8]
?findDisabledNonAlly@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSomeoneWhoWouldMakeAGoodSlave(const class hand &, class hand &, bool);
?findSomeoneWhoWouldMakeAGoodSlave@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+266*8]
?findSomeoneWhoWouldMakeAGoodSlave@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findBadSlaves(const class hand &, class hand &, bool);
?findBadSlaves@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+267*8]
?findBadSlaves@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findNewSlaveOrPrisonerToProcess(const class hand &, class hand &, bool);
?findNewSlaveOrPrisonerToProcess@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+268*8]
?findNewSlaveOrPrisonerToProcess@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findRandomOneOfMySlaves(const class hand &, class hand &, bool);
?findRandomOneOfMySlaves@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+269*8]
?findRandomOneOfMySlaves@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findConsciousSlaveInTown(const class hand &, class hand &, bool);
?findConsciousSlaveInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+270*8]
?findConsciousSlaveInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findConsciousSlaveInTownForShipping(const class hand &, class hand &, bool);
?findConsciousSlaveInTownForShipping@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+271*8]
?findConsciousSlaveInTownForShipping@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findConsciousSlaveInTown_unholy(const class hand &, class hand &, bool);
?findConsciousSlaveInTown_unholy@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+272*8]
?findConsciousSlaveInTown_unholy@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findKOedSlaveOfMine(const class hand &, class hand &, bool);
?findKOedSlaveOfMine@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+273*8]
?findKOedSlaveOfMine@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findCorpse_onGround(const class hand &, class hand &, bool);
?findCorpse_onGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+274*8]
?findCorpse_onGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findCorpse_onGround_detail(const class hand &, class hand &, bool, bool, bool);
?findCorpse_onGround_detail@AI@@QEAAMAEBVhand@@AEAV2@_N22@Z proc EXPORT
jmp function_pointers[_AI_base+275*8]
?findCorpse_onGround_detail@AI@@QEAAMAEBVhand@@AEAV2@_N22@Z endp

; AI::findCorpse_includingCages(const class hand &, class hand &, bool);
?findCorpse_includingCages@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+276*8]
?findCorpse_includingCages@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findDeadOrKOBody_onGround(const class hand &, class hand &, bool);
?findDeadOrKOBody_onGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+277*8]
?findDeadOrKOBody_onGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findCrops(const class hand &, class hand &, bool);
?findCrops@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+278*8]
?findCrops@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findOwnedFreeBed(const class hand &, class hand &, bool);
?findOwnedFreeBed@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+279*8]
?findOwnedFreeBed@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findOwnedFreeCage(const class hand &, class hand &, bool);
?findOwnedFreeCage@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+280*8]
?findOwnedFreeCage@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSlaveBuyer(const class hand &, class hand &, bool);
?findSlaveBuyer@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+281*8]
?findSlaveBuyer@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findEmptyCageBelongingToMaster(const class hand &, class hand &, bool);
?findEmptyCageBelongingToMaster@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+282*8]
?findEmptyCageBelongingToMaster@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findOwnedFullCage_MarkForDeath(const class hand &, class hand &, bool);
?findOwnedFullCage_MarkForDeath@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+283*8]
?findOwnedFullCage_MarkForDeath@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findCorpseDisposal(const class hand &, class hand &, bool);
?findCorpseDisposal@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+284*8]
?findCorpseDisposal@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findShop(const class hand &, class hand &, bool);
?findShop@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+285*8]
?findShop@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findPackageTarget(const class hand &, class hand &, bool);
?findPackageTarget@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+286*8]
?findPackageTarget@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::getDestinationGate(const class hand &, class hand &, bool);
?getDestinationGate@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+287*8]
?getDestinationGate@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::getBuildingToSmash(const class hand &, class hand &, bool);
?getBuildingToSmash@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+288*8]
?getBuildingToSmash@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSomethingToBuild(const class hand &, class hand &, bool);
?findSomethingToBuild@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+289*8]
?findSomethingToBuild@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findNearestHomeBase(const class hand &, class hand &, bool);
?findNearestHomeBase@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+290*8]
?findNearestHomeBase@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findNextTown(const class hand &, class hand &, bool);
?findNextTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+291*8]
?findNextTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findSomethingToLootFoodFrom(const class hand &, class hand &, bool);
?findSomethingToLootFoodFrom@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+292*8]
?findSomethingToLootFoodFrom@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findFoodOnGround(const class hand &, class hand &, bool);
?findFoodOnGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+293*8]
?findFoodOnGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findLimbOnGround(const class hand &, class hand &, bool);
?findLimbOnGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+294*8]
?findLimbOnGround@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::targetMyLeader(const class hand &, class hand &, bool);
?targetMyLeader@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+295*8]
?targetMyLeader@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::targetMySlavemaster(const class hand &, class hand &, bool);
?targetMySlavemaster@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+296*8]
?targetMySlavemaster@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::targetMyLeader_theRealOne(const class hand &, class hand &, bool);
?targetMyLeader_theRealOne@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+297*8]
?targetMyLeader_theRealOne@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findUnlockedDoorHere(const class hand &, class hand &, bool);
?findUnlockedDoorHere@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+298*8]
?findUnlockedDoorHere@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findLockedOrClosedDoorHere(const class hand &, class hand &, bool);
?findLockedOrClosedDoorHere@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+299*8]
?findLockedOrClosedDoorHere@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findStrangersInMyBuilding(const class hand &, class hand &, bool);
?findStrangersInMyBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+300*8]
?findStrangersInMyBuilding@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findUnlockedCage(const class hand &, class hand &, bool);
?findUnlockedCage@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+301*8]
?findUnlockedCage@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findRandomBuildingInTown(const class hand &, class hand &, bool);
?findRandomBuildingInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+302*8]
?findRandomBuildingInTown@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findFogmanWorshipTarget(const class hand &, class hand &, bool);
?findFogmanWorshipTarget@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+303*8]
?findFogmanWorshipTarget@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findAnimalsToLoot(const class hand &, class hand &, bool);
?findAnimalsToLoot@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+304*8]
?findAnimalsToLoot@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findAllyAnimalWithFoodInMouth(const class hand &, class hand &, bool);
?findAllyAnimalWithFoodInMouth@AI@@QEAAMAEBVhand@@AEAV2@_N@Z proc EXPORT
jmp function_pointers[_AI_base+305*8]
?findAllyAnimalWithFoodInMouth@AI@@QEAAMAEBVhand@@AEAV2@_N@Z endp

; AI::findBodyWithResourceToLoot(class GameData *, bool);
?findBodyWithResourceToLoot@AI@@QEAAPEAVCharacter@@PEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+306*8]
?findBodyWithResourceToLoot@AI@@QEAAPEAVCharacter@@PEAVGameData@@_N@Z endp

; AI::_findOwnedCageThing(bool, enum BuildingFunction);
?_findOwnedCageThing@AI@@QEAAPEAVUseableStuff@@_NW4BuildingFunction@@@Z proc EXPORT
jmp function_pointers[_AI_base+307*8]
?_findOwnedCageThing@AI@@QEAAPEAVUseableStuff@@_NW4BuildingFunction@@@Z endp

; AI::findNode(enum NodeType, bool, bool);
?findNode@AI@@QEAA?AVhand@@W4NodeType@@_N1@Z proc EXPORT
jmp function_pointers[_AI_base+308*8]
?findNode@AI@@QEAA?AVhand@@W4NodeType@@_N1@Z endp

; AI::itemOnGroundStealingCheckIsSafe(class Item *);
?itemOnGroundStealingCheckIsSafe@AI@@QEAA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_AI_base+309*8]
?itemOnGroundStealingCheckIsSafe@AI@@QEAA_NPEAVItem@@@Z endp

; AI::findSomeoneToLoot(bool);
?findSomeoneToLoot@AI@@QEAAPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+310*8]
?findSomeoneToLoot@AI@@QEAAPEAVCharacter@@_N@Z endp

; AI::getAllLocalMachines(class lektor<Building *> &, unsigned int);
?getAllLocalMachines@AI@@QEAAXAEAV?$lektor@PEAVBuilding@@@@I@Z proc EXPORT
jmp function_pointers[_AI_base+311*8]
?getAllLocalMachines@AI@@QEAAXAEAV?$lektor@PEAVBuilding@@@@I@Z endp

; AI::findResourceStorageBulidingFor(class GameData *, class StorageBuilding *);
?findResourceStorageBulidingFor@AI@@QEAAPEAVStorageBuilding@@PEAVGameData@@PEAV2@@Z proc EXPORT
jmp function_pointers[_AI_base+312*8]
?findResourceStorageBulidingFor@AI@@QEAAPEAVStorageBuilding@@PEAVGameData@@PEAV2@@Z endp

?_NV_rateWeapon@AI@@QEAAMPEAVItem@@@Z proc EXPORT
?_NV_rateWeapon@AI@@QEAAMPEAVItem@@@Z endp

; AI::rateWeapon(class Item *);
?rateWeapon@AI@@UEAAMPEAVItem@@@Z proc EXPORT
jmp function_pointers[_AI_base+313*8]
?rateWeapon@AI@@UEAAMPEAVItem@@@Z endp

?_NV_canUseWeapon@AI@@QEBA_NPEAVItem@@@Z proc EXPORT
?_NV_canUseWeapon@AI@@QEBA_NPEAVItem@@@Z endp

; AI::canUseWeapon(class Item *);
?canUseWeapon@AI@@UEBA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_AI_base+314*8]
?canUseWeapon@AI@@UEBA_NPEAVItem@@@Z endp

; AI::scoreTargetRange(float);
?scoreTargetRange@AI@@QEAAMM@Z proc EXPORT
jmp function_pointers[_AI_base+315*8]
?scoreTargetRange@AI@@QEAAMM@Z endp

; AI::scoreDistanceTo(class RootObject *, bool);
?scoreDistanceTo@AI@@QEAAMPEAVRootObject@@_N@Z proc EXPORT
jmp function_pointers[_AI_base+316*8]
?scoreDistanceTo@AI@@QEAAMPEAVRootObject@@_N@Z endp

; AI::scoreSplint(const class hand &, const class Ogre::Vector3 &);
?scoreSplint@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+317*8]
?scoreSplint@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFirstAid(const class hand &, const class Ogre::Vector3 &);
?scoreFirstAid@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+318*8]
?scoreFirstAid@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFixMyLegs(const class hand &, const class Ogre::Vector3 &);
?scoreFixMyLegs@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+319*8]
?scoreFixMyLegs@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFirstAidRobot(const class hand &, const class Ogre::Vector3 &);
?scoreFirstAidRobot@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+320*8]
?scoreFirstAidRobot@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scorePutCarriedDudeDown(const class hand &, const class Ogre::Vector3 &);
?scorePutCarriedDudeDown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+321*8]
?scorePutCarriedDudeDown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreJobMedic(const class hand &, const class Ogre::Vector3 &);
?scoreJobMedic@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+322*8]
?scoreJobMedic@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scorePutCarriedDudeInBed(const class hand &, const class Ogre::Vector3 &);
?scorePutCarriedDudeInBed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+323*8]
?scorePutCarriedDudeInBed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scorePutCarriedDudeInCage(const class hand &, const class Ogre::Vector3 &);
?scorePutCarriedDudeInCage@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+324*8]
?scorePutCarriedDudeInCage@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreCarryingIntruder(const class hand &, const class Ogre::Vector3 &);
?scoreCarryingIntruder@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+325*8]
?scoreCarryingIntruder@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFindAndRescue(const class hand &, const class Ogre::Vector3 &);
?scoreFindAndRescue@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+326*8]
?scoreFindAndRescue@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFindAndRescueIfTheresBeds(const class hand &, const class Ogre::Vector3 &);
?scoreFindAndRescueIfTheresBeds@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+327*8]
?scoreFindAndRescueIfTheresBeds@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreRescueLeader(const class hand &, const class Ogre::Vector3 &);
?scoreRescueLeader@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+328*8]
?scoreRescueLeader@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFindAndKidnap(const class hand &, const class Ogre::Vector3 &);
?scoreFindAndKidnap@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+329*8]
?scoreFindAndKidnap@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreKidnapperCageJob(const class hand &, const class Ogre::Vector3 &);
?scoreKidnapperCageJob@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+330*8]
?scoreKidnapperCageJob@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreShopping(const class hand &, const class Ogre::Vector3 &);
?scoreShopping@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+331*8]
?scoreShopping@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreProtectAllies@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreProtectAllies@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreProtectAllies(const class hand &, const class Ogre::Vector3 &);
?scoreProtectAllies@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+332*8]
?scoreProtectAllies@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreStayClose@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreStayClose@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreStayClose(const class hand &, const class Ogre::Vector3 &);
?scoreStayClose@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+333*8]
?scoreStayClose@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreStayCloseIsh@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreStayCloseIsh@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreStayCloseIsh(const class hand &, const class Ogre::Vector3 &);
?scoreStayCloseIsh@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+334*8]
?scoreStayCloseIsh@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scorePutDudeInCage(const class hand &);
?scorePutDudeInCage@AI@@QEAAMAEBVhand@@@Z proc EXPORT
jmp function_pointers[_AI_base+335*8]
?scorePutDudeInCage@AI@@QEAAMAEBVhand@@@Z endp

?_NV_scoreUnderAttack@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreUnderAttack@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreUnderAttack(const class hand &, const class Ogre::Vector3 &);
?scoreUnderAttack@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+336*8]
?scoreUnderAttack@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreEmptyMachine@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreEmptyMachine@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreEmptyMachine(const class hand &, const class Ogre::Vector3 &);
?scoreEmptyMachine@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+337*8]
?scoreEmptyMachine@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreNone@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreNone@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreNone(const class hand &, const class Ogre::Vector3 &);
?scoreNone@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+338*8]
?scoreNone@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreCannibalKill@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreCannibalKill@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreCannibalKill(const class hand &, const class Ogre::Vector3 &);
?scoreCannibalKill@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+339*8]
?scoreCannibalKill@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreAutoMachinery@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreAutoMachinery@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreAutoMachinery(const class hand &, const class Ogre::Vector3 &);
?scoreAutoMachinery@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+340*8]
?scoreAutoMachinery@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreCollectOutputResource@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreCollectOutputResource@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreCollectOutputResource(const class hand &, const class Ogre::Vector3 &);
?scoreCollectOutputResource@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+341*8]
?scoreCollectOutputResource@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreCollectOutputResourceForBuildMats@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreCollectOutputResourceForBuildMats@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreCollectOutputResourceForBuildMats(const class hand &, const class Ogre::Vector3 &);
?scoreCollectOutputResourceForBuildMats@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+342*8]
?scoreCollectOutputResourceForBuildMats@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreGetFood_inHomeTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreGetFood_inHomeTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreGetFood_inHomeTown(const class hand &, const class Ogre::Vector3 &);
?scoreGetFood_inHomeTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+343*8]
?scoreGetFood_inHomeTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreFindFoodOnGround@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreFindFoodOnGround@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFindFoodOnGround(const class hand &, const class Ogre::Vector3 &);
?scoreFindFoodOnGround@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+344*8]
?scoreFindFoodOnGround@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreGetFood_inHomeTown_andFeedAnimals@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreGetFood_inHomeTown_andFeedAnimals@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreGetFood_inHomeTown_andFeedAnimals(const class hand &, const class Ogre::Vector3 &);
?scoreGetFood_inHomeTown_andFeedAnimals@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+345*8]
?scoreGetFood_inHomeTown_andFeedAnimals@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreUnlockDoorHere@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreUnlockDoorHere@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreUnlockDoorHere(const class hand &, const class Ogre::Vector3 &);
?scoreUnlockDoorHere@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+346*8]
?scoreUnlockDoorHere@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreGetOutOfBed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreGetOutOfBed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreGetOutOfBed(const class hand &, const class Ogre::Vector3 &);
?scoreGetOutOfBed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+347*8]
?scoreGetOutOfBed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreGetOutOfBedOnceFullyHealed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreGetOutOfBedOnceFullyHealed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreGetOutOfBedOnceFullyHealed(const class hand &, const class Ogre::Vector3 &);
?scoreGetOutOfBedOnceFullyHealed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+348*8]
?scoreGetOutOfBedOnceFullyHealed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreGoToBed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreGoToBed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreGoToBed(const class hand &, const class Ogre::Vector3 &);
?scoreGoToBed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+349*8]
?scoreGoToBed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHomeIsNotLockedUp@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHomeIsNotLockedUp@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHomeIsNotLockedUp(const class hand &, const class Ogre::Vector3 &);
?scoreHomeIsNotLockedUp@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+350*8]
?scoreHomeIsNotLockedUp@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreDontLeaveTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreDontLeaveTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreDontLeaveTown(const class hand &, const class Ogre::Vector3 &);
?scoreDontLeaveTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+351*8]
?scoreDontLeaveTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreFoundCages@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreFoundCages@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreFoundCages(const class hand &, const class Ogre::Vector3 &);
?scoreFoundCages@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+352*8]
?scoreFoundCages@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHasWorkingArm@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHasWorkingArm@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHasWorkingArm(const class hand &, const class Ogre::Vector3 &);
?scoreHasWorkingArm@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+353*8]
?scoreHasWorkingArm@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreUseTurret@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreUseTurret@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreUseTurret(const class hand &, const class Ogre::Vector3 &);
?scoreUseTurret@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+354*8]
?scoreUseTurret@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreAggressiveAction@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreAggressiveAction@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreAggressiveAction(const class hand &, const class Ogre::Vector3 &);
?scoreAggressiveAction@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+355*8]
?scoreAggressiveAction@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreBashGate@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreBashGate@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreBashGate(const class hand &, const class Ogre::Vector3 &);
?scoreBashGate@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+356*8]
?scoreBashGate@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreNPCEscapeCageOpportunity@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreNPCEscapeCageOpportunity@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreNPCEscapeCageOpportunity(const class hand &, const class Ogre::Vector3 &);
?scoreNPCEscapeCageOpportunity@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+357*8]
?scoreNPCEscapeCageOpportunity@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score01@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score01@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score01(const class hand &, const class Ogre::Vector3 &);
?score01@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+358*8]
?score01@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score025@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score025@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score025(const class hand &, const class Ogre::Vector3 &);
?score025@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+359*8]
?score025@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score05@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score05@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score05(const class hand &, const class Ogre::Vector3 &);
?score05@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+360*8]
?score05@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score08@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score08@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score08(const class hand &, const class Ogre::Vector3 &);
?score08@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+361*8]
?score08@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score10@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score10@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score10(const class hand &, const class Ogre::Vector3 &);
?score10@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+362*8]
?score10@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreCanSeeTarget@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreCanSeeTarget@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreCanSeeTarget(const class hand &, const class Ogre::Vector3 &);
?scoreCanSeeTarget@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+363*8]
?scoreCanSeeTarget@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score12@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score12@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score12(const class hand &, const class Ogre::Vector3 &);
?score12@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+364*8]
?score12@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score15@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score15@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score15(const class hand &, const class Ogre::Vector3 &);
?score15@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+365*8]
?score15@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_score20@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_score20@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::score20(const class hand &, const class Ogre::Vector3 &);
?score20@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+366*8]
?score20@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreRandomFluff@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreRandomFluff@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreRandomFluff(const class hand &, const class Ogre::Vector3 &);
?scoreRandomFluff@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+367*8]
?scoreRandomFluff@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHuntingBlood@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHuntingBlood@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHuntingBlood(const class hand &, const class Ogre::Vector3 &);
?scoreHuntingBlood@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+368*8]
?scoreHuntingBlood@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHuntingEggs@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHuntingEggs@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHuntingEggs(const class hand &, const class Ogre::Vector3 &);
?scoreHuntingEggs@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+369*8]
?scoreHuntingEggs@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreTargetInDanger@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreTargetInDanger@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreTargetInDanger(const class hand &, const class Ogre::Vector3 &);
?scoreTargetInDanger@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+370*8]
?scoreTargetInDanger@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreAttackEnemies@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreAttackEnemies@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreAttackEnemies(const class hand &, const class Ogre::Vector3 &);
?scoreAttackEnemies@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+371*8]
?scoreAttackEnemies@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreMeleeAttack@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreMeleeAttack@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreMeleeAttack(const class hand &, const class Ogre::Vector3 &);
?scoreMeleeAttack@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+372*8]
?scoreMeleeAttack@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreRangedAttack@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreRangedAttack@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreRangedAttack(const class hand &, const class Ogre::Vector3 &);
?scoreRangedAttack@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+373*8]
?scoreRangedAttack@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreRunAway@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreRunAway@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreRunAway(const class hand &, const class Ogre::Vector3 &);
?scoreRunAway@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+374*8]
?scoreRunAway@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreRetreat@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreRetreat@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreRetreat(const class hand &, const class Ogre::Vector3 &);
?scoreRetreat@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+375*8]
?scoreRetreat@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreMove@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreMove@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreMove(const class hand &, const class Ogre::Vector3 &);
?scoreMove@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+376*8]
?scoreMove@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreDontWantToBeUnarmed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreDontWantToBeUnarmed@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreDontWantToBeUnarmed(const class hand &, const class Ogre::Vector3 &);
?scoreDontWantToBeUnarmed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+377*8]
?scoreDontWantToBeUnarmed@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreLiftObject@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreLiftObject@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreLiftObject(const class hand &, const class Ogre::Vector3 &);
?scoreLiftObject@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+378*8]
?scoreLiftObject@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreLiftIntruder@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreLiftIntruder@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreLiftIntruder(const class hand &, const class Ogre::Vector3 &);
?scoreLiftIntruder@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+379*8]
?scoreLiftIntruder@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreChainNewSlave@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreChainNewSlave@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreChainNewSlave(const class hand &, const class Ogre::Vector3 &);
?scoreChainNewSlave@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+380*8]
?scoreChainNewSlave@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreNotDown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreNotDown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreNotDown(const class hand &, const class Ogre::Vector3 &);
?scoreNotDown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+381*8]
?scoreNotDown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreNoMoreThan4Slaves@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreNoMoreThan4Slaves@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreNoMoreThan4Slaves(const class hand &, const class Ogre::Vector3 &);
?scoreNoMoreThan4Slaves@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+382*8]
?scoreNoMoreThan4Slaves@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreSlaveExportTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreSlaveExportTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreSlaveExportTown(const class hand &, const class Ogre::Vector3 &);
?scoreSlaveExportTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+383*8]
?scoreSlaveExportTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHasSomeSlaves@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHasSomeSlaves@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHasSomeSlaves(const class hand &, const class Ogre::Vector3 &);
?scoreHasSomeSlaves@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+384*8]
?scoreHasSomeSlaves@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHasSomeSlavesAndAtImportTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHasSomeSlavesAndAtImportTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHasSomeSlavesAndAtImportTown(const class hand &, const class Ogre::Vector3 &);
?scoreHasSomeSlavesAndAtImportTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+385*8]
?scoreHasSomeSlavesAndAtImportTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreAmTheRealLeader@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreAmTheRealLeader@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreAmTheRealLeader(const class hand &, const class Ogre::Vector3 &);
?scoreAmTheRealLeader@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+386*8]
?scoreAmTheRealLeader@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreAtAttackableTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreAtAttackableTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreAtAttackableTown(const class hand &, const class Ogre::Vector3 &);
?scoreAtAttackableTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+387*8]
?scoreAtAttackableTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreDogPlaying@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreDogPlaying@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreDogPlaying(const class hand &, const class Ogre::Vector3 &);
?scoreDogPlaying@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+388*8]
?scoreDogPlaying@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreDogPlayingChase@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreDogPlayingChase@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreDogPlayingChase(const class hand &, const class Ogre::Vector3 &);
?scoreDogPlayingChase@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+389*8]
?scoreDogPlayingChase@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreHomeIsPrivate@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreHomeIsPrivate@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreHomeIsPrivate(const class hand &, const class Ogre::Vector3 &);
?scoreHomeIsPrivate@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+390*8]
?scoreHomeIsPrivate@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreNotKOOrPlayingDead@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreNotKOOrPlayingDead@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreNotKOOrPlayingDead(const class hand &, const class Ogre::Vector3 &);
?scoreNotKOOrPlayingDead@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+391*8]
?scoreNotKOOrPlayingDead@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_scoreTargetInMyTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_scoreTargetInMyTown@AI@@QEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AI::scoreTargetInMyTown(const class hand &, const class Ogre::Vector3 &);
?scoreTargetInMyTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AI_base+392*8]
?scoreTargetInMyTown@AI@@UEAAMAEBVhand@@AEBVVector3@Ogre@@@Z endp
