
?_CONSTRUCTOR@AIResultsCacher@AI@@QEAAPEAV12@PEAV2@@Z proc EXPORT
?_CONSTRUCTOR@AIResultsCacher@AI@@QEAAPEAV12@PEAV2@@Z endp

; AI::AIResultsCacher::AIResultsCacher(class AI *);
??0AIResultsCacher@AI@@QEAA@PEAV1@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+0*8]
??0AIResultsCacher@AI@@QEAA@PEAV1@@Z endp

; AI::AIResultsCacher::resetAllCaches();
?resetAllCaches@AIResultsCacher@AI@@QEAAXXZ proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+1*8]
?resetAllCaches@AIResultsCacher@AI@@QEAAXXZ endp

; AI::AIResultsCacher::cacheResult_reqs(const class TaskMatch &, bool);
?cacheResult_reqs@AIResultsCacher@AI@@QEAAXAEBVTaskMatch@@_N@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+2*8]
?cacheResult_reqs@AIResultsCacher@AI@@QEAAXAEBVTaskMatch@@_N@Z endp

; AI::AIResultsCacher::getCacheResult_reqs(const class TaskMatch &);
?getCacheResult_reqs@AIResultsCacher@AI@@QEAA_NAEBVTaskMatch@@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+3*8]
?getCacheResult_reqs@AIResultsCacher@AI@@QEAA_NAEBVTaskMatch@@@Z endp

; AI::AIResultsCacher::hasCacheResult_reqs(const class TaskMatch &);
?hasCacheResult_reqs@AIResultsCacher@AI@@QEBA_NAEBVTaskMatch@@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+4*8]
?hasCacheResult_reqs@AIResultsCacher@AI@@QEBA_NAEBVTaskMatch@@@Z endp

; AI::AIResultsCacher::cacheResult_results(const class TaskMatch &, bool);
?cacheResult_results@AIResultsCacher@AI@@QEAAXAEBVTaskMatch@@_N@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+5*8]
?cacheResult_results@AIResultsCacher@AI@@QEAAXAEBVTaskMatch@@_N@Z endp

; AI::AIResultsCacher::getCacheResult_results(const class TaskMatch &);
?getCacheResult_results@AIResultsCacher@AI@@QEAA_NAEBVTaskMatch@@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+6*8]
?getCacheResult_results@AIResultsCacher@AI@@QEAA_NAEBVTaskMatch@@@Z endp

; AI::AIResultsCacher::hasCacheResult_results(const class TaskMatch &);
?hasCacheResult_results@AIResultsCacher@AI@@QEBA_NAEBVTaskMatch@@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+7*8]
?hasCacheResult_results@AIResultsCacher@AI@@QEBA_NAEBVTaskMatch@@@Z endp

; AI::AIResultsCacher::runTargetFinder(function  *, const class TaskMatch &, class hand &);
?runTargetFinder@AIResultsCacher@AI@@QEAAMP82@EAAMAEBVhand@@AEAV3@_N@ZAEBVTaskMatch@@1@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+8*8]
?runTargetFinder@AIResultsCacher@AI@@QEAAMP82@EAAMAEBVhand@@AEAV3@_N@ZAEBVTaskMatch@@1@Z endp

; AI::AIResultsCacher::resetSpecificTargetFinderCache(const class TaskMatch &);
?resetSpecificTargetFinderCache@AIResultsCacher@AI@@QEAAXAEBVTaskMatch@@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+9*8]
?resetSpecificTargetFinderCache@AIResultsCacher@AI@@QEAAXAEBVTaskMatch@@@Z endp

; AI::AIResultsCacher::getResourceSource(class hand &, class GameData *, class StorageBuilding *);
?getResourceSource@AIResultsCacher@AI@@QEAAMAEAVhand@@PEAVGameData@@PEAVStorageBuilding@@@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+10*8]
?getResourceSource@AIResultsCacher@AI@@QEAAMAEAVhand@@PEAVGameData@@PEAVStorageBuilding@@@Z endp

; AI::AIResultsCacher::cacheResult_targetFinder(class TaskMatch, const class hand &, float);
?cacheResult_targetFinder@AIResultsCacher@AI@@QEAAXVTaskMatch@@AEBVhand@@M@Z proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+11*8]
?cacheResult_targetFinder@AIResultsCacher@AI@@QEAAXVTaskMatch@@AEBVhand@@M@Z endp

?_DESTRUCTOR@AIResultsCacher@AI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AIResultsCacher@AI@@QEAAXXZ endp

; AI::AIResultsCacher::~AIResultsCacher();
??1AIResultsCacher@AI@@QEAA@XZ proc EXPORT
jmp function_pointers[_AI_AIResultsCacher_base+12*8]
??1AIResultsCacher@AI@@QEAA@XZ endp
