
?_CONSTRUCTOR@AIPackage@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AIPackage@@QEAAPEAV1@XZ endp

; AIPackage::AIPackage();
??0AIPackage@@QEAA@XZ proc EXPORT
jmp function_pointers[_AIPackage_base+0*8]
??0AIPackage@@QEAA@XZ endp

?_DESTRUCTOR@AIPackage@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AIPackage@@QEAAXXZ endp

; AIPackage::~AIPackage();
??1AIPackage@@UEAA@XZ proc EXPORT
jmp function_pointers[_AIPackage_base+1*8]
??1AIPackage@@UEAA@XZ endp

?_NV_getMyTarget@AIPackage@@QEAA?AVTargetInfo@@PEAVCharacter@@@Z proc EXPORT
?_NV_getMyTarget@AIPackage@@QEAA?AVTargetInfo@@PEAVCharacter@@@Z endp

; AIPackage::getMyTarget(class Character *);
?getMyTarget@AIPackage@@UEAA?AVTargetInfo@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+2*8]
?getMyTarget@AIPackage@@UEAA?AVTargetInfo@@PEAVCharacter@@@Z endp

?_NV_notifyMyTargetPathfindImpossible@AIPackage@@QEAAXPEAVCharacter@@AEBVhand@@@Z proc EXPORT
?_NV_notifyMyTargetPathfindImpossible@AIPackage@@QEAAXPEAVCharacter@@AEBVhand@@@Z endp

; AIPackage::notifyMyTargetPathfindImpossible(class Character *, const class hand &);
?notifyMyTargetPathfindImpossible@AIPackage@@UEAAXPEAVCharacter@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+3*8]
?notifyMyTargetPathfindImpossible@AIPackage@@UEAAXPEAVCharacter@@AEBVhand@@@Z endp

?_NV_getDesiredTravelSpeed@AIPackage@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
?_NV_getDesiredTravelSpeed@AIPackage@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

; AIPackage::getDesiredTravelSpeed(class Character *);
?getDesiredTravelSpeed@AIPackage@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+4*8]
?getDesiredTravelSpeed@AIPackage@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

; AIPackage::getLeader();
?getLeader@AIPackage@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_AIPackage_base+5*8]
?getLeader@AIPackage@@QEAAPEAVCharacter@@XZ endp

?_NV_save@AIPackage@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_save@AIPackage@@QEAAXPEAVGameData@@@Z endp

; AIPackage::save(class GameData *);
?save@AIPackage@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+6*8]
?save@AIPackage@@UEAAXPEAVGameData@@@Z endp

?_NV_load@AIPackage@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_load@AIPackage@@QEAAXPEAVGameData@@@Z endp

; AIPackage::load(class GameData *);
?load@AIPackage@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+7*8]
?load@AIPackage@@UEAAXPEAVGameData@@@Z endp

?_NV_activateAndSetup@AIPackage@@QEAAXXZ proc EXPORT
?_NV_activateAndSetup@AIPackage@@QEAAXXZ endp

; AIPackage::activateAndSetup();
?activateAndSetup@AIPackage@@UEAAXXZ proc EXPORT
jmp function_pointers[_AIPackage_base+8*8]
?activateAndSetup@AIPackage@@UEAAXXZ endp

?_NV_endPackage@AIPackage@@QEAAXXZ proc EXPORT
?_NV_endPackage@AIPackage@@QEAAXXZ endp

; AIPackage::endPackage();
?endPackage@AIPackage@@UEAAXXZ proc EXPORT
jmp function_pointers[_AIPackage_base+9*8]
?endPackage@AIPackage@@UEAAXXZ endp

?_NV_notifyBetrayal@AIPackage@@QEAA_NPEAVCharacter@@0@Z proc EXPORT
?_NV_notifyBetrayal@AIPackage@@QEAA_NPEAVCharacter@@0@Z endp

; AIPackage::notifyBetrayal(class Character *, class Character *);
?notifyBetrayal@AIPackage@@UEAA_NPEAVCharacter@@0@Z proc EXPORT
jmp function_pointers[_AIPackage_base+10*8]
?notifyBetrayal@AIPackage@@UEAA_NPEAVCharacter@@0@Z endp

?_NV_periodicUpdate@AIPackage@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@AIPackage@@QEAAXXZ endp

; AIPackage::periodicUpdate();
?periodicUpdate@AIPackage@@UEAAXXZ proc EXPORT
jmp function_pointers[_AIPackage_base+11*8]
?periodicUpdate@AIPackage@@UEAAXXZ endp

?_NV_assessNeutral@AIPackage@@QEAAXPEAVCharacter@@@Z proc EXPORT
?_NV_assessNeutral@AIPackage@@QEAAXPEAVCharacter@@@Z endp

; AIPackage::assessNeutral(class Character *);
?assessNeutral@AIPackage@@UEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+12*8]
?assessNeutral@AIPackage@@UEAAXPEAVCharacter@@@Z endp

?_NV_assessEnemy@AIPackage@@QEAA_NPEAVCharacter@@@Z proc EXPORT
?_NV_assessEnemy@AIPackage@@QEAA_NPEAVCharacter@@@Z endp

; AIPackage::assessEnemy(class Character *);
?assessEnemy@AIPackage@@UEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+13*8]
?assessEnemy@AIPackage@@UEAA_NPEAVCharacter@@@Z endp

?_NV_signalStart@AIPackage@@QEAA_NXZ proc EXPORT
?_NV_signalStart@AIPackage@@QEAA_NXZ endp

; AIPackage::signalStart();
?signalStart@AIPackage@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AIPackage_base+14*8]
?signalStart@AIPackage@@UEAA_NXZ endp

?_NV_signalEnd@AIPackage@@QEAA_NXZ proc EXPORT
?_NV_signalEnd@AIPackage@@QEAA_NXZ endp

; AIPackage::signalEnd();
?signalEnd@AIPackage@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AIPackage_base+15*8]
?signalEnd@AIPackage@@UEAA_NXZ endp

; AIPackage::iAmActivePackage();
?iAmActivePackage@AIPackage@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AIPackage_base+16*8]
?iAmActivePackage@AIPackage@@QEBA_NXZ endp

?_NV_getGUIData@AIPackage@@QEAA_NPEAVDatapanelGUI@@@Z proc EXPORT
?_NV_getGUIData@AIPackage@@QEAA_NPEAVDatapanelGUI@@@Z endp

; AIPackage::getGUIData(class DatapanelGUI *);
?getGUIData@AIPackage@@UEAA_NPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_AIPackage_base+17*8]
?getGUIData@AIPackage@@UEAA_NPEAVDatapanelGUI@@@Z endp

?_NV_autoNotifyJobsPanel@AIPackage@@QEAA_NXZ proc EXPORT
?_NV_autoNotifyJobsPanel@AIPackage@@QEAA_NXZ endp

; AIPackage::autoNotifyJobsPanel();
?autoNotifyJobsPanel@AIPackage@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AIPackage_base+18*8]
?autoNotifyJobsPanel@AIPackage@@UEAA_NXZ endp

?_NV_wantsRenewButton@AIPackage@@QEAA_NXZ proc EXPORT
?_NV_wantsRenewButton@AIPackage@@QEAA_NXZ endp

; AIPackage::wantsRenewButton();
?wantsRenewButton@AIPackage@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AIPackage_base+19*8]
?wantsRenewButton@AIPackage@@UEAA_NXZ endp

?_NV_showManagementPanelCallback@AIPackage@@QEAAXXZ proc EXPORT
?_NV_showManagementPanelCallback@AIPackage@@QEAAXXZ endp

; AIPackage::showManagementPanelCallback();
?showManagementPanelCallback@AIPackage@@UEAAXXZ proc EXPORT
jmp function_pointers[_AIPackage_base+20*8]
?showManagementPanelCallback@AIPackage@@UEAAXXZ endp

?_NV_wasASuccess@AIPackage@@QEAA_NXZ proc EXPORT
?_NV_wasASuccess@AIPackage@@QEAA_NXZ endp

; AIPackage::wasASuccess();
?wasASuccess@AIPackage@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AIPackage_base+21*8]
?wasASuccess@AIPackage@@UEAA_NXZ endp
