
?_CONSTRUCTOR@ActionsListMgr@AITaskSytem@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ActionsListMgr@AITaskSytem@@QEAAPEAV12@XZ endp

; AITaskSytem::ActionsListMgr::ActionsListMgr();
??0ActionsListMgr@AITaskSytem@@QEAA@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_ActionsListMgr_base+0*8]
??0ActionsListMgr@AITaskSytem@@QEAA@XZ endp

?_DESTRUCTOR@ActionsListMgr@AITaskSytem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ActionsListMgr@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::ActionsListMgr::~ActionsListMgr();
??1ActionsListMgr@AITaskSytem@@UEAA@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_ActionsListMgr_base+1*8]
??1ActionsListMgr@AITaskSytem@@UEAA@XZ endp

; AITaskSytem::ActionsListMgr::copyFrom(class AITaskSytem::ActionsListMgr *);
?copyFrom@ActionsListMgr@AITaskSytem@@QEAAXPEAV12@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_ActionsListMgr_base+2*8]
?copyFrom@ActionsListMgr@AITaskSytem@@QEAAXPEAV12@@Z endp

; AITaskSytem::ActionsListMgr::addFrom(class AITaskSytem::ActionsListMgr *);
?addFrom@ActionsListMgr@AITaskSytem@@QEAAXPEAV12@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_ActionsListMgr_base+3*8]
?addFrom@ActionsListMgr@AITaskSytem@@QEAAXPEAV12@@Z endp

; AITaskSytem::ActionsListMgr::getTaskAfterCurrent();
?getTaskAfterCurrent@ActionsListMgr@AITaskSytem@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_ActionsListMgr_base+4*8]
?getTaskAfterCurrent@ActionsListMgr@AITaskSytem@@QEAAPEAVTasker@@XZ endp

; AITaskSytem::ActionsListMgr::get2TasksAfterCurrent();
?get2TasksAfterCurrent@ActionsListMgr@AITaskSytem@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_ActionsListMgr_base+5*8]
?get2TasksAfterCurrent@ActionsListMgr@AITaskSytem@@QEAAPEAVTasker@@XZ endp
