
; AITaskSytem::canIDoTheInfrequents();
?canIDoTheInfrequents@AITaskSytem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+0*8]
?canIDoTheInfrequents@AITaskSytem@@QEAA_NXZ endp

; AITaskSytem::infrequentsStampCheck();
?infrequentsStampCheck@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+1*8]
?infrequentsStampCheck@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::currentActionChecks();
?currentActionChecks@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+2*8]
?currentActionChecks@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::_logTheAI();
?_logTheAI@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+3*8]
?_logTheAI@AITaskSytem@@QEAAXXZ endp

?_CONSTRUCTOR@AITaskSytem@@QEAAPEAV1@PEAVAI@@PEAVCharBody@@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@AITaskSytem@@QEAAPEAV1@PEAVAI@@PEAVCharBody@@PEAVCharacter@@@Z endp

; AITaskSytem::AITaskSytem(class AI *, class CharBody *, class Character *);
??0AITaskSytem@@QEAA@PEAVAI@@PEAVCharBody@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+4*8]
??0AITaskSytem@@QEAA@PEAVAI@@PEAVCharBody@@PEAVCharacter@@@Z endp

?_DESTRUCTOR@AITaskSytem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::~AITaskSytem();
??1AITaskSytem@@UEAA@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+5*8]
??1AITaskSytem@@UEAA@XZ endp

?_NV_serialise@AITaskSytem@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_serialise@AITaskSytem@@QEAAXPEAVGameData@@@Z endp

; AITaskSytem::serialise(class GameData *);
?serialise@AITaskSytem@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+6*8]
?serialise@AITaskSytem@@UEAAXPEAVGameData@@@Z endp

?_NV_loadFromSerialise@AITaskSytem@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_loadFromSerialise@AITaskSytem@@QEAAXPEAVGameData@@@Z endp

; AITaskSytem::loadFromSerialise(class GameData *);
?loadFromSerialise@AITaskSytem@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+7*8]
?loadFromSerialise@AITaskSytem@@UEAAXPEAVGameData@@@Z endp

; AITaskSytem::getHandle();
?getHandle@AITaskSytem@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+8*8]
?getHandle@AITaskSytem@@QEBA?AVhand@@XZ endp

; AITaskSytem::notifyPathImpossible(const class hand &, const class Ogre::Vector3 &);
?notifyPathImpossible@AITaskSytem@@QEAAXAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+9*8]
?notifyPathImpossible@AITaskSytem@@QEAAXAEBVhand@@AEBVVector3@Ogre@@@Z endp

; AITaskSytem::isPathImpossible(const class hand &);
?isPathImpossible@AITaskSytem@@QEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+10*8]
?isPathImpossible@AITaskSytem@@QEAA_NAEBVhand@@@Z endp

; AITaskSytem::update(class Ogre::Vector3, float);
?update@AITaskSytem@@QEAAXVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+11*8]
?update@AITaskSytem@@QEAAXVVector3@Ogre@@M@Z endp

; AITaskSytem::update4Frame(class Ogre::Vector3, float);
?update4Frame@AITaskSytem@@QEAAXVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+12*8]
?update4Frame@AITaskSytem@@QEAAXVVector3@Ogre@@M@Z endp

; AITaskSytem::periodicUpdate(float);
?periodicUpdate@AITaskSytem@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+13*8]
?periodicUpdate@AITaskSytem@@QEAAXM@Z endp

; AITaskSytem::taskImpossible();
?taskImpossible@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+14*8]
?taskImpossible@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::_notifyBodyTaskComplete();
?_notifyBodyTaskComplete@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+15*8]
?_notifyBodyTaskComplete@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::_forcedSetCurrentAction(class Tasker *, float);
?_forcedSetCurrentAction@AITaskSytem@@QEAAXPEAVTasker@@M@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+16*8]
?_forcedSetCurrentAction@AITaskSytem@@QEAAXPEAVTasker@@M@Z endp

; AITaskSytem::setTaskExpiryTimer();
?setTaskExpiryTimer@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+17*8]
?setTaskExpiryTimer@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::isGoalExpired();
?isGoalExpired@AITaskSytem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+18*8]
?isGoalExpired@AITaskSytem@@QEAA_NXZ endp

; AITaskSytem::isTaskExpired();
?isTaskExpired@AITaskSytem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+19*8]
?isTaskExpired@AITaskSytem@@QEAA_NXZ endp

; AITaskSytem::getGOalExpiryTimeRemaining();
?getGOalExpiryTimeRemaining@AITaskSytem@@QEAAMXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+20*8]
?getGOalExpiryTimeRemaining@AITaskSytem@@QEAAMXZ endp

; AITaskSytem::tryAndRerunGOAP(class Tasker *);
?tryAndRerunGOAP@AITaskSytem@@QEAA_NPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+21*8]
?tryAndRerunGOAP@AITaskSytem@@QEAA_NPEAVTasker@@@Z endp

?_NV_setCurrentGoal@AITaskSytem@@QEAAXPEAVTasker@@MW4taskPriority@@@Z proc EXPORT
?_NV_setCurrentGoal@AITaskSytem@@QEAAXPEAVTasker@@MW4taskPriority@@@Z endp

; AITaskSytem::setCurrentGoal(class Tasker *, float, enum taskPriority);
?setCurrentGoal@AITaskSytem@@UEAAXPEAVTasker@@MW4taskPriority@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+22*8]
?setCurrentGoal@AITaskSytem@@UEAAXPEAVTasker@@MW4taskPriority@@@Z endp

; AITaskSytem::callForUpdate(bool);
?callForUpdate@AITaskSytem@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+23*8]
?callForUpdate@AITaskSytem@@QEAAX_N@Z endp

; AITaskSytem::getGUIData(class DatapanelGUI *);
?getGUIData@AITaskSytem@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+24*8]
?getGUIData@AITaskSytem@@QEAAXPEAVDatapanelGUI@@@Z endp

; AITaskSytem::getCurrentGoalString();
?getCurrentGoalString@AITaskSytem@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+25*8]
?getCurrentGoalString@AITaskSytem@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; AITaskSytem::intendsToAttackTarget(class Character *);
?intendsToAttackTarget@AITaskSytem@@QEBA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+26*8]
?intendsToAttackTarget@AITaskSytem@@QEBA_NPEAVCharacter@@@Z endp

; AITaskSytem::updateStateBroadcast(class StateBroadcastData *);
?updateStateBroadcast@AITaskSytem@@QEAAXPEAVStateBroadcastData@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+27*8]
?updateStateBroadcast@AITaskSytem@@QEAAXPEAVStateBroadcastData@@@Z endp

; AITaskSytem::clearAllTasks();
?clearAllTasks@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+28*8]
?clearAllTasks@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::debugTargetInfo(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class hand &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?debugTargetInfo@AITaskSytem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVhand@@0_N@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+29*8]
?debugTargetInfo@AITaskSytem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVhand@@0_N@Z endp

?_NV_setNeedGOAP@AITaskSytem@@QEAAXXZ proc EXPORT
?_NV_setNeedGOAP@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::setNeedGOAP();
?setNeedGOAP@AITaskSytem@@UEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+30*8]
?setNeedGOAP@AITaskSytem@@UEAAXXZ endp

; AITaskSytem::setDialogueDeliveryTag(enum EventTriggerEnum);
?setDialogueDeliveryTag@AITaskSytem@@QEAAXW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+31*8]
?setDialogueDeliveryTag@AITaskSytem@@QEAAXW4EventTriggerEnum@@@Z endp

; AITaskSytem::getCurrentDurationTimedTask();
?getCurrentDurationTimedTask@AITaskSytem@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+32*8]
?getCurrentDurationTimedTask@AITaskSytem@@QEAAPEAVTasker@@XZ endp

; AITaskSytem::_taskImpossible();
?_taskImpossible@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+33*8]
?_taskImpossible@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::isThePlayer();
?isThePlayer@AITaskSytem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+34*8]
?isThePlayer@AITaskSytem@@QEAA_NXZ endp

; AITaskSytem::checkOrders();
?checkOrders@AITaskSytem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+35*8]
?checkOrders@AITaskSytem@@QEAA_NXZ endp

; AITaskSytem::chooseGoal(bool);
?chooseGoal@AITaskSytem@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+36*8]
?chooseGoal@AITaskSytem@@QEAAX_N@Z endp

; AITaskSytem::_chooseGoal(enum taskPriority, enum SquadMemberType);
?_chooseGoal@AITaskSytem@@QEAA_NW4taskPriority@@W4SquadMemberType@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+37*8]
?_chooseGoal@AITaskSytem@@QEAA_NW4taskPriority@@W4SquadMemberType@@@Z endp

; AITaskSytem::chooseGoalFrom(class std::map<float,Tasker *,std::less<float>,Ogre::STLAllocator<std::pair<float const ,Tasker *>,Ogre::CategorisedAllocPolicy<0> > > &, class TaskMatch &, class lektor<Tasker *> &, bool);
?chooseGoalFrom@AITaskSytem@@QEAAXAEAV?$map@MPEAVTasker@@U?$less@M@std@@V?$STLAllocator@U?$pair@$$CBMPEAVTasker@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAVTaskMatch@@AEAV?$lektor@PEAVTasker@@@@_N@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+38*8]
?chooseGoalFrom@AITaskSytem@@QEAAXAEAV?$map@MPEAVTasker@@U?$less@M@std@@V?$STLAllocator@U?$pair@$$CBMPEAVTasker@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAVTaskMatch@@AEAV?$lektor@PEAVTasker@@@@_N@Z endp

; AITaskSytem::choosePermaJob(class std::map<float,Tasker *,std::less<float>,Ogre::STLAllocator<std::pair<float const ,Tasker *>,Ogre::CategorisedAllocPolicy<0> > > &, class TaskMatch &, bool, bool);
?choosePermaJob@AITaskSytem@@QEAAXAEAV?$map@MPEAVTasker@@U?$less@M@std@@V?$STLAllocator@U?$pair@$$CBMPEAVTasker@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAVTaskMatch@@_N2@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+39*8]
?choosePermaJob@AITaskSytem@@QEAAXAEAV?$map@MPEAVTasker@@U?$less@M@std@@V?$STLAllocator@U?$pair@$$CBMPEAVTasker@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAVTaskMatch@@_N2@Z endp

; AITaskSytem::setupParametersForCurrentGoal();
?setupParametersForCurrentGoal@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+40*8]
?setupParametersForCurrentGoal@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::runGoals(class std::map<float,Tasker *,std::less<float>,Ogre::STLAllocator<std::pair<float const ,Tasker *>,Ogre::CategorisedAllocPolicy<0> > > &, bool);
?runGoals@AITaskSytem@@QEAA_NAEAV?$map@MPEAVTasker@@U?$less@M@std@@V?$STLAllocator@U?$pair@$$CBMPEAVTasker@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@_N@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+41*8]
?runGoals@AITaskSytem@@QEAA_NAEAV?$map@MPEAVTasker@@U?$less@M@std@@V?$STLAllocator@U?$pair@$$CBMPEAVTasker@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@_N@Z endp

; AITaskSytem::clearRequestsList();
?clearRequestsList@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+42*8]
?clearRequestsList@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::bodyTaskComplete();
?bodyTaskComplete@AITaskSytem@@QEAAXXZ proc EXPORT
jmp function_pointers[_AITaskSytem_base+43*8]
?bodyTaskComplete@AITaskSytem@@QEAAXXZ endp

; AITaskSytem::popFromOrders(class Tasker *);
?popFromOrders@AITaskSytem@@QEAAXPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+44*8]
?popFromOrders@AITaskSytem@@QEAAXPEAVTasker@@@Z endp

; AITaskSytem::setCurrentTask(class AITaskSytem::ActionsListMgr *);
?setCurrentTask@AITaskSytem@@QEAA_NPEAVActionsListMgr@1@@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+45*8]
?setCurrentTask@AITaskSytem@@QEAA_NPEAVActionsListMgr@1@@Z endp

; AITaskSytem::runGOAP(class Tasker *, bool, bool);
?runGOAP@AITaskSytem@@QEAAMPEAVTasker@@_N1@Z proc EXPORT
jmp function_pointers[_AITaskSytem_base+46*8]
?runGOAP@AITaskSytem@@QEAAMPEAVTasker@@_N1@Z endp
