
?_CONSTRUCTOR@AnimationClass@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationClass@@QEAAPEAV1@XZ endp

; AnimationClass::AnimationClass();
??0AnimationClass@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+0*8]
??0AnimationClass@@QEAA@XZ endp

; AnimationClass::debugGetAllAnimations(class DatapanelGUI *);
?debugGetAllAnimations@AnimationClass@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+1*8]
?debugGetAllAnimations@AnimationClass@@QEAAXPEAVDatapanelGUI@@@Z endp

?_DESTRUCTOR@AnimationClass@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationClass@@QEAAXXZ endp

; AnimationClass::~AnimationClass();
??1AnimationClass@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+2*8]
??1AnimationClass@@UEAA@XZ endp

; AnimationClass::startStumble(class AnimationData *);
?startStumble@AnimationClass@@QEAAXPEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+3*8]
?startStumble@AnimationClass@@QEAAXPEAVAnimationData@@@Z endp

; AnimationClass::endStumble();
?endStumble@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+4*8]
?endStumble@AnimationClass@@QEAAXXZ endp

; AnimationClass::currentlyStumbling();
?currentlyStumbling@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+5*8]
?currentlyStumbling@AnimationClass@@QEBA_NXZ endp

; AnimationClass::getCurrentlyStumbleAnim();
?getCurrentlyStumbleAnim@AnimationClass@@QEBAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+6*8]
?getCurrentlyStumbleAnim@AnimationClass@@QEBAPEAVAnimationData@@XZ endp

; AnimationClass::isCurrentlyIncapableOfWaypointMovemode();
?isCurrentlyIncapableOfWaypointMovemode@AnimationClass@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+7*8]
?isCurrentlyIncapableOfWaypointMovemode@AnimationClass@@QEAA_NXZ endp

; AnimationClass::threadSafeRagdollUpdateUT();
?threadSafeRagdollUpdateUT@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+8*8]
?threadSafeRagdollUpdateUT@AnimationClass@@QEAAXXZ endp

?_NV_update@AnimationClass@@QEAAXM@Z proc EXPORT
?_NV_update@AnimationClass@@QEAAXM@Z endp

; AnimationClass::update(float);
?update@AnimationClass@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+9*8]
?update@AnimationClass@@UEAAXM@Z endp

; AnimationClass::updateAnimationCharacterEditor(float);
?updateAnimationCharacterEditor@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+10*8]
?updateAnimationCharacterEditor@AnimationClass@@QEAAXM@Z endp

; AnimationClass::updateThreaded(float);
?updateThreaded@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+11*8]
?updateThreaded@AnimationClass@@QEAAXM@Z endp

?_NV_rotationUpdate@AnimationClass@@QEAAXM@Z proc EXPORT
?_NV_rotationUpdate@AnimationClass@@QEAAXM@Z endp

; AnimationClass::rotationUpdate(float);
?rotationUpdate@AnimationClass@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+12*8]
?rotationUpdate@AnimationClass@@UEAAXM@Z endp

; AnimationClass::updateAnimationTransforms();
?updateAnimationTransforms@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+13*8]
?updateAnimationTransforms@AnimationClass@@QEAAXXZ endp

; AnimationClass::setPosition(const class Ogre::Vector3 &);
?setPosition@AnimationClass@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+14*8]
?setPosition@AnimationClass@@QEAAXAEBVVector3@Ogre@@@Z endp

; AnimationClass::setPosition(const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?setPosition@AnimationClass@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+15*8]
?setPosition@AnimationClass@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z endp

; AnimationClass::setPosition(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?setPosition@AnimationClass@@QEAAXAEBVVector3@Ogre@@0@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+16*8]
?setPosition@AnimationClass@@QEAAXAEBVVector3@Ogre@@0@Z endp

; AnimationClass::getPosition(class Ogre::Vector3 &);
?getPosition@AnimationClass@@QEBA_NAEAVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+17*8]
?getPosition@AnimationClass@@QEBA_NAEAVVector3@Ogre@@@Z endp

; AnimationClass::rotateEntityAroundBone(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Ogre::Vector3);
?rotateEntityAroundBone@AnimationClass@@QEAA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V23@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+18*8]
?rotateEntityAroundBone@AnimationClass@@QEAA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V23@@Z endp

; AnimationClass::getBoneScale(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneScale@AnimationClass@@QEBAAEBVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+19*8]
?getBoneScale@AnimationClass@@QEBAAEBVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::deactivateVisuals();
?deactivateVisuals@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+20*8]
?deactivateVisuals@AnimationClass@@QEAAXXZ endp

; AnimationClass::getIsActivated();
?getIsActivated@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+21*8]
?getIsActivated@AnimationClass@@QEBA_NXZ endp

; AnimationClass::setBodyEntity(class Ogre::Entity *);
?setBodyEntity@AnimationClass@@QEAAXPEAVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+22*8]
?setBodyEntity@AnimationClass@@QEAAXPEAVEntity@Ogre@@@Z endp

; AnimationClass::resetBody();
?resetBody@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+23*8]
?resetBody@AnimationClass@@QEAAXXZ endp

; AnimationClass::restartAction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?restartAction@AnimationClass@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+24*8]
?restartAction@AnimationClass@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::playAction(class AnimationData *, float, float, bool);
?playAction@AnimationClass@@QEAAXPEAVAnimationData@@MM_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+25*8]
?playAction@AnimationClass@@QEAAXPEAVAnimationData@@MM_N@Z endp

; AnimationClass::playAction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, bool);
?playAction@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+26*8]
?playAction@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM_N@Z endp

; AnimationClass::stopAction();
?stopAction@AnimationClass@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+27*8]
?stopAction@AnimationClass@@QEAA_NXZ endp

; AnimationClass::stopAction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?stopAction@AnimationClass@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+28*8]
?stopAction@AnimationClass@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::setAnimationMoveSpeed(float);
?setAnimationMoveSpeed@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+29*8]
?setAnimationMoveSpeed@AnimationClass@@QEAAXM@Z endp

; AnimationClass::setStrafeSpeed(float);
?setStrafeSpeed@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+30*8]
?setStrafeSpeed@AnimationClass@@QEAAXM@Z endp

; AnimationClass::setCombatMode(bool);
?setCombatMode@AnimationClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+31*8]
?setCombatMode@AnimationClass@@QEAAX_N@Z endp

; AnimationClass::setWeatherType(enum WeatherAffecting, float, bool);
?setWeatherType@AnimationClass@@QEAAXW4WeatherAffecting@@M_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+32*8]
?setWeatherType@AnimationClass@@QEAAXW4WeatherAffecting@@M_N@Z endp

; AnimationClass::getWeatherType();
?getWeatherType@AnimationClass@@QEBA?AW4WeatherAffecting@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+33*8]
?getWeatherType@AnimationClass@@QEBA?AW4WeatherAffecting@@XZ endp

; AnimationClass::getWeatherStrength();
?getWeatherStrength@AnimationClass@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+34*8]
?getWeatherStrength@AnimationClass@@QEBAMXZ endp

; AnimationClass::setStealthMode(bool);
?setStealthMode@AnimationClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+35*8]
?setStealthMode@AnimationClass@@QEAAX_N@Z endp

; AnimationClass::setMaximumSpeed(float);
?setMaximumSpeed@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+36*8]
?setMaximumSpeed@AnimationClass@@QEAAXM@Z endp

; AnimationClass::getMaximumSpeed();
?getMaximumSpeed@AnimationClass@@QEAAMXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+37*8]
?getMaximumSpeed@AnimationClass@@QEAAMXZ endp

; AnimationClass::isLinearAnimationDone_byName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isLinearAnimationDone_byName@AnimationClass@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+38*8]
?isLinearAnimationDone_byName@AnimationClass@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::isLinearAnimationDone(class AnimationData *);
?isLinearAnimationDone@AnimationClass@@QEAA_NPEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+39*8]
?isLinearAnimationDone@AnimationClass@@QEAA_NPEAVAnimationData@@@Z endp

; AnimationClass::getFootHeight();
?getFootHeight@AnimationClass@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+40*8]
?getFootHeight@AnimationClass@@QEBAMXZ endp

; AnimationClass::calculateFeetHeight();
?calculateFeetHeight@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+41*8]
?calculateFeetHeight@AnimationClass@@QEAAXXZ endp

; AnimationClass::setBootHeight(float);
?setBootHeight@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+42*8]
?setBootHeight@AnimationClass@@QEAAXM@Z endp

; AnimationClass::isBeingCarried();
?isBeingCarried@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+43*8]
?isBeingCarried@AnimationClass@@QEBA_NXZ endp

; AnimationClass::isTotallyRagdoll();
?isTotallyRagdoll@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+44*8]
?isTotallyRagdoll@AnimationClass@@QEBA_NXZ endp

; AnimationClass::notifyRagdollNeedsAnUpdate();
?notifyRagdollNeedsAnUpdate@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+45*8]
?notifyRagdollNeedsAnUpdate@AnimationClass@@QEAAXXZ endp

; AnimationClass::setCarryMode(bool, bool, bool);
?setCarryMode@AnimationClass@@QEAAX_N00@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+46*8]
?setCarryMode@AnimationClass@@QEAAX_N00@Z endp

; AnimationClass::setCombatModeLegsIdle(bool);
?setCombatModeLegsIdle@AnimationClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+47*8]
?setCombatModeLegsIdle@AnimationClass@@QEAAX_N@Z endp

; AnimationClass::setCombatModeUpperIdle(bool);
?setCombatModeUpperIdle@AnimationClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+48*8]
?setCombatModeUpperIdle@AnimationClass@@QEAAX_N@Z endp

?_NV_getRagdoll@AnimationClass@@QEBAPEAVRagdollClass@@XZ proc EXPORT
?_NV_getRagdoll@AnimationClass@@QEBAPEAVRagdollClass@@XZ endp

; AnimationClass::getRagdoll();
?getRagdoll@AnimationClass@@UEBAPEAVRagdollClass@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+49*8]
?getRagdoll@AnimationClass@@UEBAPEAVRagdollClass@@XZ endp

; AnimationClass::isRagdoll();
?isRagdoll@AnimationClass@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+50*8]
?isRagdoll@AnimationClass@@QEAA_NXZ endp

; AnimationClass::setupRagdoll(class Scythe::SkeletonData *);
?setupRagdoll@AnimationClass@@QEAA_NPEAVSkeletonData@Scythe@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+51*8]
?setupRagdoll@AnimationClass@@QEAA_NPEAVSkeletonData@Scythe@@@Z endp

; AnimationClass::ragdollAnimateTo(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?ragdollAnimateTo@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+52*8]
?ragdollAnimateTo@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp

; AnimationClass::isRagdollAnimated();
?isRagdollAnimated@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+53*8]
?isRagdollAnimated@AnimationClass@@QEBA_NXZ endp

?_NV_ragdollModeUT@AnimationClass@@QEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z proc EXPORT
?_NV_ragdollModeUT@AnimationClass@@QEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z endp

; AnimationClass::ragdollModeUT(bool, class Ogre::Vector3, enum RagdollPart::Enum, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Character *);
?ragdollModeUT@AnimationClass@@UEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+54*8]
?ragdollModeUT@AnimationClass@@UEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z endp

?_NV_postRagdollCreationCallbackMT@AnimationClass@@QEAAX_N@Z proc EXPORT
?_NV_postRagdollCreationCallbackMT@AnimationClass@@QEAAX_N@Z endp

; AnimationClass::postRagdollCreationCallbackMT(bool);
?postRagdollCreationCallbackMT@AnimationClass@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+55*8]
?postRagdollCreationCallbackMT@AnimationClass@@UEAAX_N@Z endp

; AnimationClass::hasRagdollPart(const enum RagdollPart::Enum &);
?hasRagdollPart@AnimationClass@@QEAA_NAEBW4Enum@RagdollPart@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+56*8]
?hasRagdollPart@AnimationClass@@QEAA_NAEBW4Enum@RagdollPart@@@Z endp

; AnimationClass::isPhysical();
?isPhysical@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+57*8]
?isPhysical@AnimationClass@@QEBA_NXZ endp

; AnimationClass::getHeight();
?getHeight@AnimationClass@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+58*8]
?getHeight@AnimationClass@@QEBAMXZ endp

; AnimationClass::randomiseAnimationPosition();
?randomiseAnimationPosition@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+59*8]
?randomiseAnimationPosition@AnimationClass@@QEAAXXZ endp

; AnimationClass::beingCarriedUpdate(const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?beingCarriedUpdate@AnimationClass@@QEAA?AVVector3@Ogre@@AEBV23@AEBVQuaternion@3@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+60*8]
?beingCarriedUpdate@AnimationClass@@QEAA?AVVector3@Ogre@@AEBV23@AEBVQuaternion@3@@Z endp

; AnimationClass::rangedCombatModeUpdate(const class Ogre::Vector3 &);
?rangedCombatModeUpdate@AnimationClass@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+61*8]
?rangedCombatModeUpdate@AnimationClass@@QEAAXAEBVVector3@Ogre@@@Z endp

; AnimationClass::runAnimation(class AnimationData *, float, enum AnimationLayerEnum, float);
?runAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MW4AnimationLayerEnum@@M@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+62*8]
?runAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MW4AnimationLayerEnum@@M@Z endp

; AnimationClass::runAnimation(class AnimationData *, float, enum AnimationLayerEnum, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?runAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MW4AnimationLayerEnum@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+63*8]
?runAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MW4AnimationLayerEnum@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::runAnimation(class AnimationData *, float, float);
?runAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+64*8]
?runAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MM@Z endp

; AnimationClass::runAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float);
?runAnimation@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+65*8]
?runAnimation@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM@Z endp

; AnimationClass::runAnimation_manualTiming(class AnimationData *, float, float);
?runAnimation_manualTiming@AnimationClass@@QEAAXPEAVAnimationData@@MM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+66*8]
?runAnimation_manualTiming@AnimationClass@@QEAAXPEAVAnimationData@@MM@Z endp

; AnimationClass::endCombatAnimation();
?endCombatAnimation@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+67*8]
?endCombatAnimation@AnimationClass@@QEAAXXZ endp

; AnimationClass::runCombatAnimation(class CombatTechniqueData *, float, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?runCombatAnimation@AnimationClass@@QEAAXPEAVCombatTechniqueData@@MV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+68*8]
?runCombatAnimation@AnimationClass@@QEAAXPEAVCombatTechniqueData@@MV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::startCombatAnimation(class CombatTechniqueData *, float, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?startCombatAnimation@AnimationClass@@QEAAXPEAVCombatTechniqueData@@MV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+69*8]
?startCombatAnimation@AnimationClass@@QEAAXPEAVCombatTechniqueData@@MV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::startAnimation(class AnimationData *, float, float);
?startAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+70*8]
?startAnimation@AnimationClass@@QEAAXPEAVAnimationData@@MM@Z endp

; AnimationClass::startAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float);
?startAnimation@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+71*8]
?startAnimation@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM@Z endp

; AnimationClass::stopAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?stopAnimation@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+72*8]
?stopAnimation@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::stopAnimation(class AnimationData *);
?stopAnimation@AnimationClass@@QEAAXPEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+73*8]
?stopAnimation@AnimationClass@@QEAAXPEAVAnimationData@@@Z endp

; AnimationClass::getEvents(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getEvents@AnimationClass@@QEAAPEAVAnimationEvents@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+74*8]
?getEvents@AnimationClass@@QEAAPEAVAnimationEvents@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::activateVisuals();
?activateVisuals@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+75*8]
?activateVisuals@AnimationClass@@QEAAXXZ endp

?_NV_getAnimationData@AnimationClass@@QEAAPEAVAnimationData@@PEAVGameData@@@Z proc EXPORT
?_NV_getAnimationData@AnimationClass@@QEAAPEAVAnimationData@@PEAVGameData@@@Z endp

; AnimationClass::getAnimationData(class GameData *);
?getAnimationData@AnimationClass@@UEAAPEAVAnimationData@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+76*8]
?getAnimationData@AnimationClass@@UEAAPEAVAnimationData@@PEAVGameData@@@Z endp

?_NV_getAnimationData@AnimationClass@@QEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_getAnimationData@AnimationClass@@QEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::getAnimationData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimationData@AnimationClass@@UEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+77*8]
?getAnimationData@AnimationClass@@UEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getAnimationDataByOgreName@AnimationClass@@QEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_getAnimationDataByOgreName@AnimationClass@@QEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::getAnimationDataByOgreName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimationDataByOgreName@AnimationClass@@UEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+78*8]
?getAnimationDataByOgreName@AnimationClass@@UEAAPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::getAnimationDatasList();
?getAnimationDatasList@AnimationClass@@QEAAPEAUAnimList@AnimsListsManager@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+79*8]
?getAnimationDatasList@AnimationClass@@QEAAPEAUAnimList@AnimsListsManager@@XZ endp

; AnimationClass::estimateAnimationTime(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?estimateAnimationTime@AnimationClass@@QEAAMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+80*8]
?estimateAnimationTime@AnimationClass@@QEAAMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::notifyRelocatedAnimLoop();
?notifyRelocatedAnimLoop@AnimationClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+81*8]
?notifyRelocatedAnimLoop@AnimationClass@@QEAAXXZ endp

; AnimationClass::serialiseAppearance(class GameData *);
?serialiseAppearance@AnimationClass@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+82*8]
?serialiseAppearance@AnimationClass@@QEAAXPEAVGameData@@@Z endp

; AnimationClass::setAppearanceData(class GameDataCopyStandalone *);
?setAppearanceData@AnimationClass@@QEAAXPEAVGameDataCopyStandalone@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+83*8]
?setAppearanceData@AnimationClass@@QEAAXPEAVGameDataCopyStandalone@@@Z endp

; AnimationClass::getAppearanceData();
?getAppearanceData@AnimationClass@@QEAAPEAVGameDataCopyStandalone@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+84*8]
?getAppearanceData@AnimationClass@@QEAAPEAVGameDataCopyStandalone@@XZ endp

?_NV_getAudioObject@AnimationClass@@QEBA_KXZ proc EXPORT
?_NV_getAudioObject@AnimationClass@@QEBA_KXZ endp

; AnimationClass::getAudioObject();
?getAudioObject@AnimationClass@@UEBA_KXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+85*8]
?getAudioObject@AnimationClass@@UEBA_KXZ endp

; AnimationClass::playSlaveAnim(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float);
?playSlaveAnim@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+86*8]
?playSlaveAnim@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMM@Z endp

; AnimationClass::runSlaveAnim(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float);
?runSlaveAnim@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+87*8]
?runSlaveAnim@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMM@Z endp

; AnimationClass::endSlaveAnim(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?endSlaveAnim@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+88*8]
?endSlaveAnim@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::isSlaveAnimating();
?isSlaveAnimating@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+89*8]
?isSlaveAnimating@AnimationClass@@QEBA_NXZ endp

; AnimationClass::setSlaveHandle(const class hand &);
?setSlaveHandle@AnimationClass@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+90*8]
?setSlaveHandle@AnimationClass@@QEAAXAEBVhand@@@Z endp

; AnimationClass::slaveAttachToBoneMode(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?slaveAttachToBoneMode@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+91*8]
?slaveAttachToBoneMode@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::isSlaveAttachToBoneMode();
?isSlaveAttachToBoneMode@AnimationClass@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+92*8]
?isSlaveAttachToBoneMode@AnimationClass@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getCharacter@AnimationClass@@QEAAPEAVCharacter@@XZ proc EXPORT
?_NV_getCharacter@AnimationClass@@QEAAPEAVCharacter@@XZ endp

; AnimationClass::getCharacter();
?getCharacter@AnimationClass@@UEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+93*8]
?getCharacter@AnimationClass@@UEAAPEAVCharacter@@XZ endp

?_NV_setLegDamage@AnimationClass@@QEAAXMM@Z proc EXPORT
?_NV_setLegDamage@AnimationClass@@QEAAXMM@Z endp

; AnimationClass::setLegDamage(float, float);
?setLegDamage@AnimationClass@@UEAAXMM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+94*8]
?setLegDamage@AnimationClass@@UEAAXMM@Z endp

?_NV_setDesiredPainOverlayAnims@AnimationClass@@QEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_setDesiredPainOverlayAnims@AnimationClass@@QEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; AnimationClass::setDesiredPainOverlayAnims(class std::set<StringValuePair,std::less<StringValuePair>,Ogre::STLAllocator<StringValuePair,Ogre::CategorisedAllocPolicy<0> > >);
?setDesiredPainOverlayAnims@AnimationClass@@UEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+95*8]
?setDesiredPainOverlayAnims@AnimationClass@@UEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_setDesiredPainOverlayAnimOverride@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setDesiredPainOverlayAnimOverride@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClass::setDesiredPainOverlayAnimOverride(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setDesiredPainOverlayAnimOverride@AnimationClass@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+96*8]
?setDesiredPainOverlayAnimOverride@AnimationClass@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_ragdollTheWeapons@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z proc EXPORT
?_NV_ragdollTheWeapons@AnimationClass@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z endp

; AnimationClass::ragdollTheWeapons(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *, bool);
?ragdollTheWeapons@AnimationClass@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+97*8]
?ragdollTheWeapons@AnimationClass@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z endp

?_NV_setStance@AnimationClass@@QEAAX_N0@Z proc EXPORT
?_NV_setStance@AnimationClass@@QEAAX_N0@Z endp

; AnimationClass::setStance(bool, bool);
?setStance@AnimationClass@@UEAAX_N0@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+98*8]
?setStance@AnimationClass@@UEAAX_N0@Z endp

?_NV_setStanceAnimation@AnimationClass@@QEAAXW4StanceEnum@@@Z proc EXPORT
?_NV_setStanceAnimation@AnimationClass@@QEAAXW4StanceEnum@@@Z endp

; AnimationClass::setStanceAnimation(enum StanceEnum);
?setStanceAnimation@AnimationClass@@UEAAXW4StanceEnum@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+99*8]
?setStanceAnimation@AnimationClass@@UEAAXW4StanceEnum@@@Z endp

?_NV_setEquipmentInHand@AnimationClass@@QEAAX_N0@Z proc EXPORT
?_NV_setEquipmentInHand@AnimationClass@@QEAAX_N0@Z endp

; AnimationClass::setEquipmentInHand(bool, bool);
?setEquipmentInHand@AnimationClass@@UEAAX_N0@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+100*8]
?setEquipmentInHand@AnimationClass@@UEAAX_N0@Z endp

?_NV_isTurning@AnimationClass@@QEBA_NXZ proc EXPORT
?_NV_isTurning@AnimationClass@@QEBA_NXZ endp

; AnimationClass::isTurning();
?isTurning@AnimationClass@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+101*8]
?isTurning@AnimationClass@@UEBA_NXZ endp

?_NV_isTurningFar@AnimationClass@@QEBA_NXZ proc EXPORT
?_NV_isTurningFar@AnimationClass@@QEBA_NXZ endp

; AnimationClass::isTurningFar();
?isTurningFar@AnimationClass@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+102*8]
?isTurningFar@AnimationClass@@UEBA_NXZ endp

?_NV_lookAt@AnimationClass@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_lookAt@AnimationClass@@QEAA_NAEBVVector3@Ogre@@@Z endp

; AnimationClass::lookAt(const class Ogre::Vector3 &);
?lookAt@AnimationClass@@UEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+103*8]
?lookAt@AnimationClass@@UEAA_NAEBVVector3@Ogre@@@Z endp

?_NV_getLookDirection@AnimationClass@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getLookDirection@AnimationClass@@QEBA?AVVector3@Ogre@@XZ endp

; AnimationClass::getLookDirection();
?getLookDirection@AnimationClass@@UEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+104*8]
?getLookDirection@AnimationClass@@UEBA?AVVector3@Ogre@@XZ endp

; AnimationClass::chooseStumbleAnim(class GameData *, enum CutOrigination, bool);
?chooseStumbleAnim@AnimationClass@@QEAAPEAVAnimationData@@PEAVGameData@@W4CutOrigination@@_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+105*8]
?chooseStumbleAnim@AnimationClass@@QEAAPEAVAnimationData@@PEAVGameData@@W4CutOrigination@@_N@Z endp

?_NV_getIdleAnimation@AnimationClass@@QEAAPEAVAnimationData@@XZ proc EXPORT
?_NV_getIdleAnimation@AnimationClass@@QEAAPEAVAnimationData@@XZ endp

; AnimationClass::getIdleAnimation();
?getIdleAnimation@AnimationClass@@UEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+106*8]
?getIdleAnimation@AnimationClass@@UEAAPEAVAnimationData@@XZ endp

?_NV_getFloatingAnim@AnimationClass@@QEAAPEAVAnimationData@@XZ proc EXPORT
?_NV_getFloatingAnim@AnimationClass@@QEAAPEAVAnimationData@@XZ endp

; AnimationClass::getFloatingAnim();
?getFloatingAnim@AnimationClass@@UEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+107*8]
?getFloatingAnim@AnimationClass@@UEAAPEAVAnimationData@@XZ endp

?_NV_getStandingUpAnim@AnimationClass@@QEAAPEAVAnimationData@@XZ proc EXPORT
?_NV_getStandingUpAnim@AnimationClass@@QEAAPEAVAnimationData@@XZ endp

; AnimationClass::getStandingUpAnim();
?getStandingUpAnim@AnimationClass@@UEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClass_base+108*8]
?getStandingUpAnim@AnimationClass@@UEAAPEAVAnimationData@@XZ endp

; AnimationClass::hasAction();
?hasAction@AnimationClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+109*8]
?hasAction@AnimationClass@@QEBA_NXZ endp

; AnimationClass::animationSelection(float);
?animationSelection@AnimationClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+110*8]
?animationSelection@AnimationClass@@QEAAXM@Z endp

?_NV_animationSelectionCombatMode@AnimationClass@@QEAAXM@Z proc EXPORT
?_NV_animationSelectionCombatMode@AnimationClass@@QEAAXM@Z endp

; AnimationClass::animationSelectionCombatMode(float);
?animationSelectionCombatMode@AnimationClass@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+111*8]
?animationSelectionCombatMode@AnimationClass@@UEAAXM@Z endp

?_NV_runStrafe@AnimationClass@@QEAAXPEAVAnimationData@@M@Z proc EXPORT
?_NV_runStrafe@AnimationClass@@QEAAXPEAVAnimationData@@M@Z endp

; AnimationClass::runStrafe(class AnimationData *, float);
?runStrafe@AnimationClass@@UEAAXPEAVAnimationData@@M@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+112*8]
?runStrafe@AnimationClass@@UEAAXPEAVAnimationData@@M@Z endp

?_NV_overlaidAnimationSelection@AnimationClass@@QEAAXXZ proc EXPORT
?_NV_overlaidAnimationSelection@AnimationClass@@QEAAXXZ endp

; AnimationClass::overlaidAnimationSelection();
?overlaidAnimationSelection@AnimationClass@@UEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+113*8]
?overlaidAnimationSelection@AnimationClass@@UEAAXXZ endp

?_NV_processTurnAnim@AnimationClass@@QEAA_NXZ proc EXPORT
?_NV_processTurnAnim@AnimationClass@@QEAA_NXZ endp

; AnimationClass::processTurnAnim();
?processTurnAnim@AnimationClass@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClass_base+114*8]
?processTurnAnim@AnimationClass@@UEAA_NXZ endp

; AnimationClass::chooseAnims(class AnimationChoices &, const class lektor<AnimationData *> *, const class AnimationRequirement &, bool, bool);
?chooseAnims@AnimationClass@@QEAAXAEAVAnimationChoices@@PEBV?$lektor@PEAVAnimationData@@@@AEBVAnimationRequirement@@_N3@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+115*8]
?chooseAnims@AnimationClass@@QEAAXAEAVAnimationChoices@@PEBV?$lektor@PEAVAnimationData@@@@AEBVAnimationRequirement@@_N3@Z endp

; AnimationClass::chooseRandomAnim(class lektor<AnimationData *> *, class AnimationRequirement &, bool);
?chooseRandomAnim@AnimationClass@@QEAA?AVAnimationChoices@@PEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+116*8]
?chooseRandomAnim@AnimationClass@@QEAA?AVAnimationChoices@@PEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@_N@Z endp

; AnimationClass::scoreAnim(class AnimationData *, class AnimationRequirement &, bool);
?scoreAnim@AnimationClass@@QEAAMPEAVAnimationData@@AEAVAnimationRequirement@@_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+117*8]
?scoreAnim@AnimationClass@@QEAAMPEAVAnimationData@@AEAVAnimationRequirement@@_N@Z endp

; AnimationClass::processMoveAnims(class lektor<AnimationData *> *, class AnimationRequirement &, bool, float);
?processMoveAnims@AnimationClass@@QEAAXPEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@_NM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+118*8]
?processMoveAnims@AnimationClass@@QEAAXPEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@_NM@Z endp

; symbol is too long
; ?processActionAnims@AnimationClass@@QEAA_NPEAV?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAnimationData@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@boost@@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAnimationData@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@AEAVAnimationRequirement@@@Z
; AnimationClass::processActionAnims()
AnimationClass_processActionAnims_PLACEHOLDER proc EXPORT
jmp function_pointers[_AnimationClass_base+119*8]
AnimationClass_processActionAnims_PLACEHOLDER endp

; AnimationClass::processIdleAnims(class lektor<AnimationData *> *, class AnimationRequirement &, float);
?processIdleAnims@AnimationClass@@QEAAXPEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@M@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+120*8]
?processIdleAnims@AnimationClass@@QEAAXPEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@M@Z endp

; AnimationClass::processCombatIdleAnims(class lektor<AnimationData *> *, class AnimationRequirement &, float, float);
?processCombatIdleAnims@AnimationClass@@QEAAXPEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@MM@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+121*8]
?processCombatIdleAnims@AnimationClass@@QEAAXPEAV?$lektor@PEAVAnimationData@@@@AEAVAnimationRequirement@@MM@Z endp

?_NV_breathing@AnimationClass@@QEAAX_N@Z proc EXPORT
?_NV_breathing@AnimationClass@@QEAAX_N@Z endp

; AnimationClass::breathing(bool);
?breathing@AnimationClass@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClass_base+122*8]
?breathing@AnimationClass@@UEAAX_N@Z endp
