
?_CONSTRUCTOR@AnimationGroundEvent@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@AnimationGroundEvent@@QEAAPEAV1@PEAVGameData@@@Z endp

; AnimationGroundEvent::AnimationGroundEvent(class GameData *);
??0AnimationGroundEvent@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AnimationGroundEvent_base+0*8]
??0AnimationGroundEvent@@QEAA@PEAVGameData@@@Z endp

?_NV_trigger@AnimationGroundEvent@@QEBAXPEAVCharacter@@@Z proc EXPORT
?_NV_trigger@AnimationGroundEvent@@QEBAXPEAVCharacter@@@Z endp

; AnimationGroundEvent::trigger(class Character *);
?trigger@AnimationGroundEvent@@UEBAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationGroundEvent_base+1*8]
?trigger@AnimationGroundEvent@@UEBAXPEAVCharacter@@@Z endp

?_NV_toString@AnimationGroundEvent@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_toString@AnimationGroundEvent@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; AnimationGroundEvent::toString();
?toString@AnimationGroundEvent@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AnimationGroundEvent_base+2*8]
?toString@AnimationGroundEvent@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_DESTRUCTOR@AnimationGroundEvent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationGroundEvent@@QEAAXXZ endp

; AnimationGroundEvent::~AnimationGroundEvent();
??1AnimationGroundEvent@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationGroundEvent_base+3*8]
??1AnimationGroundEvent@@UEAA@XZ endp
