
?_CONSTRUCTOR@SingleAnimation@AnimationClassBase@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAnimationData@@M_NM22M222MPEAV2@2M@Z proc EXPORT
?_CONSTRUCTOR@SingleAnimation@AnimationClassBase@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAnimationData@@M_NM22M222MPEAV2@2M@Z endp

; AnimationClassBase::SingleAnimation::SingleAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class AnimationData *, float, bool, float, bool, bool, float, bool, bool, bool, float, class AnimationClassBase *, bool, float);
??0SingleAnimation@AnimationClassBase@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAnimationData@@M_NM22M222MPEAV1@2M@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+0*8]
??0SingleAnimation@AnimationClassBase@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAnimationData@@M_NM22M222MPEAV1@2M@Z endp

?_DESTRUCTOR@SingleAnimation@AnimationClassBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SingleAnimation@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::SingleAnimation::~SingleAnimation();
??1SingleAnimation@AnimationClassBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+1*8]
??1SingleAnimation@AnimationClassBase@@QEAA@XZ endp

; AnimationClassBase::SingleAnimation::getAnimTime();
?getAnimTime@SingleAnimation@AnimationClassBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+2*8]
?getAnimTime@SingleAnimation@AnimationClassBase@@QEBAMXZ endp

; AnimationClassBase::SingleAnimation::hasSound();
?hasSound@SingleAnimation@AnimationClassBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+3*8]
?hasSound@SingleAnimation@AnimationClassBase@@QEBA_NXZ endp

; AnimationClassBase::SingleAnimation::_disable();
?_disable@SingleAnimation@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+4*8]
?_disable@SingleAnimation@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::SingleAnimation::disable();
?disable@SingleAnimation@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+5*8]
?disable@SingleAnimation@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::SingleAnimation::notStartedYet();
?notStartedYet@SingleAnimation@AnimationClassBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+6*8]
?notStartedYet@SingleAnimation@AnimationClassBase@@QEBA_NXZ endp

; AnimationClassBase::SingleAnimation::isACombatAnimation();
?isACombatAnimation@SingleAnimation@AnimationClassBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+7*8]
?isACombatAnimation@SingleAnimation@AnimationClassBase@@QEBA_NXZ endp

; AnimationClassBase::SingleAnimation::isABlockAnimation();
?isABlockAnimation@SingleAnimation@AnimationClassBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+8*8]
?isABlockAnimation@SingleAnimation@AnimationClassBase@@QEBA_NXZ endp

; AnimationClassBase::SingleAnimation::_debugCallback(class DataPanelLine *);
?_debugCallback@SingleAnimation@AnimationClassBase@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+9*8]
?_debugCallback@SingleAnimation@AnimationClassBase@@QEAAXPEAVDataPanelLine@@@Z endp

; AnimationClassBase::SingleAnimation::initialiseMainState();
?initialiseMainState@SingleAnimation@AnimationClassBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+10*8]
?initialiseMainState@SingleAnimation@AnimationClassBase@@QEAA_NXZ endp

; AnimationClassBase::SingleAnimation::fade(float, float);
?fade@SingleAnimation@AnimationClassBase@@QEAA_NMM@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+11*8]
?fade@SingleAnimation@AnimationClassBase@@QEAA_NMM@Z endp

; AnimationClassBase::SingleAnimation::update(float, float, bool);
?update@SingleAnimation@AnimationClassBase@@QEAAXMM_N@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_SingleAnimation_base+12*8]
?update@SingleAnimation@AnimationClassBase@@QEAAXMM_N@Z endp
