
?_CONSTRUCTOR@AnimationClassHuman@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationClassHuman@@QEAAPEAV1@XZ endp

; AnimationClassHuman::AnimationClassHuman();
??0AnimationClassHuman@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+0*8]
??0AnimationClassHuman@@QEAA@XZ endp

?_DESTRUCTOR@AnimationClassHuman@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationClassHuman@@QEAAXXZ endp

; AnimationClassHuman::~AnimationClassHuman();
??1AnimationClassHuman@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+1*8]
??1AnimationClassHuman@@UEAA@XZ endp

?_NV_isHuman@AnimationClassHuman@@QEAAPEAV1@XZ proc EXPORT
?_NV_isHuman@AnimationClassHuman@@QEAAPEAV1@XZ endp

; AnimationClassHuman::isHuman();
?isHuman@AnimationClassHuman@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+2*8]
?isHuman@AnimationClassHuman@@UEAAPEAV1@XZ endp

?_NV_ragdollModeUT@AnimationClassHuman@@QEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z proc EXPORT
?_NV_ragdollModeUT@AnimationClassHuman@@QEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z endp

; AnimationClassHuman::ragdollModeUT(bool, class Ogre::Vector3, enum RagdollPart::Enum, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Character *);
?ragdollModeUT@AnimationClassHuman@@UEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+3*8]
?ragdollModeUT@AnimationClassHuman@@UEAAX_NVVector3@Ogre@@W4Enum@RagdollPart@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@@Z endp

?_NV_calculatePositionWithWaterHeight@AnimationClassHuman@@QEAAMXZ proc EXPORT
?_NV_calculatePositionWithWaterHeight@AnimationClassHuman@@QEAAMXZ endp

; AnimationClassHuman::calculatePositionWithWaterHeight();
?calculatePositionWithWaterHeight@AnimationClassHuman@@UEAAMXZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+4*8]
?calculatePositionWithWaterHeight@AnimationClassHuman@@UEAAMXZ endp

?_NV_update@AnimationClassHuman@@QEAAXM@Z proc EXPORT
?_NV_update@AnimationClassHuman@@QEAAXM@Z endp

; AnimationClassHuman::update(float);
?update@AnimationClassHuman@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+5*8]
?update@AnimationClassHuman@@UEAAXM@Z endp

?_NV_create@AnimationClassHuman@@QEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z proc EXPORT
?_NV_create@AnimationClassHuman@@QEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z endp

; AnimationClassHuman::create(class CharMovement *, class GameDataCopyStandalone *, class GameData *, class Character *, class GameData *);
?create@AnimationClassHuman@@UEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+6*8]
?create@AnimationClassHuman@@UEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z endp

?_NV_setStance@AnimationClassHuman@@QEAAX_N0@Z proc EXPORT
?_NV_setStance@AnimationClassHuman@@QEAAX_N0@Z endp

; AnimationClassHuman::setStance(bool, bool);
?setStance@AnimationClassHuman@@UEAAX_N0@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+7*8]
?setStance@AnimationClassHuman@@UEAAX_N0@Z endp

?_NV_setStanceAnimation@AnimationClassHuman@@QEAAXW4StanceEnum@@@Z proc EXPORT
?_NV_setStanceAnimation@AnimationClassHuman@@QEAAXW4StanceEnum@@@Z endp

; AnimationClassHuman::setStanceAnimation(enum StanceEnum);
?setStanceAnimation@AnimationClassHuman@@UEAAXW4StanceEnum@@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+8*8]
?setStanceAnimation@AnimationClassHuman@@UEAAXW4StanceEnum@@@Z endp

; AnimationClassHuman::setEquipmentInHand(bool, bool, class Weapon *);
?setEquipmentInHand@AnimationClassHuman@@QEAAX_N0PEAVWeapon@@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+9*8]
?setEquipmentInHand@AnimationClassHuman@@QEAAX_N0PEAVWeapon@@@Z endp

?_NV_setDesiredPainOverlayAnims@AnimationClassHuman@@QEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_setDesiredPainOverlayAnims@AnimationClassHuman@@QEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; AnimationClassHuman::setDesiredPainOverlayAnims(class std::set<StringValuePair,std::less<StringValuePair>,Ogre::STLAllocator<StringValuePair,Ogre::CategorisedAllocPolicy<0> > >);
?setDesiredPainOverlayAnims@AnimationClassHuman@@UEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+10*8]
?setDesiredPainOverlayAnims@AnimationClassHuman@@UEAAXV?$set@VStringValuePair@@U?$less@VStringValuePair@@@std@@V?$STLAllocator@VStringValuePair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_setDesiredPainOverlayAnimOverride@AnimationClassHuman@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setDesiredPainOverlayAnimOverride@AnimationClassHuman@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassHuman::setDesiredPainOverlayAnimOverride(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setDesiredPainOverlayAnimOverride@AnimationClassHuman@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+11*8]
?setDesiredPainOverlayAnimOverride@AnimationClassHuman@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_animationSelectionCombatMode@AnimationClassHuman@@QEAAXM@Z proc EXPORT
?_NV_animationSelectionCombatMode@AnimationClassHuman@@QEAAXM@Z endp

; AnimationClassHuman::animationSelectionCombatMode(float);
?animationSelectionCombatMode@AnimationClassHuman@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+12*8]
?animationSelectionCombatMode@AnimationClassHuman@@UEAAXM@Z endp

?_NV_ragdollTheWeapons@AnimationClassHuman@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z proc EXPORT
?_NV_ragdollTheWeapons@AnimationClassHuman@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z endp

; AnimationClassHuman::ragdollTheWeapons(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *, bool);
?ragdollTheWeapons@AnimationClassHuman@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+13*8]
?ragdollTheWeapons@AnimationClassHuman@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@_N@Z endp

?_NV_lookAt@AnimationClassHuman@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_lookAt@AnimationClassHuman@@QEAA_NAEBVVector3@Ogre@@@Z endp

; AnimationClassHuman::lookAt(const class Ogre::Vector3 &);
?lookAt@AnimationClassHuman@@UEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+14*8]
?lookAt@AnimationClassHuman@@UEAA_NAEBVVector3@Ogre@@@Z endp

?_NV_getLookDirection@AnimationClassHuman@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getLookDirection@AnimationClassHuman@@QEBA?AVVector3@Ogre@@XZ endp

; AnimationClassHuman::getLookDirection();
?getLookDirection@AnimationClassHuman@@UEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+15*8]
?getLookDirection@AnimationClassHuman@@UEBA?AVVector3@Ogre@@XZ endp

?_NV_getFloatingAnim@AnimationClassHuman@@QEAAPEAVAnimationData@@XZ proc EXPORT
?_NV_getFloatingAnim@AnimationClassHuman@@QEAAPEAVAnimationData@@XZ endp

; AnimationClassHuman::getFloatingAnim();
?getFloatingAnim@AnimationClassHuman@@UEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+16*8]
?getFloatingAnim@AnimationClassHuman@@UEAAPEAVAnimationData@@XZ endp

?_NV_getStandingUpAnim@AnimationClassHuman@@QEAAPEAVAnimationData@@XZ proc EXPORT
?_NV_getStandingUpAnim@AnimationClassHuman@@QEAAPEAVAnimationData@@XZ endp

; AnimationClassHuman::getStandingUpAnim();
?getStandingUpAnim@AnimationClassHuman@@UEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+17*8]
?getStandingUpAnim@AnimationClassHuman@@UEAAPEAVAnimationData@@XZ endp

?_NV_overlaidAnimationSelection@AnimationClassHuman@@QEAAXXZ proc EXPORT
?_NV_overlaidAnimationSelection@AnimationClassHuman@@QEAAXXZ endp

; AnimationClassHuman::overlaidAnimationSelection();
?overlaidAnimationSelection@AnimationClassHuman@@UEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+18*8]
?overlaidAnimationSelection@AnimationClassHuman@@UEAAXXZ endp

; AnimationClassHuman::canUseArmAnim(class AnimationData *);
?canUseArmAnim@AnimationClassHuman@@QEAAPEAVAnimationData@@PEAV2@@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+19*8]
?canUseArmAnim@AnimationClassHuman@@QEAAPEAVAnimationData@@PEAV2@@Z endp

; AnimationClassHuman::calculatehipspos();
?calculatehipspos@AnimationClassHuman@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+20*8]
?calculatehipspos@AnimationClassHuman@@QEAAXXZ endp

?_NV_breathing@AnimationClassHuman@@QEAAX_N@Z proc EXPORT
?_NV_breathing@AnimationClassHuman@@QEAAX_N@Z endp

; AnimationClassHuman::breathing(bool);
?breathing@AnimationClassHuman@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClassHuman_base+21*8]
?breathing@AnimationClassHuman@@UEAAX_N@Z endp
