
?_CONSTRUCTOR@AnimationClassAnimal@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationClassAnimal@@QEAAPEAV1@XZ endp

; AnimationClassAnimal::AnimationClassAnimal();
??0AnimationClassAnimal@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+0*8]
??0AnimationClassAnimal@@QEAA@XZ endp

?_DESTRUCTOR@AnimationClassAnimal@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationClassAnimal@@QEAAXXZ endp

; AnimationClassAnimal::~AnimationClassAnimal();
??1AnimationClassAnimal@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+1*8]
??1AnimationClassAnimal@@UEAA@XZ endp

?_NV_create@AnimationClassAnimal@@QEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z proc EXPORT
?_NV_create@AnimationClassAnimal@@QEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z endp

; AnimationClassAnimal::create(class CharMovement *, class GameDataCopyStandalone *, class GameData *, class Character *, class GameData *);
?create@AnimationClassAnimal@@UEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+2*8]
?create@AnimationClassAnimal@@UEAA_NPEAVCharMovement@@PEAVGameDataCopyStandalone@@PEAVGameData@@PEAVCharacter@@2@Z endp

?_NV_getIdleAnimation@AnimationClassAnimal@@QEAAPEAVAnimationData@@XZ proc EXPORT
?_NV_getIdleAnimation@AnimationClassAnimal@@QEAAPEAVAnimationData@@XZ endp

; AnimationClassAnimal::getIdleAnimation();
?getIdleAnimation@AnimationClassAnimal@@UEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+3*8]
?getIdleAnimation@AnimationClassAnimal@@UEAAPEAVAnimationData@@XZ endp

?_NV_rotationUpdate@AnimationClassAnimal@@QEAAXM@Z proc EXPORT
?_NV_rotationUpdate@AnimationClassAnimal@@QEAAXM@Z endp

; AnimationClassAnimal::rotationUpdate(float);
?rotationUpdate@AnimationClassAnimal@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+4*8]
?rotationUpdate@AnimationClassAnimal@@UEAAXM@Z endp

?_NV_isTurning@AnimationClassAnimal@@QEBA_NXZ proc EXPORT
?_NV_isTurning@AnimationClassAnimal@@QEBA_NXZ endp

; AnimationClassAnimal::isTurning();
?isTurning@AnimationClassAnimal@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+5*8]
?isTurning@AnimationClassAnimal@@UEBA_NXZ endp

?_NV_isTurningFar@AnimationClassAnimal@@QEBA_NXZ proc EXPORT
?_NV_isTurningFar@AnimationClassAnimal@@QEBA_NXZ endp

; AnimationClassAnimal::isTurningFar();
?isTurningFar@AnimationClassAnimal@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+6*8]
?isTurningFar@AnimationClassAnimal@@UEBA_NXZ endp

?_NV_isHuman@AnimationClassAnimal@@QEAAPEAVAnimationClassHuman@@XZ proc EXPORT
?_NV_isHuman@AnimationClassAnimal@@QEAAPEAVAnimationClassHuman@@XZ endp

; AnimationClassAnimal::isHuman();
?isHuman@AnimationClassAnimal@@UEAAPEAVAnimationClassHuman@@XZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+7*8]
?isHuman@AnimationClassAnimal@@UEAAPEAVAnimationClassHuman@@XZ endp

?_NV_calculatePositionWithWaterHeight@AnimationClassAnimal@@QEAAMXZ proc EXPORT
?_NV_calculatePositionWithWaterHeight@AnimationClassAnimal@@QEAAMXZ endp

; AnimationClassAnimal::calculatePositionWithWaterHeight();
?calculatePositionWithWaterHeight@AnimationClassAnimal@@UEAAMXZ proc EXPORT
jmp function_pointers[_AnimationClassAnimal_base+8*8]
?calculatePositionWithWaterHeight@AnimationClassAnimal@@UEAAMXZ endp
