
?_CONSTRUCTOR@AnimationClassBase@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationClassBase@@QEAAPEAV1@XZ endp

; AnimationClassBase::AnimationClassBase();
??0AnimationClassBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+0*8]
??0AnimationClassBase@@QEAA@XZ endp

?_DESTRUCTOR@AnimationClassBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::~AnimationClassBase();
??1AnimationClassBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+1*8]
??1AnimationClassBase@@UEAA@XZ endp

; AnimationClassBase::create(class CharMovement *);
?create@AnimationClassBase@@QEAAXPEAVCharMovement@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+2*8]
?create@AnimationClassBase@@QEAAXPEAVCharMovement@@@Z endp

; AnimationClassBase::setVisible(bool);
?setVisible@AnimationClassBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+3*8]
?setVisible@AnimationClassBase@@QEAAX_N@Z endp

; AnimationClassBase::getVisible();
?getVisible@AnimationClassBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+4*8]
?getVisible@AnimationClassBase@@QEBA_NXZ endp

; AnimationClassBase::stopAllAnimation(bool);
?stopAllAnimation@AnimationClassBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+5*8]
?stopAllAnimation@AnimationClassBase@@QEAAX_N@Z endp

; AnimationClassBase::clearAllAnimationUT();
?clearAllAnimationUT@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+6*8]
?clearAllAnimationUT@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::getBoneWorldOrientation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneWorldOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+7*8]
?getBoneWorldOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getBoneWorldPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?getBoneWorldPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+8*8]
?getBoneWorldPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp

; AnimationClassBase::getHasBone(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getHasBone@AnimationClassBase@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+9*8]
?getHasBone@AnimationClassBase@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::_getBone(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_getBone@AnimationClassBase@@QEAAPEAVOldBone@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+10*8]
?_getBone@AnimationClassBase@@QEAAPEAVOldBone@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::hasAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?hasAnimation@AnimationClassBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+11*8]
?hasAnimation@AnimationClassBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getSceneNodePosition();
?getSceneNodePosition@AnimationClassBase@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+12*8]
?getSceneNodePosition@AnimationClassBase@@QEBA?BVVector3@Ogre@@XZ endp

; AnimationClassBase::getSceneNodeOrientation();
?getSceneNodeOrientation@AnimationClassBase@@QEBA?BVQuaternion@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+13*8]
?getSceneNodeOrientation@AnimationClassBase@@QEBA?BVQuaternion@Ogre@@XZ endp

; AnimationClassBase::getBoneLocalOrientation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneLocalOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+14*8]
?getBoneLocalOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getBoneLocalPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneLocalPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+15*8]
?getBoneLocalPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getRootBoneWorldPosition();
?getRootBoneWorldPosition@AnimationClassBase@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+16*8]
?getRootBoneWorldPosition@AnimationClassBase@@QEBAAEBVVector3@Ogre@@XZ endp

; AnimationClassBase::getRootBoneLocalPosition();
?getRootBoneLocalPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+17*8]
?getRootBoneLocalPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@XZ endp

; AnimationClassBase::getBoneInitialLocalPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneInitialLocalPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+18*8]
?getBoneInitialLocalPosition@AnimationClassBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getBoneInitialLocalOrientation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneInitialLocalOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+19*8]
?getBoneInitialLocalOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getBoneInitialWorldPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneInitialWorldPosition@AnimationClassBase@@QEBAAEBVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+20*8]
?getBoneInitialWorldPosition@AnimationClassBase@@QEBAAEBVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getBoneInitialWorldOrientation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneInitialWorldOrientation@AnimationClassBase@@QEBAAEBVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+21*8]
?getBoneInitialWorldOrientation@AnimationClassBase@@QEBAAEBVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::resetOrientation();
?resetOrientation@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+22*8]
?resetOrientation@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::getAnimationProgress(class CombatTechniqueData *);
?getAnimationProgress@AnimationClassBase@@QEAAMPEAVCombatTechniqueData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+23*8]
?getAnimationProgress@AnimationClassBase@@QEAAMPEAVCombatTechniqueData@@@Z endp

; AnimationClassBase::getAnimationProgress(class AnimationData *);
?getAnimationProgress@AnimationClassBase@@QEAAMPEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+24*8]
?getAnimationProgress@AnimationClassBase@@QEAAMPEAVAnimationData@@@Z endp

; AnimationClassBase::getAnimationProgress(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimationProgress@AnimationClassBase@@QEAAMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+25*8]
?getAnimationProgress@AnimationClassBase@@QEAAMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getOrientation();
?getOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+26*8]
?getOrientation@AnimationClassBase@@QEBA?AVQuaternion@Ogre@@XZ endp

; AnimationClassBase::setVerticalPosition(float);
?setVerticalPosition@AnimationClassBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+27*8]
?setVerticalPosition@AnimationClassBase@@QEAAXM@Z endp

?_NV_getCharacter@AnimationClassBase@@QEAAPEAVCharacter@@XZ proc EXPORT
?_NV_getCharacter@AnimationClassBase@@QEAAPEAVCharacter@@XZ endp

; AnimationClassBase::getCharacter();
?getCharacter@AnimationClassBase@@UEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+28*8]
?getCharacter@AnimationClassBase@@UEAAPEAVCharacter@@XZ endp

; AnimationClassBase::setMasterTimeSpeed(float);
?setMasterTimeSpeed@AnimationClassBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+29*8]
?setMasterTimeSpeed@AnimationClassBase@@QEAAXM@Z endp

; AnimationClassBase::getMasterTimeSpeed();
?getMasterTimeSpeed@AnimationClassBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+30*8]
?getMasterTimeSpeed@AnimationClassBase@@QEBAMXZ endp

; AnimationClassBase::getMasterTime();
?getMasterTime@AnimationClassBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+31*8]
?getMasterTime@AnimationClassBase@@QEBAMXZ endp

; AnimationClassBase::isVisibleEntity();
?isVisibleEntity@AnimationClassBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+32*8]
?isVisibleEntity@AnimationClassBase@@QEBA_NXZ endp

; AnimationClassBase::initBoneInitialWorldPositions();
?initBoneInitialWorldPositions@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+33*8]
?initBoneInitialWorldPositions@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::getAnimationPlaying_animName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimationPlaying_animName@AnimationClassBase@@QEAAPEAVSingleAnimation@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+34*8]
?getAnimationPlaying_animName@AnimationClassBase@@QEAAPEAVSingleAnimation@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getAnimationPlaying_datName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimationPlaying_datName@AnimationClassBase@@QEAAPEAVSingleAnimation@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+35*8]
?getAnimationPlaying_datName@AnimationClassBase@@QEAAPEAVSingleAnimation@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getAnimationPlaying(class CombatTechniqueData *);
?getAnimationPlaying@AnimationClassBase@@QEAAPEAVSingleAnimation@1@PEAVCombatTechniqueData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+36*8]
?getAnimationPlaying@AnimationClassBase@@QEAAPEAVSingleAnimation@1@PEAVCombatTechniqueData@@@Z endp

; AnimationClassBase::getAnimationPlaying(class AnimationData *);
?getAnimationPlaying@AnimationClassBase@@QEAAPEAVSingleAnimation@1@PEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+37*8]
?getAnimationPlaying@AnimationClassBase@@QEAAPEAVSingleAnimation@1@PEAVAnimationData@@@Z endp

; AnimationClassBase::isAnimationPlaying(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isAnimationPlaying@AnimationClassBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+38*8]
?isAnimationPlaying@AnimationClassBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getAnimationCurrentWeight(class AnimationData *);
?getAnimationCurrentWeight@AnimationClassBase@@QEAAMPEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+39*8]
?getAnimationCurrentWeight@AnimationClassBase@@QEAAMPEAVAnimationData@@@Z endp

; AnimationClassBase::getTotalActionAnimationWeight();
?getTotalActionAnimationWeight@AnimationClassBase@@QEAAMXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+40*8]
?getTotalActionAnimationWeight@AnimationClassBase@@QEAAMXZ endp

; AnimationClassBase::stillPlayingAnActionOrSomething();
?stillPlayingAnActionOrSomething@AnimationClassBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_base+41*8]
?stillPlayingAnActionOrSomething@AnimationClassBase@@QEAA_NXZ endp

; AnimationClassBase::getAnimationState(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimationState@AnimationClassBase@@QEAAPEAVAnimationState@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+42*8]
?getAnimationState@AnimationClassBase@@QEAAPEAVAnimationState@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAnimation@AnimationClassBase@@QEAAPEAVAnimation@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+43*8]
?getAnimation@AnimationClassBase@@QEAAPEAVAnimation@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::getAnimation_Medic(const class hand &);
?getAnimation_Medic@AnimationClassBase@@QEAAPEAVAnimationData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+44*8]
?getAnimation_Medic@AnimationClassBase@@QEAAPEAVAnimationData@@AEBVhand@@@Z endp

; AnimationClassBase::getAnimation_Lockpick(const class hand &);
?getAnimation_Lockpick@AnimationClassBase@@QEAAPEAVAnimationData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_base+45*8]
?getAnimation_Lockpick@AnimationClassBase@@QEAAPEAVAnimationData@@AEBVhand@@@Z endp
