
; AnimsListsManager::getSingleton();
?getSingleton@AnimsListsManager@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_AnimsListsManager_base+0*8]
?getSingleton@AnimsListsManager@@SAPEAV1@XZ endp

; AnimsListsManager::getAnimalList(class GameData *, class GameData *);
?getAnimalList@AnimsListsManager@@QEAAPEAUAnimList@1@PEAVGameData@@0@Z proc EXPORT
jmp function_pointers[_AnimsListsManager_base+1*8]
?getAnimalList@AnimsListsManager@@QEAAPEAUAnimList@1@PEAVGameData@@0@Z endp

; AnimsListsManager::getCharacterList();
?getCharacterList@AnimsListsManager@@QEAAPEAUAnimList@1@XZ proc EXPORT
jmp function_pointers[_AnimsListsManager_base+2*8]
?getCharacterList@AnimsListsManager@@QEAAPEAUAnimList@1@XZ endp

; AnimsListsManager::setupCharacterList();
?setupCharacterList@AnimsListsManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimsListsManager_base+3*8]
?setupCharacterList@AnimsListsManager@@QEAAXXZ endp

; AnimsListsManager::setupAnimalList(class GameData *, class GameData *);
?setupAnimalList@AnimsListsManager@@QEAAXPEAVGameData@@0@Z proc EXPORT
jmp function_pointers[_AnimsListsManager_base+4*8]
?setupAnimalList@AnimsListsManager@@QEAAXPEAVGameData@@0@Z endp

; AnimsListsManager::setupList(class lektor<GameData *> &, struct AnimsListsManager::AnimList &, class lektor<GameData *> &);
?setupList@AnimsListsManager@@QEAAXAEAV?$lektor@PEAVGameData@@@@AEAUAnimList@1@0@Z proc EXPORT
jmp function_pointers[_AnimsListsManager_base+5*8]
?setupList@AnimsListsManager@@QEAAXAEAV?$lektor@PEAVGameData@@@@AEAUAnimList@1@0@Z endp

?_CONSTRUCTOR@AnimsListsManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimsListsManager@@QEAAPEAV1@XZ endp

; AnimsListsManager::AnimsListsManager();
??0AnimsListsManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimsListsManager_base+6*8]
??0AnimsListsManager@@QEAA@XZ endp
