
; AnimsListsManager::AnimList::getStumbles(class GameData *);
?getStumbles@AnimList@AnimsListsManager@@QEAAPEAV?$lektor@PEAVAnimationData@@@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AnimsListsManager_AnimList_base+0*8]
?getStumbles@AnimList@AnimsListsManager@@QEAAPEAV?$lektor@PEAVAnimationData@@@@PEAVGameData@@@Z endp

; AnimsListsManager::AnimList::getStrafe();
?getStrafe@AnimList@AnimsListsManager@@QEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimsListsManager_AnimList_base+1*8]
?getStrafe@AnimList@AnimsListsManager@@QEAAPEAVAnimationData@@XZ endp

?_CONSTRUCTOR@AnimList@AnimsListsManager@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@AnimList@AnimsListsManager@@QEAAPEAV12@AEBU12@@Z endp

; AnimsListsManager::AnimList::AnimList(const struct AnimsListsManager::AnimList &);
??0AnimList@AnimsListsManager@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_AnimsListsManager_AnimList_base+2*8]
??0AnimList@AnimsListsManager@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@AnimList@AnimsListsManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@AnimList@AnimsListsManager@@QEAAPEAV12@XZ endp

; AnimsListsManager::AnimList::AnimList();
??0AnimList@AnimsListsManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimsListsManager_AnimList_base+3*8]
??0AnimList@AnimsListsManager@@QEAA@XZ endp

?_DESTRUCTOR@AnimList@AnimsListsManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimList@AnimsListsManager@@QEAAXXZ endp

; AnimsListsManager::AnimList::~AnimList();
??1AnimList@AnimsListsManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimsListsManager_AnimList_base+4*8]
??1AnimList@AnimsListsManager@@QEAA@XZ endp
