
; AnimationClassBase::AnimationLayer::addToRemoveList(class AnimationClassBase::SingleAnimation *);
?addToRemoveList@AnimationLayer@AnimationClassBase@@QEAAXPEAVSingleAnimation@2@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+0*8]
?addToRemoveList@AnimationLayer@AnimationClassBase@@QEAAXPEAVSingleAnimation@2@@Z endp

; AnimationClassBase::AnimationLayer::clearLists();
?clearLists@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+1*8]
?clearLists@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::_clearListsSafe();
?_clearListsSafe@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+2*8]
?_clearListsSafe@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::randomiseAnimationPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?randomiseAnimationPosition@AnimationLayer@AnimationClassBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+3*8]
?randomiseAnimationPosition@AnimationLayer@AnimationClassBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::AnimationLayer::runAnimation(bool, class AnimationData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, bool, bool, bool, float, bool, bool, float, bool, float);
?runAnimation@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@_NPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M000M00M0M@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+4*8]
?runAnimation@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@_NPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M000M00M0M@Z endp

; AnimationClassBase::AnimationLayer::startAnimation(bool, class AnimationData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, bool, bool, bool, bool, bool, bool, float, float);
?startAnimation@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@_NPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M000000MM@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+5*8]
?startAnimation@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@_NPEAVAnimationData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M000000MM@Z endp

; AnimationClassBase::AnimationLayer::isAnimationInRemoveList(class AnimationData *);
?isAnimationInRemoveList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+6*8]
?isAnimationInRemoveList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVAnimationData@@@Z endp

; AnimationClassBase::AnimationLayer::isAnimationInAddList(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isAnimationInAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+7*8]
?isAnimationInAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::AnimationLayer::isAnimationInAddList(class CombatTechniqueData *);
?isAnimationInAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVCombatTechniqueData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+8*8]
?isAnimationInAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVCombatTechniqueData@@@Z endp

; AnimationClassBase::AnimationLayer::isAnimationInAddList(class AnimationData *);
?isAnimationInAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+9*8]
?isAnimationInAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVAnimationData@@@Z endp

; AnimationClassBase::AnimationLayer::isAnimationInAddList_Datname(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isAnimationInAddList_Datname@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+10*8]
?isAnimationInAddList_Datname@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::AnimationLayer::takeFromRemoveList(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?takeFromRemoveList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+11*8]
?takeFromRemoveList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::AnimationLayer::takeFromAddList(class AnimationData *);
?takeFromAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+12*8]
?takeFromAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@PEAVAnimationData@@@Z endp

; AnimationClassBase::AnimationLayer::takeFromAddList(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?takeFromAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+13*8]
?takeFromAddList@AnimationLayer@AnimationClassBase@@QEAAPEAVSingleAnimation@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@AnimationLayer@AnimationClassBase@@QEAAPEAV12@PEAVCharMovement@@MPEAV2@@Z proc EXPORT
?_CONSTRUCTOR@AnimationLayer@AnimationClassBase@@QEAAPEAV12@PEAVCharMovement@@MPEAV2@@Z endp

; AnimationClassBase::AnimationLayer::AnimationLayer(class CharMovement *, float, class AnimationClassBase *);
??0AnimationLayer@AnimationClassBase@@QEAA@PEAVCharMovement@@MPEAV1@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+14*8]
??0AnimationLayer@AnimationClassBase@@QEAA@PEAVCharMovement@@MPEAV1@@Z endp

?_DESTRUCTOR@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::~AnimationLayer();
??1AnimationLayer@AnimationClassBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+15*8]
??1AnimationLayer@AnimationClassBase@@QEAA@XZ endp

; AnimationClassBase::AnimationLayer::debugGetAllAnimations(class DatapanelGUI *);
?debugGetAllAnimations@AnimationLayer@AnimationClassBase@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+16*8]
?debugGetAllAnimations@AnimationLayer@AnimationClassBase@@QEAAXPEAVDatapanelGUI@@@Z endp

; AnimationClassBase::AnimationLayer::getTotalAnimationWeight(bool, bool, bool);
?getTotalAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAM_N00@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+17*8]
?getTotalAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAM_N00@Z endp

; AnimationClassBase::AnimationLayer::getTotalAnimationWeight(enum CharacterAnimCategory);
?getTotalAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAMW4CharacterAnimCategory@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+18*8]
?getTotalAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAMW4CharacterAnimCategory@@@Z endp

; AnimationClassBase::AnimationLayer::getTotalActionAnimationWeight();
?getTotalActionAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAMXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+19*8]
?getTotalActionAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAMXZ endp

; AnimationClassBase::AnimationLayer::stillPlayingAnActionOrSomething();
?stillPlayingAnActionOrSomething@AnimationLayer@AnimationClassBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+20*8]
?stillPlayingAnActionOrSomething@AnimationLayer@AnimationClassBase@@QEAA_NXZ endp

; AnimationClassBase::AnimationLayer::getCurrentAnimationWeight(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getCurrentAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+21*8]
?getCurrentAnimationWeight@AnimationLayer@AnimationClassBase@@QEAAMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::AnimationLayer::setBody(class Ogre::Entity *);
?setBody@AnimationLayer@AnimationClassBase@@QEAAXPEAVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+22*8]
?setBody@AnimationLayer@AnimationClassBase@@QEAAXPEAVEntity@Ogre@@@Z endp

; AnimationClassBase::AnimationLayer::updateAnimationSpeed(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?updateAnimationSpeed@AnimationLayer@AnimationClassBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+23*8]
?updateAnimationSpeed@AnimationLayer@AnimationClassBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp

; AnimationClassBase::AnimationLayer::removeAnimation(class AnimationData *);
?removeAnimation@AnimationLayer@AnimationClassBase@@QEAAXPEAVAnimationData@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+24*8]
?removeAnimation@AnimationLayer@AnimationClassBase@@QEAAXPEAVAnimationData@@@Z endp

; AnimationClassBase::AnimationLayer::removeAnimation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?removeAnimation@AnimationLayer@AnimationClassBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+25*8]
?removeAnimation@AnimationLayer@AnimationClassBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AnimationClassBase::AnimationLayer::update2frame();
?update2frame@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+26*8]
?update2frame@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::update(float, class CharMovement *, float, bool, bool, float);
?update@AnimationLayer@AnimationClassBase@@QEAA?AVVector3@Ogre@@MPEAVCharMovement@@M_N1M@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+27*8]
?update@AnimationLayer@AnimationClassBase@@QEAA?AVVector3@Ogre@@MPEAVCharMovement@@M_N1M@Z endp

; AnimationClassBase::AnimationLayer::moveAllToRemoveList();
?moveAllToRemoveList@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+28*8]
?moveAllToRemoveList@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::endAllAnimations();
?endAllAnimations@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+29*8]
?endAllAnimations@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::stopActionAnimations();
?stopActionAnimations@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+30*8]
?stopActionAnimations@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::stopAllAnimation(bool);
?stopAllAnimation@AnimationLayer@AnimationClassBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+31*8]
?stopAllAnimation@AnimationLayer@AnimationClassBase@@QEAAX_N@Z endp

; AnimationClassBase::AnimationLayer::stopAllAnimationThatMovesFromOrigin();
?stopAllAnimationThatMovesFromOrigin@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+32*8]
?stopAllAnimationThatMovesFromOrigin@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::clearAllAnimationUT();
?clearAllAnimationUT@AnimationLayer@AnimationClassBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+33*8]
?clearAllAnimationUT@AnimationLayer@AnimationClassBase@@QEAAXXZ endp

; AnimationClassBase::AnimationLayer::getAnimTime();
?getAnimTime@AnimationLayer@AnimationClassBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+34*8]
?getAnimTime@AnimationLayer@AnimationClassBase@@QEBAMXZ endp

; AnimationClassBase::AnimationLayer::usingRightArm();
?usingRightArm@AnimationLayer@AnimationClassBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+35*8]
?usingRightArm@AnimationLayer@AnimationClassBase@@QEAA_NXZ endp

; AnimationClassBase::AnimationLayer::usingLeftArm();
?usingLeftArm@AnimationLayer@AnimationClassBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationClassBase_AnimationLayer_base+36*8]
?usingLeftArm@AnimationLayer@AnimationClassBase@@QEAA_NXZ endp
