
?_DESTRUCTOR@AnimationChoices@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationChoices@@QEAAXXZ endp

; AnimationChoices::~AnimationChoices();
??1AnimationChoices@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationChoices_base+0*8]
??1AnimationChoices@@QEAA@XZ endp

; AnimationChoices::normaliseWeights();
?normaliseWeights@AnimationChoices@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationChoices_base+1*8]
?normaliseWeights@AnimationChoices@@QEAAXXZ endp

; AnimationChoices::calculateSpeedOfMoveAnims(float, float);
?calculateSpeedOfMoveAnims@AnimationChoices@@QEAAMMM@Z proc EXPORT
jmp function_pointers[_AnimationChoices_base+2*8]
?calculateSpeedOfMoveAnims@AnimationChoices@@QEAAMMM@Z endp

; AnimationChoices::chooseHighestScore();
?chooseHighestScore@AnimationChoices@@QEAAPEAVAnimationData@@XZ proc EXPORT
jmp function_pointers[_AnimationChoices_base+3*8]
?chooseHighestScore@AnimationChoices@@QEAAPEAVAnimationData@@XZ endp

?_CONSTRUCTOR@AnimationChoices@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@AnimationChoices@@QEAAPEAV1@AEBV1@@Z endp

; AnimationChoices::AnimationChoices(const class AnimationChoices &);
??0AnimationChoices@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_AnimationChoices_base+4*8]
??0AnimationChoices@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@AnimationChoices@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationChoices@@QEAAPEAV1@XZ endp

; AnimationChoices::AnimationChoices();
??0AnimationChoices@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationChoices_base+5*8]
??0AnimationChoices@@QEAA@XZ endp
