
?_CONSTRUCTOR@AnimationData@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@AnimationData@@QEAAPEAV1@PEAVGameData@@@Z endp

; AnimationData::AnimationData(class GameData *);
??0AnimationData@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AnimationData_base+0*8]
??0AnimationData@@QEAA@PEAVGameData@@@Z endp

; AnimationData::checkWeaponArms(const class AnimationRequirement &);
?checkWeaponArms@AnimationData@@QEAA_NAEBVAnimationRequirement@@@Z proc EXPORT
jmp function_pointers[_AnimationData_base+1*8]
?checkWeaponArms@AnimationData@@QEAA_NAEBVAnimationRequirement@@@Z endp

; AnimationData::checkModes(const class AnimationRequirement &);
?checkModes@AnimationData@@QEAA_NAEBVAnimationRequirement@@@Z proc EXPORT
jmp function_pointers[_AnimationData_base+2*8]
?checkModes@AnimationData@@QEAA_NAEBVAnimationRequirement@@@Z endp

; AnimationData::scoreInjury(const class AnimationRequirement &);
?scoreInjury@AnimationData@@QEAAMAEBVAnimationRequirement@@@Z proc EXPORT
jmp function_pointers[_AnimationData_base+3*8]
?scoreInjury@AnimationData@@QEAAMAEBVAnimationRequirement@@@Z endp

; AnimationData::scoreSpeed(const class AnimationRequirement &, float);
?scoreSpeed@AnimationData@@QEAAMAEBVAnimationRequirement@@M@Z proc EXPORT
jmp function_pointers[_AnimationData_base+4*8]
?scoreSpeed@AnimationData@@QEAAMAEBVAnimationRequirement@@M@Z endp

; AnimationData::scoreCarryMode(const class AnimationRequirement &);
?scoreCarryMode@AnimationData@@QEAAMAEBVAnimationRequirement@@@Z proc EXPORT
jmp function_pointers[_AnimationData_base+5*8]
?scoreCarryMode@AnimationData@@QEAAMAEBVAnimationRequirement@@@Z endp

; AnimationData::scoreWeaponType(const class AnimationRequirement &);
?scoreWeaponType@AnimationData@@QEAAMAEBVAnimationRequirement@@@Z proc EXPORT
jmp function_pointers[_AnimationData_base+6*8]
?scoreWeaponType@AnimationData@@QEAAMAEBVAnimationRequirement@@@Z endp
