
?_CONSTRUCTOR@AnimationRequirement@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationRequirement@@QEAAPEAV1@XZ endp

; AnimationRequirement::AnimationRequirement();
??0AnimationRequirement@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationRequirement_base+0*8]
??0AnimationRequirement@@QEAA@XZ endp

; AnimationRequirement::isUpperBodyOnlyAction();
?isUpperBodyOnlyAction@AnimationRequirement@@QEAA_NXZ proc EXPORT
jmp function_pointers[_AnimationRequirement_base+1*8]
?isUpperBodyOnlyAction@AnimationRequirement@@QEAA_NXZ endp

; AnimationRequirement::hasAction();
?hasAction@AnimationRequirement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AnimationRequirement_base+2*8]
?hasAction@AnimationRequirement@@QEBA_NXZ endp

; AnimationRequirement::clearAction();
?clearAction@AnimationRequirement@@QEAAXXZ proc EXPORT
jmp function_pointers[_AnimationRequirement_base+3*8]
?clearAction@AnimationRequirement@@QEAAXXZ endp

?_DESTRUCTOR@AnimationRequirement@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationRequirement@@QEAAXXZ endp

; AnimationRequirement::~AnimationRequirement();
??1AnimationRequirement@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationRequirement_base+4*8]
??1AnimationRequirement@@QEAA@XZ endp
