
?_DESTRUCTOR@AnimationEvent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationEvent@@QEAAXXZ endp

; AnimationEvent::~AnimationEvent();
??1AnimationEvent@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationEvent_base+0*8]
??1AnimationEvent@@UEAA@XZ endp

?_NV_trigger@AnimationEvent@@QEBAXPEAVCharacter@@@Z proc EXPORT
?_NV_trigger@AnimationEvent@@QEBAXPEAVCharacter@@@Z endp

; AnimationEvent::trigger(class Character *);
?trigger@AnimationEvent@@UEBAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationEvent_base+1*8]
?trigger@AnimationEvent@@UEBAXPEAVCharacter@@@Z endp

?_NV_finish@AnimationEvent@@QEBAXPEAVCharacter@@@Z proc EXPORT
?_NV_finish@AnimationEvent@@QEBAXPEAVCharacter@@@Z endp

; AnimationEvent::finish(class Character *);
?finish@AnimationEvent@@UEBAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationEvent_base+2*8]
?finish@AnimationEvent@@UEBAXPEAVCharacter@@@Z endp

?_NV_toString@AnimationEvent@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_toString@AnimationEvent@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; AnimationEvent::toString();
?toString@AnimationEvent@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AnimationEvent_base+3*8]
?toString@AnimationEvent@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_CONSTRUCTOR@AnimationEvent@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationEvent@@QEAAPEAV1@XZ endp

; AnimationEvent::AnimationEvent();
??0AnimationEvent@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationEvent_base+4*8]
??0AnimationEvent@@QEAA@XZ endp
