
?_NV_trigger@AnimationReloadEvent@@QEBAXPEAVCharacter@@@Z proc EXPORT
?_NV_trigger@AnimationReloadEvent@@QEBAXPEAVCharacter@@@Z endp

; AnimationReloadEvent::trigger(class Character *);
?trigger@AnimationReloadEvent@@UEBAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationReloadEvent_base+0*8]
?trigger@AnimationReloadEvent@@UEBAXPEAVCharacter@@@Z endp

?_CONSTRUCTOR@AnimationReloadEvent@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimationReloadEvent@@QEAAPEAV1@XZ endp

; AnimationReloadEvent::AnimationReloadEvent();
??0AnimationReloadEvent@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimationReloadEvent_base+1*8]
??0AnimationReloadEvent@@QEAA@XZ endp

?_DESTRUCTOR@AnimationReloadEvent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationReloadEvent@@QEAAXXZ endp

; AnimationReloadEvent::~AnimationReloadEvent();
??1AnimationReloadEvent@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationReloadEvent_base+2*8]
??1AnimationReloadEvent@@UEAA@XZ endp
