
?_CONSTRUCTOR@AnimationSFXEvent@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@AnimationSFXEvent@@QEAAPEAV1@PEAVGameData@@@Z endp

; AnimationSFXEvent::AnimationSFXEvent(class GameData *);
??0AnimationSFXEvent@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AnimationSFXEvent_base+0*8]
??0AnimationSFXEvent@@QEAA@PEAVGameData@@@Z endp

?_NV_trigger@AnimationSFXEvent@@QEBAXPEAVCharacter@@@Z proc EXPORT
?_NV_trigger@AnimationSFXEvent@@QEBAXPEAVCharacter@@@Z endp

; AnimationSFXEvent::trigger(class Character *);
?trigger@AnimationSFXEvent@@UEBAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationSFXEvent_base+1*8]
?trigger@AnimationSFXEvent@@UEBAXPEAVCharacter@@@Z endp

?_NV_finish@AnimationSFXEvent@@QEBAXPEAVCharacter@@@Z proc EXPORT
?_NV_finish@AnimationSFXEvent@@QEBAXPEAVCharacter@@@Z endp

; AnimationSFXEvent::finish(class Character *);
?finish@AnimationSFXEvent@@UEBAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AnimationSFXEvent_base+2*8]
?finish@AnimationSFXEvent@@UEBAXPEAVCharacter@@@Z endp

?_NV_toString@AnimationSFXEvent@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_toString@AnimationSFXEvent@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; AnimationSFXEvent::toString();
?toString@AnimationSFXEvent@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AnimationSFXEvent_base+3*8]
?toString@AnimationSFXEvent@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_DESTRUCTOR@AnimationSFXEvent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimationSFXEvent@@QEAAXXZ endp

; AnimationSFXEvent::~AnimationSFXEvent();
??1AnimationSFXEvent@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimationSFXEvent_base+4*8]
??1AnimationSFXEvent@@UEAA@XZ endp
