
?_CONSTRUCTOR@AttackState@@QEAAPEAV1@PEAVCombatClass@@@Z proc EXPORT
?_CONSTRUCTOR@AttackState@@QEAAPEAV1@PEAVCombatClass@@@Z endp

; AttackState::AttackState(class CombatClass *);
??0AttackState@@QEAA@PEAVCombatClass@@@Z proc EXPORT
jmp function_pointers[_AttackState_base+0*8]
??0AttackState@@QEAA@PEAVCombatClass@@@Z endp

?_NV_validate@AttackState@@QEAA_NXZ proc EXPORT
?_NV_validate@AttackState@@QEAA_NXZ endp

; AttackState::validate();
?validate@AttackState@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AttackState_base+1*8]
?validate@AttackState@@UEAA_NXZ endp

; AttackState::initialiseAttack(class Character *);
?initialiseAttack@AttackState@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AttackState_base+2*8]
?initialiseAttack@AttackState@@QEAA_NPEAVCharacter@@@Z endp

?_NV_initialise@AttackState@@QEAA_NXZ proc EXPORT
?_NV_initialise@AttackState@@QEAA_NXZ endp

; AttackState::initialise();
?initialise@AttackState@@UEAA_NXZ proc EXPORT
jmp function_pointers[_AttackState_base+3*8]
?initialise@AttackState@@UEAA_NXZ endp

?_NV_update@AttackState@@QEAAXM@Z proc EXPORT
?_NV_update@AttackState@@QEAAXM@Z endp

; AttackState::update(float);
?update@AttackState@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AttackState_base+4*8]
?update@AttackState@@UEAAXM@Z endp

?_NV_end@AttackState@@QEAAXXZ proc EXPORT
?_NV_end@AttackState@@QEAAXXZ endp

; AttackState::end();
?end@AttackState@@UEAAXXZ proc EXPORT
jmp function_pointers[_AttackState_base+5*8]
?end@AttackState@@UEAAXXZ endp
