
; Blackboard::createNewPackage(enum BlackboardSignalFunctions, class GameData *, int, const class hand &);
?createNewPackage@Blackboard@@QEAAPEAVAIPackage@@W4BlackboardSignalFunctions@@PEAVGameData@@HAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+0*8]
?createNewPackage@Blackboard@@QEAAPEAVAIPackage@@W4BlackboardSignalFunctions@@PEAVGameData@@HAEBVhand@@@Z endp

; Blackboard::_setContractJob(class GameData *, int, const class hand &);
?_setContractJob@Blackboard@@QEAAXPEAVGameData@@HAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+1*8]
?_setContractJob@Blackboard@@QEAAXPEAVGameData@@HAEBVhand@@@Z endp

; Blackboard::_addPackage(class GameData *, int);
?_addPackage@Blackboard@@QEAAXPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_Blackboard_base+2*8]
?_addPackage@Blackboard@@QEAAXPEAVGameData@@H@Z endp

; Blackboard::clearAllPackages();
?clearAllPackages@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+3*8]
?clearAllPackages@Blackboard@@QEAAXXZ endp

; Blackboard::_activateCurrentPackage(class AIPackage *);
?_activateCurrentPackage@Blackboard@@QEAAXPEAVAIPackage@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+4*8]
?_activateCurrentPackage@Blackboard@@QEAAXPEAVAIPackage@@@Z endp

; Blackboard::_addFromData(class GameData *);
?_addFromData@Blackboard@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+5*8]
?_addFromData@Blackboard@@QEAAXPEAVGameData@@@Z endp

; Blackboard::getPackage(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getPackage@Blackboard@@QEAAPEAVAIPackage@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+6*8]
?getPackage@Blackboard@@QEAAPEAVAIPackage@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Blackboard::getPackageList(int);
?getPackageList@Blackboard@@QEAAPEAV?$lektor@PEAVAIPackage@@@@H@Z proc EXPORT
jmp function_pointers[_Blackboard_base+7*8]
?getPackageList@Blackboard@@QEAAPEAV?$lektor@PEAVAIPackage@@@@H@Z endp

; Blackboard::periodicPackageCheck(int, float);
?periodicPackageCheck@Blackboard@@QEAA_NHM@Z proc EXPORT
jmp function_pointers[_Blackboard_base+8*8]
?periodicPackageCheck@Blackboard@@QEAA_NHM@Z endp

; Blackboard::resetAllTheStaticData();
?resetAllTheStaticData@Blackboard@@SAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+9*8]
?resetAllTheStaticData@Blackboard@@SAXXZ endp

; Blackboard::dialogEventsCheck(class GameData *, const class hand &);
?dialogEventsCheck@Blackboard@@QEAAXPEAVGameData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+10*8]
?dialogEventsCheck@Blackboard@@QEAAXPEAVGameData@@AEBVhand@@@Z endp

; Blackboard::setContractJob(class GameData *, const class hand &);
?setContractJob@Blackboard@@QEAAXPEAVGameData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+11*8]
?setContractJob@Blackboard@@QEAAXPEAVGameData@@AEBVhand@@@Z endp

; Blackboard::endContractJob();
?endContractJob@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+12*8]
?endContractJob@Blackboard@@QEAAXXZ endp

; Blackboard::isMissionComplete();
?isMissionComplete@Blackboard@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Blackboard_base+13*8]
?isMissionComplete@Blackboard@@QEAA_NXZ endp

; Blackboard::isTargetMarkedForDeath(class Building *, class TownBase *);
?isTargetMarkedForDeath@Blackboard@@QEAA_NPEAVBuilding@@PEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+14*8]
?isTargetMarkedForDeath@Blackboard@@QEAA_NPEAVBuilding@@PEAVTownBase@@@Z endp

?_CONSTRUCTOR@Blackboard@@QEAAPEAV1@PEAVPlatoon@@@Z proc EXPORT
?_CONSTRUCTOR@Blackboard@@QEAAPEAV1@PEAVPlatoon@@@Z endp

; Blackboard::Blackboard(class Platoon *);
??0Blackboard@@QEAA@PEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+15*8]
??0Blackboard@@QEAA@PEAVPlatoon@@@Z endp

?_DESTRUCTOR@Blackboard@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Blackboard@@QEAAXXZ endp

; Blackboard::~Blackboard();
??1Blackboard@@QEAA@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+16*8]
??1Blackboard@@QEAA@XZ endp

; Blackboard::update(float);
?update@Blackboard@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Blackboard_base+17*8]
?update@Blackboard@@QEAAXM@Z endp

; Blackboard::periodicUpdate(float);
?periodicUpdate@Blackboard@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Blackboard_base+18*8]
?periodicUpdate@Blackboard@@QEAAXM@Z endp

; Blackboard::addPackages(class GameData *);
?addPackages@Blackboard@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+19*8]
?addPackages@Blackboard@@QEAAXPEAVGameData@@@Z endp

; Blackboard::addFallbackPackages(class GameData *);
?addFallbackPackages@Blackboard@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+20*8]
?addFallbackPackages@Blackboard@@QEAAXPEAVGameData@@@Z endp

; Blackboard::replaceAIPackage(class GameData *);
?replaceAIPackage@Blackboard@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+21*8]
?replaceAIPackage@Blackboard@@QEAAXPEAVGameData@@@Z endp

; Blackboard::getCurrentAIPackageName();
?getCurrentAIPackageName@Blackboard@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+22*8]
?getCurrentAIPackageName@Blackboard@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Blackboard::getCurrentAIPackageGUIData(class DatapanelGUI *, int);
?getCurrentAIPackageGUIData@Blackboard@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Blackboard_base+23*8]
?getCurrentAIPackageGUIData@Blackboard@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Blackboard::assessNeutral(class Character *);
?assessNeutral@Blackboard@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+24*8]
?assessNeutral@Blackboard@@QEAAXPEAVCharacter@@@Z endp

; Blackboard::assessEnemy(class Character *);
?assessEnemy@Blackboard@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+25*8]
?assessEnemy@Blackboard@@QEAA_NPEAVCharacter@@@Z endp

; Blackboard::getCurrentPackage();
?getCurrentPackage@Blackboard@@QEAAPEAVAIPackage@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+26*8]
?getCurrentPackage@Blackboard@@QEAAPEAVAIPackage@@XZ endp

; Blackboard::getFormationPositionOffset(class Character *);
?getFormationPositionOffset@Blackboard@@QEAAAEBVVector3@Ogre@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+27*8]
?getFormationPositionOffset@Blackboard@@QEAAAEBVVector3@Ogre@@PEAVCharacter@@@Z endp

; Blackboard::nodifyFormationUpdate();
?nodifyFormationUpdate@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+28*8]
?nodifyFormationUpdate@Blackboard@@QEAAXXZ endp

; Blackboard::getOwnerships();
?getOwnerships@Blackboard@@QEAAPEAVOwnerships@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+29*8]
?getOwnerships@Blackboard@@QEAAPEAVOwnerships@@XZ endp

; Blackboard::notifyGoalStart(class Tasker *, const class hand &);
?notifyGoalStart@Blackboard@@QEAAXPEAVTasker@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+30*8]
?notifyGoalStart@Blackboard@@QEAAXPEAVTasker@@AEBVhand@@@Z endp

; Blackboard::notifyGoalEnd(const class hand &);
?notifyGoalEnd@Blackboard@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+31*8]
?notifyGoalEnd@Blackboard@@QEAAXAEBVhand@@@Z endp

; Blackboard::notifySubTarget(const class hand &, const class hand &);
?notifySubTarget@Blackboard@@QEAAXAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_Blackboard_base+32*8]
?notifySubTarget@Blackboard@@QEAAXAEBVhand@@0@Z endp

; Blackboard::howManyGuysDoingThisGoal(class Tasker *, const class hand &);
?howManyGuysDoingThisGoal@Blackboard@@QEBAHPEAVTasker@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+33*8]
?howManyGuysDoingThisGoal@Blackboard@@QEBAHPEAVTasker@@AEBVhand@@@Z endp

; Blackboard::howManyGuysWorkingOnThisSubTarget(class Tasker *, const class hand &, const class hand &);
?howManyGuysWorkingOnThisSubTarget@Blackboard@@QEBAHPEAVTasker@@AEBVhand@@1@Z proc EXPORT
jmp function_pointers[_Blackboard_base+34*8]
?howManyGuysWorkingOnThisSubTarget@Blackboard@@QEBAHPEAVTasker@@AEBVhand@@1@Z endp

; Blackboard::howManyGuysWorkingOnThisSubTarget(const class hand &, const class hand &);
?howManyGuysWorkingOnThisSubTarget@Blackboard@@QEBAHAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_Blackboard_base+35*8]
?howManyGuysWorkingOnThisSubTarget@Blackboard@@QEBAHAEBVhand@@0@Z endp

; Blackboard::isMySubTarget(class Tasker *, const class hand &, const class hand &);
?isMySubTarget@Blackboard@@QEBA_NPEAVTasker@@AEBVhand@@1@Z proc EXPORT
jmp function_pointers[_Blackboard_base+36*8]
?isMySubTarget@Blackboard@@QEBA_NPEAVTasker@@AEBVhand@@1@Z endp

; Blackboard::getSubTarget(const class hand &, class hand &);
?getSubTarget@Blackboard@@QEAAXAEBVhand@@AEAV2@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+37*8]
?getSubTarget@Blackboard@@QEAAXAEBVhand@@AEAV2@@Z endp

; Blackboard::addRequest(const class hand &, const class hand &, enum TaskType, const class hand &, enum taskPriority, float);
?addRequest@Blackboard@@QEAAXAEBVhand@@0W4TaskType@@0W4taskPriority@@M@Z proc EXPORT
jmp function_pointers[_Blackboard_base+38*8]
?addRequest@Blackboard@@QEAAXAEBVhand@@0W4TaskType@@0W4taskPriority@@M@Z endp

; Blackboard::removeRequest(const class hand &);
?removeRequest@Blackboard@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+39*8]
?removeRequest@Blackboard@@QEAAXAEBVhand@@@Z endp

; Blackboard::getRequests(class lektor<Tasker *> &, enum taskPriority, const class hand &, class TaskRepertoire *);
?getRequests@Blackboard@@QEAAXAEAV?$lektor@PEAVTasker@@@@W4taskPriority@@AEBVhand@@PEAVTaskRepertoire@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+40*8]
?getRequests@Blackboard@@QEAAXAEAV?$lektor@PEAVTasker@@@@W4taskPriority@@AEBVhand@@PEAVTaskRepertoire@@@Z endp

; Blackboard::notifyJobCompleted(enum TaskType, const class hand &, const class hand &);
?notifyJobCompleted@Blackboard@@QEAAXW4TaskType@@AEBVhand@@1@Z proc EXPORT
jmp function_pointers[_Blackboard_base+41*8]
?notifyJobCompleted@Blackboard@@QEAAXW4TaskType@@AEBVhand@@1@Z endp

; Blackboard::addSquadJob(enum SquadMemberType, enum TaskType, const class hand &, enum taskPriority, float, enum TaskTargetType, enum TaskEndEvent, int, int);
?addSquadJob@Blackboard@@QEAAXW4SquadMemberType@@W4TaskType@@AEBVhand@@W4taskPriority@@MW4TaskTargetType@@W4TaskEndEvent@@HH@Z proc EXPORT
jmp function_pointers[_Blackboard_base+42*8]
?addSquadJob@Blackboard@@QEAAXW4SquadMemberType@@W4TaskType@@AEBVhand@@W4taskPriority@@MW4TaskTargetType@@W4TaskEndEvent@@HH@Z endp

; Blackboard::getSquadJobs(enum SquadMemberType, class lektor<Tasker *> &, unsigned int, const class hand &, class TaskRepertoire *);
?getSquadJobs@Blackboard@@QEAAXW4SquadMemberType@@AEAV?$lektor@PEAVTasker@@@@IAEBVhand@@PEAVTaskRepertoire@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+43*8]
?getSquadJobs@Blackboard@@QEAAXW4SquadMemberType@@AEAV?$lektor@PEAVTasker@@@@IAEBVhand@@PEAVTaskRepertoire@@@Z endp

; Blackboard::getUnloadedPlatoonJob();
?getUnloadedPlatoonJob@Blackboard@@QEBA?AW4UnloadedPlatoonJob@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+44*8]
?getUnloadedPlatoonJob@Blackboard@@QEBA?AW4UnloadedPlatoonJob@@XZ endp

; Blackboard::clearAllTheJobs();
?clearAllTheJobs@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+45*8]
?clearAllTheJobs@Blackboard@@QEAAXXZ endp

; Blackboard::serialise(class GameData *);
?serialise@Blackboard@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+46*8]
?serialise@Blackboard@@QEAAXPEAVGameData@@@Z endp

; Blackboard::load(class GameData *);
?load@Blackboard@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+47*8]
?load@Blackboard@@QEAAXPEAVGameData@@@Z endp

; Blackboard::stateUpdate(float);
?stateUpdate@Blackboard@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Blackboard_base+48*8]
?stateUpdate@Blackboard@@QEAAXM@Z endp

; Blackboard::notifyMissionTargetPathfindImpossible(class Character *, const class hand &);
?notifyMissionTargetPathfindImpossible@Blackboard@@QEAAXPEAVCharacter@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+49*8]
?notifyMissionTargetPathfindImpossible@Blackboard@@QEAAXPEAVCharacter@@AEBVhand@@@Z endp

; Blackboard::getMissionTarget(class Character *);
?getMissionTarget@Blackboard@@QEAA?AVTargetInfo@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+50*8]
?getMissionTarget@Blackboard@@QEAA?AVTargetInfo@@PEAVCharacter@@@Z endp

; Blackboard::getMissionTown(bool);
?getMissionTown@Blackboard@@QEAA?AVhand@@_N@Z proc EXPORT
jmp function_pointers[_Blackboard_base+51*8]
?getMissionTown@Blackboard@@QEAA?AVhand@@_N@Z endp

; Blackboard::getMissionGiver();
?getMissionGiver@Blackboard@@QEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+52*8]
?getMissionGiver@Blackboard@@QEAA?AVhand@@XZ endp

; Blackboard::getCurrentTownLocation();
?getCurrentTownLocation@Blackboard@@QEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+53*8]
?getCurrentTownLocation@Blackboard@@QEAAPEAVTownBase@@XZ endp

; Blackboard::getTimeSpentInTown_inGameHours();
?getTimeSpentInTown_inGameHours@Blackboard@@QEAAMXZ proc EXPORT
jmp function_pointers[_Blackboard_base+54*8]
?getTimeSpentInTown_inGameHours@Blackboard@@QEAAMXZ endp

; Blackboard::setMyHomeIsLocked(bool);
?setMyHomeIsLocked@Blackboard@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Blackboard_base+55*8]
?setMyHomeIsLocked@Blackboard@@QEAAX_N@Z endp

; Blackboard::getMyHomeIsLocked();
?getMyHomeIsLocked@Blackboard@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Blackboard_base+56*8]
?getMyHomeIsLocked@Blackboard@@QEBA_NXZ endp

; Blackboard::getHomeGate();
?getHomeGate@Blackboard@@QEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+57*8]
?getHomeGate@Blackboard@@QEAA?AVhand@@XZ endp

; Blackboard::hasContractJob();
?hasContractJob@Blackboard@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Blackboard_base+58*8]
?hasContractJob@Blackboard@@QEBA_NXZ endp

; Blackboard::getContractExpiryTime();
?getContractExpiryTime@Blackboard@@QEBA?AVTimeOfDay@@XZ proc EXPORT
jmp function_pointers[_Blackboard_base+59*8]
?getContractExpiryTime@Blackboard@@QEBA?AVTimeOfDay@@XZ endp

; Blackboard::contractJobNotifyBetrayal(class Character *, class Character *);
?contractJobNotifyBetrayal@Blackboard@@QEAAXPEAVCharacter@@0@Z proc EXPORT
jmp function_pointers[_Blackboard_base+60*8]
?contractJobNotifyBetrayal@Blackboard@@QEAAXPEAVCharacter@@0@Z endp

; Blackboard::contractJobWasBetrayal();
?contractJobWasBetrayal@Blackboard@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Blackboard_base+61*8]
?contractJobWasBetrayal@Blackboard@@QEAA_NXZ endp

?_NV_showEndedMessage@Blackboard@@QEAAXXZ proc EXPORT
?_NV_showEndedMessage@Blackboard@@QEAAXXZ endp

; Blackboard::showEndedMessage();
?showEndedMessage@Blackboard@@UEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+62*8]
?showEndedMessage@Blackboard@@UEAAXXZ endp

; Blackboard::_serialiseJobList(class GameData *, const class lektor<TaskRequest> &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_serialiseJobList@Blackboard@@QEAAXPEAVGameData@@AEBV?$lektor@VTaskRequest@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+63*8]
?_serialiseJobList@Blackboard@@QEAAXPEAVGameData@@AEBV?$lektor@VTaskRequest@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Blackboard::_loadJobList(class GameData *, class lektor<TaskRequest> &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_loadJobList@Blackboard@@QEAAXPEAVGameData@@AEAV?$lektor@VTaskRequest@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+64*8]
?_loadJobList@Blackboard@@QEAAXPEAVGameData@@AEAV?$lektor@VTaskRequest@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Blackboard::_setupJobFromData(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum SquadMemberType);
?_setupJobFromData@Blackboard@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4SquadMemberType@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+65*8]
?_setupJobFromData@Blackboard@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4SquadMemberType@@@Z endp

; Blackboard::countCharacters();
?countCharacters@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+66*8]
?countCharacters@Blackboard@@QEAAXXZ endp

; Blackboard::runAwayCheck();
?runAwayCheck@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+67*8]
?runAwayCheck@Blackboard@@QEAAXXZ endp

; Blackboard::runAway();
?runAway@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+68*8]
?runAway@Blackboard@@QEAAXXZ endp

; Blackboard::getJobList(enum SquadMemberType);
?getJobList@Blackboard@@QEAAPEAV?$lektor@VTaskRequest@@@@W4SquadMemberType@@@Z proc EXPORT
jmp function_pointers[_Blackboard_base+69*8]
?getJobList@Blackboard@@QEAAPEAV?$lektor@VTaskRequest@@@@W4SquadMemberType@@@Z endp

; Blackboard::buildFormation();
?buildFormation@Blackboard@@QEAAXXZ proc EXPORT
jmp function_pointers[_Blackboard_base+70*8]
?buildFormation@Blackboard@@QEAAXXZ endp

; Blackboard::getGridPositions(class std::vector<Ogre::Vector3,Ogre::STLAllocator<Ogre::Vector3,Ogre::CategorisedAllocPolicy<0> > > &, int, int, int, float, float, float, float);
?getGridPositions@Blackboard@@QEAAXAEAV?$vector@VVector3@Ogre@@V?$STLAllocator@VVector3@Ogre@@V?$CategorisedAllocPolicy@$0A@@2@@2@@std@@HHHMMMM@Z proc EXPORT
jmp function_pointers[_Blackboard_base+71*8]
?getGridPositions@Blackboard@@QEAAXAEAV?$vector@VVector3@Ogre@@V?$STLAllocator@VVector3@Ogre@@V?$CategorisedAllocPolicy@$0A@@2@@2@@std@@HHHMMMM@Z endp
