
?_CONSTRUCTOR@TaskInfo@Blackboard@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TaskInfo@Blackboard@@QEAAPEAV12@XZ endp

; Blackboard::TaskInfo::TaskInfo();
??0TaskInfo@Blackboard@@QEAA@XZ proc EXPORT
jmp function_pointers[_Blackboard_TaskInfo_base+0*8]
??0TaskInfo@Blackboard@@QEAA@XZ endp

; Blackboard::TaskInfo::operator=(const class Blackboard::TaskInfo &);
??4TaskInfo@Blackboard@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_Blackboard_TaskInfo_base+1*8]
??4TaskInfo@Blackboard@@QEAAAEAV01@AEBV01@@Z endp
