
?_NV_getClassType@BlueprintItem@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@BlueprintItem@@QEBA?AW4itemType@@XZ endp

; BlueprintItem::getClassType();
?getClassType@BlueprintItem@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_BlueprintItem_base+0*8]
?getClassType@BlueprintItem@@UEBA?AW4itemType@@XZ endp

?_NV_getItemWeight@BlueprintItem@@QEBAMXZ proc EXPORT
?_NV_getItemWeight@BlueprintItem@@QEBAMXZ endp

; BlueprintItem::getItemWeight();
?getItemWeight@BlueprintItem@@UEBAMXZ proc EXPORT
jmp function_pointers[_BlueprintItem_base+1*8]
?getItemWeight@BlueprintItem@@UEBAMXZ endp

?_NV_getValueSingle@BlueprintItem@@QEBAH_N@Z proc EXPORT
?_NV_getValueSingle@BlueprintItem@@QEBAH_N@Z endp

; BlueprintItem::getValueSingle(bool);
?getValueSingle@BlueprintItem@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_BlueprintItem_base+2*8]
?getValueSingle@BlueprintItem@@UEBAH_N@Z endp

; BlueprintItem::getResearchData();
?getResearchData@BlueprintItem@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_BlueprintItem_base+3*8]
?getResearchData@BlueprintItem@@QEAAPEAVGameData@@XZ endp

?_NV_getTooltipData1@BlueprintItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@BlueprintItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; BlueprintItem::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@BlueprintItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_BlueprintItem_base+4*8]
?getTooltipData1@BlueprintItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@BlueprintItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@BlueprintItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; BlueprintItem::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@BlueprintItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_BlueprintItem_base+5*8]
?getTooltipData2@BlueprintItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getGUIData@BlueprintItem@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@BlueprintItem@@QEAAXPEAVDatapanelGUI@@H@Z endp

; BlueprintItem::getGUIData(class DatapanelGUI *, int);
?getGUIData@BlueprintItem@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_BlueprintItem_base+6*8]
?getGUIData@BlueprintItem@@UEAAXPEAVDatapanelGUI@@H@Z endp

; BlueprintItem::learnResearch();
?learnResearch@BlueprintItem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_BlueprintItem_base+7*8]
?learnResearch@BlueprintItem@@QEAA_NXZ endp

?_CONSTRUCTOR@BlueprintItem@@QEAAPEAV1@PEAVGameData@@0Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@BlueprintItem@@QEAAPEAV1@PEAVGameData@@0Vhand@@@Z endp

; BlueprintItem::BlueprintItem(class GameData *, class GameData *, class hand);
??0BlueprintItem@@QEAA@PEAVGameData@@0Vhand@@@Z proc EXPORT
jmp function_pointers[_BlueprintItem_base+8*8]
??0BlueprintItem@@QEAA@PEAVGameData@@0Vhand@@@Z endp

?_DESTRUCTOR@BlueprintItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BlueprintItem@@QEAAXXZ endp

; BlueprintItem::~BlueprintItem();
??1BlueprintItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_BlueprintItem_base+9*8]
??1BlueprintItem@@UEAA@XZ endp

; BlueprintItem::printResearch(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?printResearch@BlueprintItem@@SAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@2@Z proc EXPORT
jmp function_pointers[_BlueprintItem_base+10*8]
?printResearch@BlueprintItem@@SAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@2@Z endp
