
; CampaignData::_setupPackages(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum Phase);
?_setupPackages@CampaignData@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Phase@@@Z proc EXPORT
jmp function_pointers[_CampaignData_base+0*8]
?_setupPackages@CampaignData@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Phase@@@Z endp

; CampaignData::_addDataFrom(class GameData *);
?_addDataFrom@CampaignData@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CampaignData_base+1*8]
?_addDataFrom@CampaignData@@QEAAXPEAVGameData@@@Z endp

?_CONSTRUCTOR@CampaignData@@QEAAPEAV1@PEAVFaction@@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@CampaignData@@QEAAPEAV1@PEAVFaction@@PEAVGameData@@@Z endp

; CampaignData::CampaignData(class Faction *, class GameData *);
??0CampaignData@@QEAA@PEAVFaction@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CampaignData_base+2*8]
??0CampaignData@@QEAA@PEAVFaction@@PEAVGameData@@@Z endp

?_DESTRUCTOR@CampaignData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CampaignData@@QEAAXXZ endp

; CampaignData::~CampaignData();
??1CampaignData@@QEAA@XZ proc EXPORT
jmp function_pointers[_CampaignData_base+3*8]
??1CampaignData@@QEAA@XZ endp

; CampaignData::reset();
?reset@CampaignData@@QEAAXXZ proc EXPORT
jmp function_pointers[_CampaignData_base+4*8]
?reset@CampaignData@@QEAAXXZ endp

; CampaignData::key();
?key@CampaignData@@QEAA?AW4WarCampaignEnum@@XZ proc EXPORT
jmp function_pointers[_CampaignData_base+5*8]
?key@CampaignData@@QEAA?AW4WarCampaignEnum@@XZ endp

; CampaignData::isHostile();
?isHostile@CampaignData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CampaignData_base+6*8]
?isHostile@CampaignData@@QEBA_NXZ endp

; CampaignData::getDisplayName();
?getDisplayName@CampaignData@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_CampaignData_base+7*8]
?getDisplayName@CampaignData@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; CampaignData::isTriggersRandomly();
?isTriggersRandomly@CampaignData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CampaignData_base+8*8]
?isTriggersRandomly@CampaignData@@QEBA_NXZ endp

?_NV_chooseTarget@CampaignData@@QEAAPEAVRootObjectBase@@PEAVFaction@@PEAPEAVTownBase@@@Z proc EXPORT
?_NV_chooseTarget@CampaignData@@QEAAPEAVRootObjectBase@@PEAVFaction@@PEAPEAVTownBase@@@Z endp

; CampaignData::chooseTarget(class Faction *, class TownBase * *);
?chooseTarget@CampaignData@@UEAAPEAVRootObjectBase@@PEAVFaction@@PEAPEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_CampaignData_base+9*8]
?chooseTarget@CampaignData@@UEAAPEAVRootObjectBase@@PEAVFaction@@PEAPEAVTownBase@@@Z endp

?_NV_territorialTriggerScore@CampaignData@@QEAAMPEAVFaction@@PEAVRootObjectBase@@@Z proc EXPORT
?_NV_territorialTriggerScore@CampaignData@@QEAAMPEAVFaction@@PEAVRootObjectBase@@@Z endp

; CampaignData::territorialTriggerScore(class Faction *, class RootObjectBase *);
?territorialTriggerScore@CampaignData@@UEAAMPEAVFaction@@PEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_CampaignData_base+10*8]
?territorialTriggerScore@CampaignData@@UEAAMPEAVFaction@@PEAVRootObjectBase@@@Z endp

?_NV_canStart@CampaignData@@QEAA_NXZ proc EXPORT
?_NV_canStart@CampaignData@@QEAA_NXZ endp

; CampaignData::canStart();
?canStart@CampaignData@@UEAA_NXZ proc EXPORT
jmp function_pointers[_CampaignData_base+11*8]
?canStart@CampaignData@@UEAA_NXZ endp

; CampaignData::numForcesNeeded();
?numForcesNeeded@CampaignData@@QEAAHXZ proc EXPORT
jmp function_pointers[_CampaignData_base+12*8]
?numForcesNeeded@CampaignData@@QEAAHXZ endp

; CampaignData::ignoresMults();
?ignoresMults@CampaignData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CampaignData_base+13*8]
?ignoresMults@CampaignData@@QEAA_NXZ endp

; CampaignData::canUseThisSquad(class GameData *);
?canUseThisSquad@CampaignData@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CampaignData_base+14*8]
?canUseThisSquad@CampaignData@@QEAA_NPEAVGameData@@@Z endp
