
?_NV_signalEnd@Campaign_DefendPlayerBase@@QEAA_NXZ proc EXPORT
?_NV_signalEnd@Campaign_DefendPlayerBase@@QEAA_NXZ endp

; Campaign_DefendPlayerBase::signalEnd();
?signalEnd@Campaign_DefendPlayerBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Campaign_DefendPlayerBase_base+0*8]
?signalEnd@Campaign_DefendPlayerBase@@UEAA_NXZ endp

?_CONSTRUCTOR@Campaign_DefendPlayerBase@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Campaign_DefendPlayerBase@@QEAAPEAV1@XZ endp

; Campaign_DefendPlayerBase::Campaign_DefendPlayerBase();
??0Campaign_DefendPlayerBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_Campaign_DefendPlayerBase_base+1*8]
??0Campaign_DefendPlayerBase@@QEAA@XZ endp

?_DESTRUCTOR@Campaign_DefendPlayerBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Campaign_DefendPlayerBase@@QEAAXXZ endp

; Campaign_DefendPlayerBase::~Campaign_DefendPlayerBase();
??1Campaign_DefendPlayerBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_Campaign_DefendPlayerBase_base+2*8]
??1Campaign_DefendPlayerBase@@UEAA@XZ endp
