
?_CONSTRUCTOR@CircleStateAI@@QEAAPEAV1@PEAVCombatClass@@@Z proc EXPORT
?_CONSTRUCTOR@CircleStateAI@@QEAAPEAV1@PEAVCombatClass@@@Z endp

; CircleStateAI::CircleStateAI(class CombatClass *);
??0CircleStateAI@@QEAA@PEAVCombatClass@@@Z proc EXPORT
jmp function_pointers[_CircleStateAI_base+0*8]
??0CircleStateAI@@QEAA@PEAVCombatClass@@@Z endp

; CircleStateAI::amOverCrowded();
?amOverCrowded@CircleStateAI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CircleStateAI_base+1*8]
?amOverCrowded@CircleStateAI@@QEAA_NXZ endp

?_NV_validate@CircleStateAI@@QEAA_NXZ proc EXPORT
?_NV_validate@CircleStateAI@@QEAA_NXZ endp

; CircleStateAI::validate();
?validate@CircleStateAI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_CircleStateAI_base+2*8]
?validate@CircleStateAI@@UEAA_NXZ endp

?_NV_initialise@CircleStateAI@@QEAA_NXZ proc EXPORT
?_NV_initialise@CircleStateAI@@QEAA_NXZ endp

; CircleStateAI::initialise();
?initialise@CircleStateAI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_CircleStateAI_base+3*8]
?initialise@CircleStateAI@@UEAA_NXZ endp

?_NV_update@CircleStateAI@@QEAAXM@Z proc EXPORT
?_NV_update@CircleStateAI@@QEAAXM@Z endp

; CircleStateAI::update(float);
?update@CircleStateAI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CircleStateAI_base+4*8]
?update@CircleStateAI@@UEAAXM@Z endp

?_NV_end@CircleStateAI@@QEAAXXZ proc EXPORT
?_NV_end@CircleStateAI@@QEAAXXZ endp

; CircleStateAI::end();
?end@CircleStateAI@@UEAAXXZ proc EXPORT
jmp function_pointers[_CircleStateAI_base+5*8]
?end@CircleStateAI@@UEAAXXZ endp
