
?_CONSTRUCTOR@CombatClassAI@@QEAAPEAV1@PEAVCharMovement@@PEAVAI@@PEAVAnimationClass@@PEAVCharacter@@PEAVCharStats@@PEAVMedicalSystem@@@Z proc EXPORT
?_CONSTRUCTOR@CombatClassAI@@QEAAPEAV1@PEAVCharMovement@@PEAVAI@@PEAVAnimationClass@@PEAVCharacter@@PEAVCharStats@@PEAVMedicalSystem@@@Z endp

; CombatClassAI::CombatClassAI(class CharMovement *, class AI *, class AnimationClass *, class Character *, class CharStats *, class MedicalSystem *);
??0CombatClassAI@@QEAA@PEAVCharMovement@@PEAVAI@@PEAVAnimationClass@@PEAVCharacter@@PEAVCharStats@@PEAVMedicalSystem@@@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+0*8]
??0CombatClassAI@@QEAA@PEAVCharMovement@@PEAVAI@@PEAVAnimationClass@@PEAVCharacter@@PEAVCharStats@@PEAVMedicalSystem@@@Z endp

?_DESTRUCTOR@CombatClassAI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CombatClassAI@@QEAAXXZ endp

; CombatClassAI::~CombatClassAI();
??1CombatClassAI@@UEAA@XZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+1*8]
??1CombatClassAI@@UEAA@XZ endp

?_NV_update@CombatClassAI@@QEAAXM@Z proc EXPORT
?_NV_update@CombatClassAI@@QEAAXM@Z endp

; CombatClassAI::update(float);
?update@CombatClassAI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+2*8]
?update@CombatClassAI@@UEAAXM@Z endp

?_NV_periodicUpdate@CombatClassAI@@QEAAXM@Z proc EXPORT
?_NV_periodicUpdate@CombatClassAI@@QEAAXM@Z endp

; CombatClassAI::periodicUpdate(float);
?periodicUpdate@CombatClassAI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+3*8]
?periodicUpdate@CombatClassAI@@UEAAXM@Z endp

?_NV_initCombatMode@CombatClassAI@@QEAA_NAEBVhand@@H_N@Z proc EXPORT
?_NV_initCombatMode@CombatClassAI@@QEAA_NAEBVhand@@H_N@Z endp

; CombatClassAI::initCombatMode(const class hand &, int, bool);
?initCombatMode@CombatClassAI@@UEAA_NAEBVhand@@H_N@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+4*8]
?initCombatMode@CombatClassAI@@UEAA_NAEBVhand@@H_N@Z endp

?_NV_isAI@CombatClassAI@@QEBA_NXZ proc EXPORT
?_NV_isAI@CombatClassAI@@QEBA_NXZ endp

; CombatClassAI::isAI();
?isAI@CombatClassAI@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+5*8]
?isAI@CombatClassAI@@UEBA_NXZ endp

?_NV_hasFocusedTarget@CombatClassAI@@QEAA?AVhand@@XZ proc EXPORT
?_NV_hasFocusedTarget@CombatClassAI@@QEAA?AVhand@@XZ endp

; CombatClassAI::hasFocusedTarget();
?hasFocusedTarget@CombatClassAI@@UEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+6*8]
?hasFocusedTarget@CombatClassAI@@UEAA?AVhand@@XZ endp

; CombatClassAI::tracerUpdate();
?tracerUpdate@CombatClassAI@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+7*8]
?tracerUpdate@CombatClassAI@@QEAAXXZ endp

; CombatClassAI::targetPathBlocked();
?targetPathBlocked@CombatClassAI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+8*8]
?targetPathBlocked@CombatClassAI@@QEBA_NXZ endp

; CombatClassAI::decisionState();
?decisionState@CombatClassAI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+9*8]
?decisionState@CombatClassAI@@QEAA_NXZ endp

?_NV_startupState@CombatClassAI@@QEAA_NXZ proc EXPORT
?_NV_startupState@CombatClassAI@@QEAA_NXZ endp

; CombatClassAI::startupState();
?startupState@CombatClassAI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+10*8]
?startupState@CombatClassAI@@UEAA_NXZ endp

; CombatClassAI::isInMeiDistance();
?isInMeiDistance@CombatClassAI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+11*8]
?isInMeiDistance@CombatClassAI@@QEAA_NXZ endp

; CombatClassAI::waitState();
?waitState@CombatClassAI@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+12*8]
?waitState@CombatClassAI@@QEAAXXZ endp

; CombatClassAI::circleState();
?circleState@CombatClassAI@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+13*8]
?circleState@CombatClassAI@@QEAAXXZ endp

; CombatClassAI::hesitateState();
?hesitateState@CombatClassAI@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+14*8]
?hesitateState@CombatClassAI@@QEAAXXZ endp

?_NV_attackState@CombatClassAI@@QEAA_NXZ proc EXPORT
?_NV_attackState@CombatClassAI@@QEAA_NXZ endp

; CombatClassAI::attackState();
?attackState@CombatClassAI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+15*8]
?attackState@CombatClassAI@@UEAA_NXZ endp

?_NV_blockState@CombatClassAI@@QEAA_N_N@Z proc EXPORT
?_NV_blockState@CombatClassAI@@QEAA_N_N@Z endp

; CombatClassAI::blockState(bool);
?blockState@CombatClassAI@@UEAA_N_N@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+16*8]
?blockState@CombatClassAI@@UEAA_N_N@Z endp

?_NV_informOfFreeAttackSlot@CombatClassAI@@QEAAXPEAVCharacter@@@Z proc EXPORT
?_NV_informOfFreeAttackSlot@CombatClassAI@@QEAAXPEAVCharacter@@@Z endp

; CombatClassAI::informOfFreeAttackSlot(class Character *);
?informOfFreeAttackSlot@CombatClassAI@@UEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+17*8]
?informOfFreeAttackSlot@CombatClassAI@@UEAAXPEAVCharacter@@@Z endp

?_NV_whoAttacksYouOrMe@CombatClassAI@@QEAA?AW4swordStateEnum@@PEAVCharacter@@MAEAM@Z proc EXPORT
?_NV_whoAttacksYouOrMe@CombatClassAI@@QEAA?AW4swordStateEnum@@PEAVCharacter@@MAEAM@Z endp

; CombatClassAI::whoAttacksYouOrMe(class Character *, float, float &);
?whoAttacksYouOrMe@CombatClassAI@@UEAA?AW4swordStateEnum@@PEAVCharacter@@MAEAM@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+18*8]
?whoAttacksYouOrMe@CombatClassAI@@UEAA?AW4swordStateEnum@@PEAVCharacter@@MAEAM@Z endp

; CombatClassAI::chooseAttackTarget();
?chooseAttackTarget@CombatClassAI@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_CombatClassAI_base+19*8]
?chooseAttackTarget@CombatClassAI@@QEAAPEAVCharacter@@XZ endp

?_NV_gotMoreImportantThingsToDoThanFightingYou@CombatClassAI@@QEAA_NPEAVCharacter@@@Z proc EXPORT
?_NV_gotMoreImportantThingsToDoThanFightingYou@CombatClassAI@@QEAA_NPEAVCharacter@@@Z endp

; CombatClassAI::gotMoreImportantThingsToDoThanFightingYou(class Character *);
?gotMoreImportantThingsToDoThanFightingYou@CombatClassAI@@UEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CombatClassAI_base+20*8]
?gotMoreImportantThingsToDoThanFightingYou@CombatClassAI@@UEAA_NPEAVCharacter@@@Z endp
