
?_NV_signalStart@Contract_Timed@@QEAA_NXZ proc EXPORT
?_NV_signalStart@Contract_Timed@@QEAA_NXZ endp

; Contract_Timed::signalStart();
?signalStart@Contract_Timed@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Contract_Timed_base+0*8]
?signalStart@Contract_Timed@@UEAA_NXZ endp

?_NV_signalEnd@Contract_Timed@@QEAA_NXZ proc EXPORT
?_NV_signalEnd@Contract_Timed@@QEAA_NXZ endp

; Contract_Timed::signalEnd();
?signalEnd@Contract_Timed@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Contract_Timed_base+1*8]
?signalEnd@Contract_Timed@@UEAA_NXZ endp

?_CONSTRUCTOR@Contract_Timed@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Contract_Timed@@QEAAPEAV1@XZ endp

; Contract_Timed::Contract_Timed();
??0Contract_Timed@@QEAA@XZ proc EXPORT
jmp function_pointers[_Contract_Timed_base+2*8]
??0Contract_Timed@@QEAA@XZ endp

?_DESTRUCTOR@Contract_Timed@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Contract_Timed@@QEAAXXZ endp

; Contract_Timed::~Contract_Timed();
??1Contract_Timed@@UEAA@XZ proc EXPORT
jmp function_pointers[_Contract_Timed_base+3*8]
??1Contract_Timed@@UEAA@XZ endp
