
?_NV_activateAndSetup@Contract_UntilOutOfDanger@@QEAAXXZ proc EXPORT
?_NV_activateAndSetup@Contract_UntilOutOfDanger@@QEAAXXZ endp

; Contract_UntilOutOfDanger::activateAndSetup();
?activateAndSetup@Contract_UntilOutOfDanger@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_UntilOutOfDanger_base+0*8]
?activateAndSetup@Contract_UntilOutOfDanger@@UEAAXXZ endp

?_NV_periodicUpdate@Contract_UntilOutOfDanger@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@Contract_UntilOutOfDanger@@QEAAXXZ endp

; Contract_UntilOutOfDanger::periodicUpdate();
?periodicUpdate@Contract_UntilOutOfDanger@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_UntilOutOfDanger_base+1*8]
?periodicUpdate@Contract_UntilOutOfDanger@@UEAAXXZ endp

?_NV_getDesiredTravelSpeed@Contract_UntilOutOfDanger@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
?_NV_getDesiredTravelSpeed@Contract_UntilOutOfDanger@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

; Contract_UntilOutOfDanger::getDesiredTravelSpeed(class Character *);
?getDesiredTravelSpeed@Contract_UntilOutOfDanger@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_UntilOutOfDanger_base+2*8]
?getDesiredTravelSpeed@Contract_UntilOutOfDanger@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

?_NV_signalEnd@Contract_UntilOutOfDanger@@QEAA_NXZ proc EXPORT
?_NV_signalEnd@Contract_UntilOutOfDanger@@QEAA_NXZ endp

; Contract_UntilOutOfDanger::signalEnd();
?signalEnd@Contract_UntilOutOfDanger@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Contract_UntilOutOfDanger_base+3*8]
?signalEnd@Contract_UntilOutOfDanger@@UEAA_NXZ endp

?_CONSTRUCTOR@Contract_UntilOutOfDanger@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Contract_UntilOutOfDanger@@QEAAPEAV1@XZ endp

; Contract_UntilOutOfDanger::Contract_UntilOutOfDanger();
??0Contract_UntilOutOfDanger@@QEAA@XZ proc EXPORT
jmp function_pointers[_Contract_UntilOutOfDanger_base+4*8]
??0Contract_UntilOutOfDanger@@QEAA@XZ endp

?_DESTRUCTOR@Contract_UntilOutOfDanger@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Contract_UntilOutOfDanger@@QEAAXXZ endp

; Contract_UntilOutOfDanger::~Contract_UntilOutOfDanger();
??1Contract_UntilOutOfDanger@@UEAA@XZ proc EXPORT
jmp function_pointers[_Contract_UntilOutOfDanger_base+5*8]
??1Contract_UntilOutOfDanger@@UEAA@XZ endp
