
?_NV_getDesiredTravelSpeed@Contract_UntilExSlave@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
?_NV_getDesiredTravelSpeed@Contract_UntilExSlave@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

; Contract_UntilExSlave::getDesiredTravelSpeed(class Character *);
?getDesiredTravelSpeed@Contract_UntilExSlave@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_UntilExSlave_base+0*8]
?getDesiredTravelSpeed@Contract_UntilExSlave@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

?_NV_signalEnd@Contract_UntilExSlave@@QEAA_NXZ proc EXPORT
?_NV_signalEnd@Contract_UntilExSlave@@QEAA_NXZ endp

; Contract_UntilExSlave::signalEnd();
?signalEnd@Contract_UntilExSlave@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Contract_UntilExSlave_base+1*8]
?signalEnd@Contract_UntilExSlave@@UEAA_NXZ endp

?_CONSTRUCTOR@Contract_UntilExSlave@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Contract_UntilExSlave@@QEAAPEAV1@XZ endp

; Contract_UntilExSlave::Contract_UntilExSlave();
??0Contract_UntilExSlave@@QEAA@XZ proc EXPORT
jmp function_pointers[_Contract_UntilExSlave_base+2*8]
??0Contract_UntilExSlave@@QEAA@XZ endp

?_DESTRUCTOR@Contract_UntilExSlave@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Contract_UntilExSlave@@QEAAXXZ endp

; Contract_UntilExSlave::~Contract_UntilExSlave();
??1Contract_UntilExSlave@@UEAA@XZ proc EXPORT
jmp function_pointers[_Contract_UntilExSlave_base+3*8]
??1Contract_UntilExSlave@@UEAA@XZ endp
