
?_NV_getDesiredTravelSpeed@Contract_HiredAlly@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
?_NV_getDesiredTravelSpeed@Contract_HiredAlly@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

; Contract_HiredAlly::getDesiredTravelSpeed(class Character *);
?getDesiredTravelSpeed@Contract_HiredAlly@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+0*8]
?getDesiredTravelSpeed@Contract_HiredAlly@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

?_NV_activateAndSetup@Contract_HiredAlly@@QEAAXXZ proc EXPORT
?_NV_activateAndSetup@Contract_HiredAlly@@QEAAXXZ endp

; Contract_HiredAlly::activateAndSetup();
?activateAndSetup@Contract_HiredAlly@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+1*8]
?activateAndSetup@Contract_HiredAlly@@UEAAXXZ endp

?_NV_periodicUpdate@Contract_HiredAlly@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@Contract_HiredAlly@@QEAAXXZ endp

; Contract_HiredAlly::periodicUpdate();
?periodicUpdate@Contract_HiredAlly@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+2*8]
?periodicUpdate@Contract_HiredAlly@@UEAAXXZ endp

?_NV_assessNeutral@Contract_HiredAlly@@QEAAXPEAVCharacter@@@Z proc EXPORT
?_NV_assessNeutral@Contract_HiredAlly@@QEAAXPEAVCharacter@@@Z endp

; Contract_HiredAlly::assessNeutral(class Character *);
?assessNeutral@Contract_HiredAlly@@UEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+3*8]
?assessNeutral@Contract_HiredAlly@@UEAAXPEAVCharacter@@@Z endp

?_NV_assessEnemy@Contract_HiredAlly@@QEAA_NPEAVCharacter@@@Z proc EXPORT
?_NV_assessEnemy@Contract_HiredAlly@@QEAA_NPEAVCharacter@@@Z endp

; Contract_HiredAlly::assessEnemy(class Character *);
?assessEnemy@Contract_HiredAlly@@UEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+4*8]
?assessEnemy@Contract_HiredAlly@@UEAA_NPEAVCharacter@@@Z endp

?_NV_notifyBetrayal@Contract_HiredAlly@@QEAA_NPEAVCharacter@@0@Z proc EXPORT
?_NV_notifyBetrayal@Contract_HiredAlly@@QEAA_NPEAVCharacter@@0@Z endp

; Contract_HiredAlly::notifyBetrayal(class Character *, class Character *);
?notifyBetrayal@Contract_HiredAlly@@UEAA_NPEAVCharacter@@0@Z proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+5*8]
?notifyBetrayal@Contract_HiredAlly@@UEAA_NPEAVCharacter@@0@Z endp

?_NV_endPackage@Contract_HiredAlly@@QEAAXXZ proc EXPORT
?_NV_endPackage@Contract_HiredAlly@@QEAAXXZ endp

; Contract_HiredAlly::endPackage();
?endPackage@Contract_HiredAlly@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+6*8]
?endPackage@Contract_HiredAlly@@UEAAXXZ endp

?_NV_showEndedMessage@Contract_HiredAlly@@QEAAXXZ proc EXPORT
?_NV_showEndedMessage@Contract_HiredAlly@@QEAAXXZ endp

; Contract_HiredAlly::showEndedMessage();
?showEndedMessage@Contract_HiredAlly@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+7*8]
?showEndedMessage@Contract_HiredAlly@@UEAAXXZ endp

?_NV_signalEnd@Contract_HiredAlly@@QEAA_NXZ proc EXPORT
?_NV_signalEnd@Contract_HiredAlly@@QEAA_NXZ endp

; Contract_HiredAlly::signalEnd();
?signalEnd@Contract_HiredAlly@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+8*8]
?signalEnd@Contract_HiredAlly@@UEAA_NXZ endp

?_NV_getGUIData@Contract_HiredAlly@@QEAA_NPEAVDatapanelGUI@@@Z proc EXPORT
?_NV_getGUIData@Contract_HiredAlly@@QEAA_NPEAVDatapanelGUI@@@Z endp

; Contract_HiredAlly::getGUIData(class DatapanelGUI *);
?getGUIData@Contract_HiredAlly@@UEAA_NPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+9*8]
?getGUIData@Contract_HiredAlly@@UEAA_NPEAVDatapanelGUI@@@Z endp

?_NV_wantsRenewButton@Contract_HiredAlly@@QEAA_NXZ proc EXPORT
?_NV_wantsRenewButton@Contract_HiredAlly@@QEAA_NXZ endp

; Contract_HiredAlly::wantsRenewButton();
?wantsRenewButton@Contract_HiredAlly@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+10*8]
?wantsRenewButton@Contract_HiredAlly@@UEAA_NXZ endp

?_NV_showManagementPanelCallback@Contract_HiredAlly@@QEAAXXZ proc EXPORT
?_NV_showManagementPanelCallback@Contract_HiredAlly@@QEAAXXZ endp

; Contract_HiredAlly::showManagementPanelCallback();
?showManagementPanelCallback@Contract_HiredAlly@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+11*8]
?showManagementPanelCallback@Contract_HiredAlly@@UEAAXXZ endp

?_CONSTRUCTOR@Contract_HiredAlly@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Contract_HiredAlly@@QEAAPEAV1@XZ endp

; Contract_HiredAlly::Contract_HiredAlly();
??0Contract_HiredAlly@@QEAA@XZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+12*8]
??0Contract_HiredAlly@@QEAA@XZ endp

?_DESTRUCTOR@Contract_HiredAlly@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Contract_HiredAlly@@QEAAXXZ endp

; Contract_HiredAlly::~Contract_HiredAlly();
??1Contract_HiredAlly@@UEAA@XZ proc EXPORT
jmp function_pointers[_Contract_HiredAlly_base+13*8]
??1Contract_HiredAlly@@UEAA@XZ endp
