
?_NV_getGUIData@Contract_DefendPlayerBase@@QEAA_NPEAVDatapanelGUI@@@Z proc EXPORT
?_NV_getGUIData@Contract_DefendPlayerBase@@QEAA_NPEAVDatapanelGUI@@@Z endp

; Contract_DefendPlayerBase::getGUIData(class DatapanelGUI *);
?getGUIData@Contract_DefendPlayerBase@@UEAA_NPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+0*8]
?getGUIData@Contract_DefendPlayerBase@@UEAA_NPEAVDatapanelGUI@@@Z endp

?_NV_getMyTarget@Contract_DefendPlayerBase@@QEAA?AVTargetInfo@@PEAVCharacter@@@Z proc EXPORT
?_NV_getMyTarget@Contract_DefendPlayerBase@@QEAA?AVTargetInfo@@PEAVCharacter@@@Z endp

; Contract_DefendPlayerBase::getMyTarget(class Character *);
?getMyTarget@Contract_DefendPlayerBase@@UEAA?AVTargetInfo@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+1*8]
?getMyTarget@Contract_DefendPlayerBase@@UEAA?AVTargetInfo@@PEAVCharacter@@@Z endp

?_NV_getDesiredTravelSpeed@Contract_DefendPlayerBase@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
?_NV_getDesiredTravelSpeed@Contract_DefendPlayerBase@@QEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

; Contract_DefendPlayerBase::getDesiredTravelSpeed(class Character *);
?getDesiredTravelSpeed@Contract_DefendPlayerBase@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+2*8]
?getDesiredTravelSpeed@Contract_DefendPlayerBase@@UEAA?AW4MoveSpeed@@PEAVCharacter@@@Z endp

?_NV_activateAndSetup@Contract_DefendPlayerBase@@QEAAXXZ proc EXPORT
?_NV_activateAndSetup@Contract_DefendPlayerBase@@QEAAXXZ endp

; Contract_DefendPlayerBase::activateAndSetup();
?activateAndSetup@Contract_DefendPlayerBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+3*8]
?activateAndSetup@Contract_DefendPlayerBase@@UEAAXXZ endp

?_NV_periodicUpdate@Contract_DefendPlayerBase@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@Contract_DefendPlayerBase@@QEAAXXZ endp

; Contract_DefendPlayerBase::periodicUpdate();
?periodicUpdate@Contract_DefendPlayerBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+4*8]
?periodicUpdate@Contract_DefendPlayerBase@@UEAAXXZ endp

?_NV_assessNeutral@Contract_DefendPlayerBase@@QEAAXPEAVCharacter@@@Z proc EXPORT
?_NV_assessNeutral@Contract_DefendPlayerBase@@QEAAXPEAVCharacter@@@Z endp

; Contract_DefendPlayerBase::assessNeutral(class Character *);
?assessNeutral@Contract_DefendPlayerBase@@UEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+5*8]
?assessNeutral@Contract_DefendPlayerBase@@UEAAXPEAVCharacter@@@Z endp

?_CONSTRUCTOR@Contract_DefendPlayerBase@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Contract_DefendPlayerBase@@QEAAPEAV1@XZ endp

; Contract_DefendPlayerBase::Contract_DefendPlayerBase();
??0Contract_DefendPlayerBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+6*8]
??0Contract_DefendPlayerBase@@QEAA@XZ endp

?_DESTRUCTOR@Contract_DefendPlayerBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Contract_DefendPlayerBase@@QEAAXXZ endp

; Contract_DefendPlayerBase::~Contract_DefendPlayerBase();
??1Contract_DefendPlayerBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_Contract_DefendPlayerBase_base+7*8]
??1Contract_DefendPlayerBase@@UEAA@XZ endp
