
?_CONSTRUCTOR@Formation@@QEAAPEAV1@PEAVRootObject@@@Z proc EXPORT
?_CONSTRUCTOR@Formation@@QEAAPEAV1@PEAVRootObject@@@Z endp

; Formation::Formation(class RootObject *);
??0Formation@@QEAA@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Formation_base+0*8]
??0Formation@@QEAA@PEAVRootObject@@@Z endp

?_NV_addToFormation@Formation@@QEAAHAEBVhand@@@Z proc EXPORT
?_NV_addToFormation@Formation@@QEAAHAEBVhand@@@Z endp

; Formation::addToFormation(const class hand &);
?addToFormation@Formation@@UEAAHAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Formation_base+1*8]
?addToFormation@Formation@@UEAAHAEBVhand@@@Z endp

?_NV_removeFromFormation@Formation@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_removeFromFormation@Formation@@QEAAXAEBVhand@@@Z endp

; Formation::removeFromFormation(const class hand &);
?removeFromFormation@Formation@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Formation_base+2*8]
?removeFromFormation@Formation@@UEAAXAEBVhand@@@Z endp

?_NV_getFormationPos@Formation@@QEAA?AVVector3@Ogre@@HM@Z proc EXPORT
?_NV_getFormationPos@Formation@@QEAA?AVVector3@Ogre@@HM@Z endp

; Formation::getFormationPos(int, float);
?getFormationPos@Formation@@UEAA?AVVector3@Ogre@@HM@Z proc EXPORT
jmp function_pointers[_Formation_base+3*8]
?getFormationPos@Formation@@UEAA?AVVector3@Ogre@@HM@Z endp

?_DESTRUCTOR@Formation@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Formation@@QEAAXXZ endp

; Formation::~Formation();
??1Formation@@QEAA@XZ proc EXPORT
jmp function_pointers[_Formation_base+4*8]
??1Formation@@QEAA@XZ endp
