
; GameDataScoredList::setupFromData(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum itemType);
?setupFromData@GameDataScoredList@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_GameDataScoredList_base+0*8]
?setupFromData@GameDataScoredList@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@@Z endp

?_CONSTRUCTOR@GameDataScoredList@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataScoredList@@QEAAPEAV1@XZ endp

; GameDataScoredList::GameDataScoredList();
??0GameDataScoredList@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataScoredList_base+1*8]
??0GameDataScoredList@@QEAA@XZ endp

?_DESTRUCTOR@GameDataScoredList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataScoredList@@QEAAXXZ endp

; GameDataScoredList::~GameDataScoredList();
??1GameDataScoredList@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataScoredList_base+2*8]
??1GameDataScoredList@@QEAA@XZ endp
