
?_CONSTRUCTOR@GunClass@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@GunClass@@QEAAPEAV1@PEAVGameData@@@Z endp

; GunClass::GunClass(class GameData *);
??0GunClass@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+0*8]
??0GunClass@@QEAA@PEAVGameData@@@Z endp

?_DESTRUCTOR@GunClass@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GunClass@@QEAAXXZ endp

; GunClass::~GunClass();
??1GunClass@@UEAA@XZ proc EXPORT
jmp function_pointers[_GunClass_base+1*8]
??1GunClass@@UEAA@XZ endp

?_NV_setVisible@GunClass@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@GunClass@@QEAAX_N@Z endp

; GunClass::setVisible(bool);
?setVisible@GunClass@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_GunClass_base+2*8]
?setVisible@GunClass@@UEAAX_N@Z endp

?_NV_update@GunClass@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_update@GunClass@@QEAAXAEBVVector3@Ogre@@@Z endp

; GunClass::update(const class Ogre::Vector3 &);
?update@GunClass@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+3*8]
?update@GunClass@@UEAAXAEBVVector3@Ogre@@@Z endp

; GunClass::reloadAmmo(float);
?reloadAmmo@GunClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_GunClass_base+4*8]
?reloadAmmo@GunClass@@QEAAXM@Z endp

; GunClass::shoot(class Character *, class RootObject *, enum StatsEnumerated, const class Ogre::Vector3 &);
?shoot@GunClass@@QEAAXPEAVCharacter@@PEAVRootObject@@W4StatsEnumerated@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+5*8]
?shoot@GunClass@@QEAAXPEAVCharacter@@PEAVRootObject@@W4StatsEnumerated@@AEBVVector3@Ogre@@@Z endp

?_NV_createPhysical@GunClass@@QEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_createPhysical@GunClass@@QEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GunClass::createPhysical(class Ogre::SceneNode *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createPhysical@GunClass@@UEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+6*8]
?createPhysical@GunClass@@UEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_destroyPhysical@GunClass@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@GunClass@@QEAAXXZ endp

; GunClass::destroyPhysical();
?destroyPhysical@GunClass@@UEAAXXZ proc EXPORT
jmp function_pointers[_GunClass_base+7*8]
?destroyPhysical@GunClass@@UEAAXXZ endp

?_NV_aimAt@GunClass@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_aimAt@GunClass@@QEAAXAEBVVector3@Ogre@@@Z endp

; GunClass::aimAt(const class Ogre::Vector3 &);
?aimAt@GunClass@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+8*8]
?aimAt@GunClass@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_isAnimationReadyToShoot@GunClass@@QEAA_NXZ proc EXPORT
?_NV_isAnimationReadyToShoot@GunClass@@QEAA_NXZ endp

; GunClass::isAnimationReadyToShoot();
?isAnimationReadyToShoot@GunClass@@UEAA_NXZ proc EXPORT
jmp function_pointers[_GunClass_base+9*8]
?isAnimationReadyToShoot@GunClass@@UEAA_NXZ endp

?_NV_setAnimationReadyToShoot@GunClass@@QEAAX_N@Z proc EXPORT
?_NV_setAnimationReadyToShoot@GunClass@@QEAAX_N@Z endp

; GunClass::setAnimationReadyToShoot(bool);
?setAnimationReadyToShoot@GunClass@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_GunClass_base+10*8]
?setAnimationReadyToShoot@GunClass@@UEAAX_N@Z endp

?_NV_getBarrelPos@GunClass@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getBarrelPos@GunClass@@QEAA?AVVector3@Ogre@@XZ endp

; GunClass::getBarrelPos();
?getBarrelPos@GunClass@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_GunClass_base+11*8]
?getBarrelPos@GunClass@@UEAA?AVVector3@Ogre@@XZ endp

?_NV_getBarrelPosForTrace@GunClass@@QEAA?AVVector3@Ogre@@M@Z proc EXPORT
?_NV_getBarrelPosForTrace@GunClass@@QEAA?AVVector3@Ogre@@M@Z endp

; GunClass::getBarrelPosForTrace(float);
?getBarrelPosForTrace@GunClass@@UEAA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_GunClass_base+12*8]
?getBarrelPosForTrace@GunClass@@UEAA?AVVector3@Ogre@@M@Z endp

?_NV_didThisTraceHitOurMountedBuilding@GunClass@@QEAA_NAEAVphysHit@@@Z proc EXPORT
?_NV_didThisTraceHitOurMountedBuilding@GunClass@@QEAA_NAEAVphysHit@@@Z endp

; GunClass::didThisTraceHitOurMountedBuilding(class physHit &);
?didThisTraceHitOurMountedBuilding@GunClass@@UEAA_NAEAVphysHit@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+13*8]
?didThisTraceHitOurMountedBuilding@GunClass@@UEAA_NAEAVphysHit@@@Z endp

; GunClass::getRelativeBarrelPos();
?getRelativeBarrelPos@GunClass@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_GunClass_base+14*8]
?getRelativeBarrelPos@GunClass@@QEBA?AVVector3@Ogre@@XZ endp

?_NV_getAimDir@GunClass@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getAimDir@GunClass@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; GunClass::getAimDir(const class Ogre::Vector3 &);
?getAimDir@GunClass@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_GunClass_base+15*8]
?getAimDir@GunClass@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

; GunClass::trace(const class Ogre::Vector3 &, bool);
?trace@GunClass@@QEAAAEAVphysHit@@AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_GunClass_base+16*8]
?trace@GunClass@@QEAAAEAVphysHit@@AEBVVector3@Ogre@@_N@Z endp

; GunClass::trace2(const class Ogre::Vector3 &, bool);
?trace2@GunClass@@QEAAAEAVphysHit@@AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_GunClass_base+17*8]
?trace2@GunClass@@QEAAAEAVphysHit@@AEBVVector3@Ogre@@_N@Z endp

?_NV_getGUIData@GunClass@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@GunClass@@QEAAXPEAVDatapanelGUI@@H@Z endp

; GunClass::getGUIData(class DatapanelGUI *, int);
?getGUIData@GunClass@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_GunClass_base+18*8]
?getGUIData@GunClass@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_setStateForGUI@GunClass@@QEAAXM@Z proc EXPORT
?_NV_setStateForGUI@GunClass@@QEAAXM@Z endp

; GunClass::setStateForGUI(float);
?setStateForGUI@GunClass@@UEAAXM@Z proc EXPORT
jmp function_pointers[_GunClass_base+19*8]
?setStateForGUI@GunClass@@UEAAXM@Z endp

?_NV_setSkillForGUI@GunClass@@QEAAXMAEBVhand@@@Z proc EXPORT
?_NV_setSkillForGUI@GunClass@@QEAAXMAEBVhand@@@Z endp

; GunClass::setSkillForGUI(float, const class hand &);
?setSkillForGUI@GunClass@@UEAAXMAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+20*8]
?setSkillForGUI@GunClass@@UEAAXMAEBVhand@@@Z endp

; GunClass::calculateHeightBonus(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?calculateHeightBonus@GunClass@@QEBAMAEBVVector3@Ogre@@0@Z proc EXPORT
jmp function_pointers[_GunClass_base+21*8]
?calculateHeightBonus@GunClass@@QEBAMAEBVVector3@Ogre@@0@Z endp

?_NV_calculateWallBonusMult@GunClass@@QEAAMXZ proc EXPORT
?_NV_calculateWallBonusMult@GunClass@@QEAAMXZ endp

; GunClass::calculateWallBonusMult();
?calculateWallBonusMult@GunClass@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClass_base+22*8]
?calculateWallBonusMult@GunClass@@UEAAMXZ endp

?_NV_getPowerEfficiencyMult@GunClass@@QEAAMXZ proc EXPORT
?_NV_getPowerEfficiencyMult@GunClass@@QEAAMXZ endp

; GunClass::getPowerEfficiencyMult();
?getPowerEfficiencyMult@GunClass@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClass_base+23*8]
?getPowerEfficiencyMult@GunClass@@UEAAMXZ endp

; GunClass::isReloading();
?isReloading@GunClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_GunClass_base+24*8]
?isReloading@GunClass@@QEBA_NXZ endp

; GunClass::isActive();
?isActive@GunClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_GunClass_base+25*8]
?isActive@GunClass@@QEBA_NXZ endp

; GunClass::calculateAccuracyDeviationAngle(float);
?calculateAccuracyDeviationAngle@GunClass@@QEAAMM@Z proc EXPORT
jmp function_pointers[_GunClass_base+26*8]
?calculateAccuracyDeviationAngle@GunClass@@QEAAMM@Z endp

; GunClass::calculateReloadTime(float);
?calculateReloadTime@GunClass@@QEAAMM@Z proc EXPORT
jmp function_pointers[_GunClass_base+27*8]
?calculateReloadTime@GunClass@@QEAAMM@Z endp

?_NV_serialise@GunClass@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_serialise@GunClass@@QEAAXPEAVGameData@@@Z endp

; GunClass::serialise(class GameData *);
?serialise@GunClass@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+28*8]
?serialise@GunClass@@UEAAXPEAVGameData@@@Z endp

?_NV_loadFromSerialise@GunClass@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_loadFromSerialise@GunClass@@QEAAXPEAVGameData@@@Z endp

; GunClass::loadFromSerialise(class GameData *);
?loadFromSerialise@GunClass@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+29*8]
?loadFromSerialise@GunClass@@UEAAXPEAVGameData@@@Z endp

; GunClass::getARandomDamage();
?getARandomDamage@GunClass@@QEAAMXZ proc EXPORT
jmp function_pointers[_GunClass_base+30*8]
?getARandomDamage@GunClass@@QEAAMXZ endp

?_NV_isPersonalCrossbow@GunClass@@QEAAPEAVGunClassPersonal@@XZ proc EXPORT
?_NV_isPersonalCrossbow@GunClass@@QEAAPEAVGunClassPersonal@@XZ endp

; GunClass::isPersonalCrossbow();
?isPersonalCrossbow@GunClass@@UEAAPEAVGunClassPersonal@@XZ proc EXPORT
jmp function_pointers[_GunClass_base+31*8]
?isPersonalCrossbow@GunClass@@UEAAPEAVGunClassPersonal@@XZ endp

?_NV_isTurret@GunClass@@QEAAPEAVGunClassTurret@@XZ proc EXPORT
?_NV_isTurret@GunClass@@QEAAPEAVGunClassTurret@@XZ endp

; GunClass::isTurret();
?isTurret@GunClass@@UEAAPEAVGunClassTurret@@XZ proc EXPORT
jmp function_pointers[_GunClass_base+32*8]
?isTurret@GunClass@@UEAAPEAVGunClassTurret@@XZ endp

; GunClass::getReloadStateForGUI(bool);
?getReloadStateForGUI@GunClass@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_GunClass_base+33*8]
?getReloadStateForGUI@GunClass@@QEBAM_N@Z endp

?_NV_setCharacter@GunClass@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setCharacter@GunClass@@QEAAXAEBVhand@@@Z endp

; GunClass::setCharacter(const class hand &);
?setCharacter@GunClass@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GunClass_base+34*8]
?setCharacter@GunClass@@UEAAXAEBVhand@@@Z endp

; GunClass::reactivationCheck();
?reactivationCheck@GunClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_GunClass_base+35*8]
?reactivationCheck@GunClass@@QEAAXXZ endp

; GunClass::loadEntityCallback(class Ogre::SharedPtr<Ogre::Resource>, void *);
?loadEntityCallback@GunClass@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_GunClass_base+36*8]
?loadEntityCallback@GunClass@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

?_NV_onEntitiesLoaded@GunClass@@QEAAXXZ proc EXPORT
?_NV_onEntitiesLoaded@GunClass@@QEAAXXZ endp

; GunClass::onEntitiesLoaded();
?onEntitiesLoaded@GunClass@@UEAAXXZ proc EXPORT
jmp function_pointers[_GunClass_base+37*8]
?onEntitiesLoaded@GunClass@@UEAAXXZ endp

; GunClass::updatePartVisibilities();
?updatePartVisibilities@GunClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_GunClass_base+38*8]
?updatePartVisibilities@GunClass@@QEAAXXZ endp
