
?_CONSTRUCTOR@GunClassTurret@@QEAAPEAV1@PEAVGameData@@PEAVTurretBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@GunClassTurret@@QEAAPEAV1@PEAVGameData@@PEAVTurretBuilding@@@Z endp

; GunClassTurret::GunClassTurret(class GameData *, class TurretBuilding *);
??0GunClassTurret@@QEAA@PEAVGameData@@PEAVTurretBuilding@@@Z proc EXPORT
jmp function_pointers[_GunClassTurret_base+0*8]
??0GunClassTurret@@QEAA@PEAVGameData@@PEAVTurretBuilding@@@Z endp

?_NV_getGUIData@GunClassTurret@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@GunClassTurret@@QEAAXPEAVDatapanelGUI@@H@Z endp

; GunClassTurret::getGUIData(class DatapanelGUI *, int);
?getGUIData@GunClassTurret@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_GunClassTurret_base+1*8]
?getGUIData@GunClassTurret@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_aimAt@GunClassTurret@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_aimAt@GunClassTurret@@QEAAXAEBVVector3@Ogre@@@Z endp

; GunClassTurret::aimAt(const class Ogre::Vector3 &);
?aimAt@GunClassTurret@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GunClassTurret_base+2*8]
?aimAt@GunClassTurret@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_scoreTarget@GunClassTurret@@QEAAMPEAVCharacter@@0@Z proc EXPORT
?_NV_scoreTarget@GunClassTurret@@QEAAMPEAVCharacter@@0@Z endp

; GunClassTurret::scoreTarget(class Character *, class Character *);
?scoreTarget@GunClassTurret@@UEAAMPEAVCharacter@@0@Z proc EXPORT
jmp function_pointers[_GunClassTurret_base+3*8]
?scoreTarget@GunClassTurret@@UEAAMPEAVCharacter@@0@Z endp

?_NV_getAimCloseness@GunClassTurret@@QEAAMXZ proc EXPORT
?_NV_getAimCloseness@GunClassTurret@@QEAAMXZ endp

; GunClassTurret::getAimCloseness();
?getAimCloseness@GunClassTurret@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+4*8]
?getAimCloseness@GunClassTurret@@UEAAMXZ endp

?_NV_getPowerEfficiencyMult@GunClassTurret@@QEAAMXZ proc EXPORT
?_NV_getPowerEfficiencyMult@GunClassTurret@@QEAAMXZ endp

; GunClassTurret::getPowerEfficiencyMult();
?getPowerEfficiencyMult@GunClassTurret@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+5*8]
?getPowerEfficiencyMult@GunClassTurret@@UEAAMXZ endp

?_NV_calculateWallBonusMult@GunClassTurret@@QEAAMXZ proc EXPORT
?_NV_calculateWallBonusMult@GunClassTurret@@QEAAMXZ endp

; GunClassTurret::calculateWallBonusMult();
?calculateWallBonusMult@GunClassTurret@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+6*8]
?calculateWallBonusMult@GunClassTurret@@UEAAMXZ endp

?_NV_didThisTraceHitOurMountedBuilding@GunClassTurret@@QEAA_NAEAVphysHit@@@Z proc EXPORT
?_NV_didThisTraceHitOurMountedBuilding@GunClassTurret@@QEAA_NAEAVphysHit@@@Z endp

; GunClassTurret::didThisTraceHitOurMountedBuilding(class physHit &);
?didThisTraceHitOurMountedBuilding@GunClassTurret@@UEAA_NAEAVphysHit@@@Z proc EXPORT
jmp function_pointers[_GunClassTurret_base+7*8]
?didThisTraceHitOurMountedBuilding@GunClassTurret@@UEAA_NAEAVphysHit@@@Z endp

?_NV_isOutOfPower@GunClassTurret@@QEBA_NXZ proc EXPORT
?_NV_isOutOfPower@GunClassTurret@@QEBA_NXZ endp

; GunClassTurret::isOutOfPower();
?isOutOfPower@GunClassTurret@@UEBA_NXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+8*8]
?isOutOfPower@GunClassTurret@@UEBA_NXZ endp

?_NV_getDamageMin@GunClassTurret@@QEAAHXZ proc EXPORT
?_NV_getDamageMin@GunClassTurret@@QEAAHXZ endp

; GunClassTurret::getDamageMin();
?getDamageMin@GunClassTurret@@UEAAHXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+9*8]
?getDamageMin@GunClassTurret@@UEAAHXZ endp

?_NV_getDamageMax@GunClassTurret@@QEAAHXZ proc EXPORT
?_NV_getDamageMax@GunClassTurret@@QEAAHXZ endp

; GunClassTurret::getDamageMax();
?getDamageMax@GunClassTurret@@UEAAHXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+10*8]
?getDamageMax@GunClassTurret@@UEAAHXZ endp

?_NV_getAudioObject@GunClassTurret@@QEBA_KXZ proc EXPORT
?_NV_getAudioObject@GunClassTurret@@QEBA_KXZ endp

; GunClassTurret::getAudioObject();
?getAudioObject@GunClassTurret@@UEBA_KXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+11*8]
?getAudioObject@GunClassTurret@@UEBA_KXZ endp

?_NV_createPhysical@GunClassTurret@@QEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_createPhysical@GunClassTurret@@QEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GunClassTurret::createPhysical(class Ogre::SceneNode *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createPhysical@GunClassTurret@@UEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GunClassTurret_base+12*8]
?createPhysical@GunClassTurret@@UEAA_NPEAVSceneNode@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_destroyPhysical@GunClassTurret@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@GunClassTurret@@QEAAXXZ endp

; GunClassTurret::destroyPhysical();
?destroyPhysical@GunClassTurret@@UEAAXXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+13*8]
?destroyPhysical@GunClassTurret@@UEAAXXZ endp

; GunClassTurret::clearEntitesPtr();
?clearEntitesPtr@GunClassTurret@@QEAAXXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+14*8]
?clearEntitesPtr@GunClassTurret@@QEAAXXZ endp

?_NV_isTurret@GunClassTurret@@QEAAPEAV1@XZ proc EXPORT
?_NV_isTurret@GunClassTurret@@QEAAPEAV1@XZ endp

; GunClassTurret::isTurret();
?isTurret@GunClassTurret@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+15*8]
?isTurret@GunClassTurret@@UEAAPEAV1@XZ endp

?_NV_onEntitiesLoaded@GunClassTurret@@QEAAXXZ proc EXPORT
?_NV_onEntitiesLoaded@GunClassTurret@@QEAAXXZ endp

; GunClassTurret::onEntitiesLoaded();
?onEntitiesLoaded@GunClassTurret@@UEAAXXZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+16*8]
?onEntitiesLoaded@GunClassTurret@@UEAAXXZ endp

?_NV_getParentNode@GunClassTurret@@QEAAPEAVSceneNode@Ogre@@XZ proc EXPORT
?_NV_getParentNode@GunClassTurret@@QEAAPEAVSceneNode@Ogre@@XZ endp

; GunClassTurret::getParentNode();
?getParentNode@GunClassTurret@@UEAAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+17*8]
?getParentNode@GunClassTurret@@UEAAPEAVSceneNode@Ogre@@XZ endp

?_DESTRUCTOR@GunClassTurret@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GunClassTurret@@QEAAXXZ endp

; GunClassTurret::~GunClassTurret();
??1GunClassTurret@@UEAA@XZ proc EXPORT
jmp function_pointers[_GunClassTurret_base+18*8]
??1GunClassTurret@@UEAA@XZ endp
