
?_CONSTRUCTOR@GunClassPersonal@@QEAAPEAV1@PEAVGameData@@M@Z proc EXPORT
?_CONSTRUCTOR@GunClassPersonal@@QEAAPEAV1@PEAVGameData@@M@Z endp

; GunClassPersonal::GunClassPersonal(class GameData *, float);
??0GunClassPersonal@@QEAA@PEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_GunClassPersonal_base+0*8]
??0GunClassPersonal@@QEAA@PEAVGameData@@M@Z endp

?_NV_scoreTarget@GunClassPersonal@@QEAAMPEAVCharacter@@0@Z proc EXPORT
?_NV_scoreTarget@GunClassPersonal@@QEAAMPEAVCharacter@@0@Z endp

; GunClassPersonal::scoreTarget(class Character *, class Character *);
?scoreTarget@GunClassPersonal@@UEAAMPEAVCharacter@@0@Z proc EXPORT
jmp function_pointers[_GunClassPersonal_base+1*8]
?scoreTarget@GunClassPersonal@@UEAAMPEAVCharacter@@0@Z endp

?_NV_isAnimationReadyToShoot@GunClassPersonal@@QEAA_NXZ proc EXPORT
?_NV_isAnimationReadyToShoot@GunClassPersonal@@QEAA_NXZ endp

; GunClassPersonal::isAnimationReadyToShoot();
?isAnimationReadyToShoot@GunClassPersonal@@UEAA_NXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+2*8]
?isAnimationReadyToShoot@GunClassPersonal@@UEAA_NXZ endp

?_NV_setAnimationReadyToShoot@GunClassPersonal@@QEAAX_N@Z proc EXPORT
?_NV_setAnimationReadyToShoot@GunClassPersonal@@QEAAX_N@Z endp

; GunClassPersonal::setAnimationReadyToShoot(bool);
?setAnimationReadyToShoot@GunClassPersonal@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_GunClassPersonal_base+3*8]
?setAnimationReadyToShoot@GunClassPersonal@@UEAAX_N@Z endp

?_NV_getAimCloseness@GunClassPersonal@@QEAAMXZ proc EXPORT
?_NV_getAimCloseness@GunClassPersonal@@QEAAMXZ endp

; GunClassPersonal::getAimCloseness();
?getAimCloseness@GunClassPersonal@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+4*8]
?getAimCloseness@GunClassPersonal@@UEAAMXZ endp

?_NV_getPowerEfficiencyMult@GunClassPersonal@@QEAAMXZ proc EXPORT
?_NV_getPowerEfficiencyMult@GunClassPersonal@@QEAAMXZ endp

; GunClassPersonal::getPowerEfficiencyMult();
?getPowerEfficiencyMult@GunClassPersonal@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+5*8]
?getPowerEfficiencyMult@GunClassPersonal@@UEAAMXZ endp

?_NV_calculateWallBonusMult@GunClassPersonal@@QEAAMXZ proc EXPORT
?_NV_calculateWallBonusMult@GunClassPersonal@@QEAAMXZ endp

; GunClassPersonal::calculateWallBonusMult();
?calculateWallBonusMult@GunClassPersonal@@UEAAMXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+6*8]
?calculateWallBonusMult@GunClassPersonal@@UEAAMXZ endp

?_NV_didThisTraceHitOurMountedBuilding@GunClassPersonal@@QEAA_NAEAVphysHit@@@Z proc EXPORT
?_NV_didThisTraceHitOurMountedBuilding@GunClassPersonal@@QEAA_NAEAVphysHit@@@Z endp

; GunClassPersonal::didThisTraceHitOurMountedBuilding(class physHit &);
?didThisTraceHitOurMountedBuilding@GunClassPersonal@@UEAA_NAEAVphysHit@@@Z proc EXPORT
jmp function_pointers[_GunClassPersonal_base+7*8]
?didThisTraceHitOurMountedBuilding@GunClassPersonal@@UEAA_NAEAVphysHit@@@Z endp

?_NV_getDamageMin@GunClassPersonal@@QEAAHXZ proc EXPORT
?_NV_getDamageMin@GunClassPersonal@@QEAAHXZ endp

; GunClassPersonal::getDamageMin();
?getDamageMin@GunClassPersonal@@UEAAHXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+8*8]
?getDamageMin@GunClassPersonal@@UEAAHXZ endp

?_NV_getDamageMax@GunClassPersonal@@QEAAHXZ proc EXPORT
?_NV_getDamageMax@GunClassPersonal@@QEAAHXZ endp

; GunClassPersonal::getDamageMax();
?getDamageMax@GunClassPersonal@@UEAAHXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+9*8]
?getDamageMax@GunClassPersonal@@UEAAHXZ endp

?_NV_getAudioObject@GunClassPersonal@@QEBA_KXZ proc EXPORT
?_NV_getAudioObject@GunClassPersonal@@QEBA_KXZ endp

; GunClassPersonal::getAudioObject();
?getAudioObject@GunClassPersonal@@UEBA_KXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+10*8]
?getAudioObject@GunClassPersonal@@UEBA_KXZ endp

?_NV_isPersonalCrossbow@GunClassPersonal@@QEAAPEAV1@XZ proc EXPORT
?_NV_isPersonalCrossbow@GunClassPersonal@@QEAAPEAV1@XZ endp

; GunClassPersonal::isPersonalCrossbow();
?isPersonalCrossbow@GunClassPersonal@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+11*8]
?isPersonalCrossbow@GunClassPersonal@@UEAAPEAV1@XZ endp

; GunClassPersonal::clearEntitesPtr();
?clearEntitesPtr@GunClassPersonal@@QEAAXXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+12*8]
?clearEntitesPtr@GunClassPersonal@@QEAAXXZ endp

?_NV_getAimDir@GunClassPersonal@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getAimDir@GunClassPersonal@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; GunClassPersonal::getAimDir(const class Ogre::Vector3 &);
?getAimDir@GunClassPersonal@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_GunClassPersonal_base+13*8]
?getAimDir@GunClassPersonal@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_setCharacter@GunClassPersonal@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setCharacter@GunClassPersonal@@QEAAXAEBVhand@@@Z endp

; GunClassPersonal::setCharacter(const class hand &);
?setCharacter@GunClassPersonal@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GunClassPersonal_base+14*8]
?setCharacter@GunClassPersonal@@UEAAXAEBVhand@@@Z endp

?_NV_onEntitiesLoaded@GunClassPersonal@@QEAAXXZ proc EXPORT
?_NV_onEntitiesLoaded@GunClassPersonal@@QEAAXXZ endp

; GunClassPersonal::onEntitiesLoaded();
?onEntitiesLoaded@GunClassPersonal@@UEAAXXZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+15*8]
?onEntitiesLoaded@GunClassPersonal@@UEAAXXZ endp

?_NV_getParentNode@GunClassPersonal@@QEAAPEAVSceneNode@Ogre@@XZ proc EXPORT
?_NV_getParentNode@GunClassPersonal@@QEAAPEAVSceneNode@Ogre@@XZ endp

; GunClassPersonal::getParentNode();
?getParentNode@GunClassPersonal@@UEAAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+16*8]
?getParentNode@GunClassPersonal@@UEAAPEAVSceneNode@Ogre@@XZ endp

?_DESTRUCTOR@GunClassPersonal@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GunClassPersonal@@QEAAXXZ endp

; GunClassPersonal::~GunClassPersonal();
??1GunClassPersonal@@UEAA@XZ proc EXPORT
jmp function_pointers[_GunClassPersonal_base+17*8]
??1GunClassPersonal@@UEAA@XZ endp
