
?_CONSTRUCTOR@HandleListBase@@QEAAPEAV1@I@Z proc EXPORT
?_CONSTRUCTOR@HandleListBase@@QEAAPEAV1@I@Z endp

; HandleListBase::HandleListBase(unsigned int);
??0HandleListBase@@QEAA@I@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+0*8]
??0HandleListBase@@QEAA@I@Z endp

?_DESTRUCTOR@HandleListBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@HandleListBase@@QEAAXXZ endp

; HandleListBase::~HandleListBase();
??1HandleListBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_HandleListBase_base+1*8]
??1HandleListBase@@UEAA@XZ endp

?_NV_clearToZero@HandleListBase@@QEAAXXZ proc EXPORT
?_NV_clearToZero@HandleListBase@@QEAAXXZ endp

; HandleListBase::clearToZero();
?clearToZero@HandleListBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_HandleListBase_base+2*8]
?clearToZero@HandleListBase@@UEAAXXZ endp

?_NV_get@HandleListBase@@QEBAPEAVRootObjectBase@@AEBVhand@@@Z proc EXPORT
?_NV_get@HandleListBase@@QEBAPEAVRootObjectBase@@AEBVhand@@@Z endp

; HandleListBase::get(const class hand &);
?get@HandleListBase@@UEBAPEAVRootObjectBase@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+3*8]
?get@HandleListBase@@UEBAPEAVRootObjectBase@@AEBVhand@@@Z endp

?_NV_isUnloadedNotDead@HandleListBase@@QEBA_NAEBVhand@@@Z proc EXPORT
?_NV_isUnloadedNotDead@HandleListBase@@QEBA_NAEBVhand@@@Z endp

; HandleListBase::isUnloadedNotDead(const class hand &);
?isUnloadedNotDead@HandleListBase@@UEBA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+4*8]
?isUnloadedNotDead@HandleListBase@@UEBA_NAEBVhand@@@Z endp

?_NV_addExisting@HandleListBase@@QEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z proc EXPORT
?_NV_addExisting@HandleListBase@@QEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z endp

; HandleListBase::addExisting(class RootObjectBase *, const class hand &);
?addExisting@HandleListBase@@UEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+5*8]
?addExisting@HandleListBase@@UEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z endp

?_NV_setUnloaded@HandleListBase@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setUnloaded@HandleListBase@@QEAAXAEBVhand@@@Z endp

; HandleListBase::setUnloaded(const class hand &);
?setUnloaded@HandleListBase@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+6*8]
?setUnloaded@HandleListBase@@UEAAXAEBVhand@@@Z endp

?_NV_destroy@HandleListBase@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_destroy@HandleListBase@@QEAAXAEBVhand@@@Z endp

; HandleListBase::destroy(const class hand &);
?destroy@HandleListBase@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+7*8]
?destroy@HandleListBase@@UEAAXAEBVhand@@@Z endp

?_NV_serialise@HandleListBase@@QEAAXAEAV?$basic_ofstream@DU?$char_traits@D@std@@@std@@@Z proc EXPORT
?_NV_serialise@HandleListBase@@QEAAXAEAV?$basic_ofstream@DU?$char_traits@D@std@@@std@@@Z endp

; HandleListBase::serialise(class std::basic_ofstream<char,std::char_traits<char> > &);
?serialise@HandleListBase@@UEAAXAEAV?$basic_ofstream@DU?$char_traits@D@std@@@std@@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+8*8]
?serialise@HandleListBase@@UEAAXAEAV?$basic_ofstream@DU?$char_traits@D@std@@@std@@@Z endp

?_NV_restore@HandleListBase@@QEAAXAEAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z proc EXPORT
?_NV_restore@HandleListBase@@QEAAXAEAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z endp

; HandleListBase::restore(class std::basic_ifstream<char,std::char_traits<char> > &);
?restore@HandleListBase@@UEAAXAEAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+9*8]
?restore@HandleListBase@@UEAAXAEAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z endp

; HandleListBase::addToList(class RootObjectBase *, bool, unsigned int);
?addToList@HandleListBase@@QEAAIPEAVRootObjectBase@@_NI@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+10*8]
?addToList@HandleListBase@@QEAAIPEAVRootObjectBase@@_NI@Z endp

; HandleListBase::resize(unsigned int);
?resize@HandleListBase@@QEAAXI@Z proc EXPORT
jmp function_pointers[_HandleListBase_base+11*8]
?resize@HandleListBase@@QEAAXI@Z endp

; HandleListBase::getNewID();
?getNewID@HandleListBase@@QEAAIXZ proc EXPORT
jmp function_pointers[_HandleListBase_base+12*8]
?getNewID@HandleListBase@@QEAAIXZ endp
