
?_CONSTRUCTOR@HandleList@@QEAAPEAV1@HVhand@@@Z proc EXPORT
?_CONSTRUCTOR@HandleList@@QEAAPEAV1@HVhand@@@Z endp

; HandleList::HandleList(int, class hand);
??0HandleList@@QEAA@HVhand@@@Z proc EXPORT
jmp function_pointers[_HandleList_base+0*8]
??0HandleList@@QEAA@HVhand@@@Z endp

?_NV_add@HandleList@@QEAA?AVhand@@PEAVRootObjectBase@@@Z proc EXPORT
?_NV_add@HandleList@@QEAA?AVhand@@PEAVRootObjectBase@@@Z endp

; HandleList::add(class RootObjectBase *);
?add@HandleList@@UEAA?AVhand@@PEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_HandleList_base+1*8]
?add@HandleList@@UEAA?AVhand@@PEAVRootObjectBase@@@Z endp

?_NV_get@HandleList@@QEBAPEAVRootObjectBase@@AEBVhand@@@Z proc EXPORT
?_NV_get@HandleList@@QEBAPEAVRootObjectBase@@AEBVhand@@@Z endp

; HandleList::get(const class hand &);
?get@HandleList@@UEBAPEAVRootObjectBase@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleList_base+2*8]
?get@HandleList@@UEBAPEAVRootObjectBase@@AEBVhand@@@Z endp

?_NV_addExisting@HandleList@@QEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z proc EXPORT
?_NV_addExisting@HandleList@@QEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z endp

; HandleList::addExisting(class RootObjectBase *, const class hand &);
?addExisting@HandleList@@UEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z proc EXPORT
jmp function_pointers[_HandleList_base+3*8]
?addExisting@HandleList@@UEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z endp

?_NV_addExistingAndForceContainer@HandleList@@QEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z proc EXPORT
?_NV_addExistingAndForceContainer@HandleList@@QEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z endp

; HandleList::addExistingAndForceContainer(class RootObjectBase *, const class hand &);
?addExistingAndForceContainer@HandleList@@UEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z proc EXPORT
jmp function_pointers[_HandleList_base+4*8]
?addExistingAndForceContainer@HandleList@@UEAA?AVhand@@PEAVRootObjectBase@@AEBV2@@Z endp

?_NV_destroy@HandleList@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_destroy@HandleList@@QEAAXAEBVhand@@@Z endp

; HandleList::destroy(const class hand &);
?destroy@HandleList@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleList_base+5*8]
?destroy@HandleList@@UEAAXAEBVhand@@@Z endp

?_NV_setIndex@HandleList@@QEBAXAEAVhand@@I@Z proc EXPORT
?_NV_setIndex@HandleList@@QEBAXAEAVhand@@I@Z endp

; HandleList::setIndex(class hand &, unsigned int);
?setIndex@HandleList@@UEBAXAEAVhand@@I@Z proc EXPORT
jmp function_pointers[_HandleList_base+6*8]
?setIndex@HandleList@@UEBAXAEAVhand@@I@Z endp

?_NV_getIndex@HandleList@@QEBAIAEBVhand@@@Z proc EXPORT
?_NV_getIndex@HandleList@@QEBAIAEBVhand@@@Z endp

; HandleList::getIndex(const class hand &);
?getIndex@HandleList@@UEBAIAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleList_base+7*8]
?getIndex@HandleList@@UEBAIAEBVhand@@@Z endp

?_NV_compareSerials@HandleList@@QEBA_NAEBVhand@@0@Z proc EXPORT
?_NV_compareSerials@HandleList@@QEBA_NAEBVhand@@0@Z endp

; HandleList::compareSerials(const class hand &, const class hand &);
?compareSerials@HandleList@@UEBA_NAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_HandleList_base+8*8]
?compareSerials@HandleList@@UEBA_NAEBVhand@@0@Z endp

?_DESTRUCTOR@HandleList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@HandleList@@QEAAXXZ endp

; HandleList::~HandleList();
??1HandleList@@UEAA@XZ proc EXPORT
jmp function_pointers[_HandleList_base+9*8]
??1HandleList@@UEAA@XZ endp
