
?_CONSTRUCTOR@HandleContainerList@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@HandleContainerList@@QEAAPEAV1@H@Z endp

; HandleContainerList::HandleContainerList(int);
??0HandleContainerList@@QEAA@H@Z proc EXPORT
jmp function_pointers[_HandleContainerList_base+0*8]
??0HandleContainerList@@QEAA@H@Z endp

?_NV_add@HandleContainerList@@QEAA?AVhand@@PEAVRootObjectBase@@@Z proc EXPORT
?_NV_add@HandleContainerList@@QEAA?AVhand@@PEAVRootObjectBase@@@Z endp

; HandleContainerList::add(class RootObjectBase *);
?add@HandleContainerList@@UEAA?AVhand@@PEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_HandleContainerList_base+1*8]
?add@HandleContainerList@@UEAA?AVhand@@PEAVRootObjectBase@@@Z endp

?_NV_setIndex@HandleContainerList@@QEBAXAEAVhand@@I@Z proc EXPORT
?_NV_setIndex@HandleContainerList@@QEBAXAEAVhand@@I@Z endp

; HandleContainerList::setIndex(class hand &, unsigned int);
?setIndex@HandleContainerList@@UEBAXAEAVhand@@I@Z proc EXPORT
jmp function_pointers[_HandleContainerList_base+2*8]
?setIndex@HandleContainerList@@UEBAXAEAVhand@@I@Z endp

?_NV_getIndex@HandleContainerList@@QEBAIAEBVhand@@@Z proc EXPORT
?_NV_getIndex@HandleContainerList@@QEBAIAEBVhand@@@Z endp

; HandleContainerList::getIndex(const class hand &);
?getIndex@HandleContainerList@@UEBAIAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HandleContainerList_base+3*8]
?getIndex@HandleContainerList@@UEBAIAEBVhand@@@Z endp

?_NV_compareSerials@HandleContainerList@@QEBA_NAEBVhand@@0@Z proc EXPORT
?_NV_compareSerials@HandleContainerList@@QEBA_NAEBVhand@@0@Z endp

; HandleContainerList::compareSerials(const class hand &, const class hand &);
?compareSerials@HandleContainerList@@UEBA_NAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_HandleContainerList_base+4*8]
?compareSerials@HandleContainerList@@UEBA_NAEBVhand@@0@Z endp

?_DESTRUCTOR@HandleContainerList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@HandleContainerList@@QEAAXXZ endp

; HandleContainerList::~HandleContainerList();
??1HandleContainerList@@UEAA@XZ proc EXPORT
jmp function_pointers[_HandleContainerList_base+5*8]
??1HandleContainerList@@UEAA@XZ endp
