
?_CONSTRUCTOR@ItemHandleList@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@ItemHandleList@@QEAAPEAV1@H@Z endp

; ItemHandleList::ItemHandleList(int);
??0ItemHandleList@@QEAA@H@Z proc EXPORT
jmp function_pointers[_ItemHandleList_base+0*8]
??0ItemHandleList@@QEAA@H@Z endp

?_NV_setUnloaded@ItemHandleList@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setUnloaded@ItemHandleList@@QEAAXAEBVhand@@@Z endp

; ItemHandleList::setUnloaded(const class hand &);
?setUnloaded@ItemHandleList@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ItemHandleList_base+1*8]
?setUnloaded@ItemHandleList@@UEAAXAEBVhand@@@Z endp

?_DESTRUCTOR@ItemHandleList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ItemHandleList@@QEAAXXZ endp

; ItemHandleList::~ItemHandleList();
??1ItemHandleList@@UEAA@XZ proc EXPORT
jmp function_pointers[_ItemHandleList_base+2*8]
??1ItemHandleList@@UEAA@XZ endp
