
?_CONSTRUCTOR@KingOfRenderThread@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@KingOfRenderThread@@QEAAPEAV1@XZ endp

; KingOfRenderThread::KingOfRenderThread();
??0KingOfRenderThread@@QEAA@XZ proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+0*8]
??0KingOfRenderThread@@QEAA@XZ endp

?_DESTRUCTOR@KingOfRenderThread@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@KingOfRenderThread@@QEAAXXZ endp

; KingOfRenderThread::~KingOfRenderThread();
??1KingOfRenderThread@@QEAA@XZ proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+1*8]
??1KingOfRenderThread@@QEAA@XZ endp

; KingOfRenderThread::startup();
?startup@KingOfRenderThread@@QEAAXXZ proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+2*8]
?startup@KingOfRenderThread@@QEAAXXZ endp

; KingOfRenderThread::initialisation();
?initialisation@KingOfRenderThread@@QEAAXXZ proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+3*8]
?initialisation@KingOfRenderThread@@QEAAXXZ endp

; KingOfRenderThread::mainloop(float);
?mainloop@KingOfRenderThread@@QEAAXM@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+4*8]
?mainloop@KingOfRenderThread@@QEAAXM@Z endp

; KingOfRenderThread::newGame(class MyGUI::Widget *);
?newGame@KingOfRenderThread@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+5*8]
?newGame@KingOfRenderThread@@QEAAXPEAVWidget@MyGUI@@@Z endp

; KingOfRenderThread::newGameWithCharEdit(class GameData *);
?newGameWithCharEdit@KingOfRenderThread@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+6*8]
?newGameWithCharEdit@KingOfRenderThread@@QEAAXPEAVGameData@@@Z endp

; KingOfRenderThread::error(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?error@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+7*8]
?error@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; KingOfRenderThread::errorD(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?errorD@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+8*8]
?errorD@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; KingOfRenderThread::loadTerrain(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?loadTerrain@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+9*8]
?loadTerrain@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; KingOfRenderThread::analyseModel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Ogre::Entity *);
?analyseModel@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+10*8]
?analyseModel@KingOfRenderThread@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVEntity@Ogre@@@Z endp

; KingOfRenderThread::getBonesVertices(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum MeshDataLookup::Dir);
?getBonesVertices@KingOfRenderThread@@QEBAAEBV?$lektor@H@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0W4Dir@MeshDataLookup@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+11*8]
?getBonesVertices@KingOfRenderThread@@QEBAAEBV?$lektor@H@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0W4Dir@MeshDataLookup@@@Z endp

; KingOfRenderThread::getMeshData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getMeshData@KingOfRenderThread@@QEAAPEAVMeshDataLookup@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+12*8]
?getMeshData@KingOfRenderThread@@QEAAPEAVMeshDataLookup@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; KingOfRenderThread::addTerrainBloodSplat(const float, const float, const float, const class Ogre::Radian, const class iVector2, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, bool);
?addTerrainBloodSplat@KingOfRenderThread@@QEAAXMMMVRadian@Ogre@@ViVector2@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+13*8]
?addTerrainBloodSplat@KingOfRenderThread@@QEAAXMMMVRadian@Ogre@@ViVector2@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; KingOfRenderThread::deleteTitleScreen();
?deleteTitleScreen@KingOfRenderThread@@QEAAXXZ proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+14*8]
?deleteTitleScreen@KingOfRenderThread@@QEAAXXZ endp

; KingOfRenderThread::processThreadMessages();
?processThreadMessages@KingOfRenderThread@@QEAAXXZ proc EXPORT
jmp function_pointers[_KingOfRenderThread_base+15*8]
?processThreadMessages@KingOfRenderThread@@QEAAXXZ endp
