
; LocaleManager::getInstance();
?getInstance@LocaleManager@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+0*8]
?getInstance@LocaleManager@@SAPEAV1@XZ endp

?_CONSTRUCTOR@LocaleManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@LocaleManager@@QEAAPEAV1@XZ endp

; LocaleManager::LocaleManager();
??0LocaleManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+1*8]
??0LocaleManager@@QEAA@XZ endp

?_DESTRUCTOR@LocaleManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LocaleManager@@QEAAXXZ endp

; LocaleManager::~LocaleManager();
??1LocaleManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+2*8]
??1LocaleManager@@QEAA@XZ endp

; LocaleManager::init();
?init@LocaleManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_LocaleManager_base+3*8]
?init@LocaleManager@@QEAAXXZ endp

; LocaleManager::getCurrentLocale();
?getCurrentLocale@LocaleManager@@QEBAPEAVLocaleInfo@@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+4*8]
?getCurrentLocale@LocaleManager@@QEBAPEAVLocaleInfo@@XZ endp

; LocaleManager::setCurrentLocale(class LocaleInfo *);
?setCurrentLocale@LocaleManager@@QEAAXPEAVLocaleInfo@@@Z proc EXPORT
jmp function_pointers[_LocaleManager_base+5*8]
?setCurrentLocale@LocaleManager@@QEAAXPEAVLocaleInfo@@@Z endp

; LocaleManager::trySetCurrentLocaleFromMod(class ModInfo *);
?trySetCurrentLocaleFromMod@LocaleManager@@QEAA_NPEAVModInfo@@@Z proc EXPORT
jmp function_pointers[_LocaleManager_base+6*8]
?trySetCurrentLocaleFromMod@LocaleManager@@QEAA_NPEAVModInfo@@@Z endp

; LocaleManager::getCurrentLocalePath();
?getCurrentLocalePath@LocaleManager@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+7*8]
?getCurrentLocalePath@LocaleManager@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; LocaleManager::getCurrentLocaleMod();
?getCurrentLocaleMod@LocaleManager@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+8*8]
?getCurrentLocaleMod@LocaleManager@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; LocaleManager::getAvailableLanguages();
?getAvailableLanguages@LocaleManager@@QEBAAEBV?$FastArray@PEAVLocaleInfo@@@Ogre@@XZ proc EXPORT
jmp function_pointers[_LocaleManager_base+9*8]
?getAvailableLanguages@LocaleManager@@QEBAAEBV?$FastArray@PEAVLocaleInfo@@@Ogre@@XZ endp

; LocaleManager::isEastAsian(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isEastAsian@LocaleManager@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_LocaleManager_base+10*8]
?isEastAsian@LocaleManager@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
