
?_CONSTRUCTOR@LocaleInfo@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@3@0_N@Z proc EXPORT
?_CONSTRUCTOR@LocaleInfo@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@3@0_N@Z endp

; LocaleInfo::LocaleInfo(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
??0LocaleInfo@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@2@0_N@Z proc EXPORT
jmp function_pointers[_LocaleInfo_base+0*8]
??0LocaleInfo@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@2@0_N@Z endp

?_CONSTRUCTOR@LocaleInfo@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@LocaleInfo@@QEAAPEAV1@XZ endp

; LocaleInfo::LocaleInfo();
??0LocaleInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_LocaleInfo_base+1*8]
??0LocaleInfo@@QEAA@XZ endp

?_DESTRUCTOR@LocaleInfo@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LocaleInfo@@QEAAXXZ endp

; LocaleInfo::~LocaleInfo();
??1LocaleInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_LocaleInfo_base+2*8]
??1LocaleInfo@@QEAA@XZ endp

; LocaleInfo::operator=(const class LocaleInfo &);
??4LocaleInfo@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_LocaleInfo_base+3*8]
??4LocaleInfo@@QEAAAEAV0@AEBV0@@Z endp
