
?_NV_getItemWeight@MapItem@@QEBAMXZ proc EXPORT
?_NV_getItemWeight@MapItem@@QEBAMXZ endp

; MapItem::getItemWeight();
?getItemWeight@MapItem@@UEBAMXZ proc EXPORT
jmp function_pointers[_MapItem_base+0*8]
?getItemWeight@MapItem@@UEBAMXZ endp

?_NV_getValueSingle@MapItem@@QEBAH_N@Z proc EXPORT
?_NV_getValueSingle@MapItem@@QEBAH_N@Z endp

; MapItem::getValueSingle(bool);
?getValueSingle@MapItem@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_MapItem_base+1*8]
?getValueSingle@MapItem@@UEBAH_N@Z endp

?_NV_getTooltipData1@MapItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@MapItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; MapItem::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@MapItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_MapItem_base+2*8]
?getTooltipData1@MapItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@MapItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@MapItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; MapItem::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@MapItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_MapItem_base+3*8]
?getTooltipData2@MapItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; MapItem::selectTowns();
?selectTowns@MapItem@@QEAAHXZ proc EXPORT
jmp function_pointers[_MapItem_base+4*8]
?selectTowns@MapItem@@QEAAHXZ endp

; MapItem::consume();
?consume@MapItem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MapItem_base+5*8]
?consume@MapItem@@QEAA_NXZ endp

; MapItem::getTownsDiscovered();
?getTownsDiscovered@MapItem@@QEBAHXZ proc EXPORT
jmp function_pointers[_MapItem_base+6*8]
?getTownsDiscovered@MapItem@@QEBAHXZ endp

?_NV__loadFromSerialise@MapItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@MapItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; MapItem::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@MapItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MapItem_base+7*8]
?_loadFromSerialise@MapItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV__serialise@MapItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@MapItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; MapItem::_serialise(class GameDataContainer *, enum itemType);
?_serialise@MapItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_MapItem_base+8*8]
?_serialise@MapItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_CONSTRUCTOR@MapItem@@QEAAPEAV1@PEAVGameData@@Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@MapItem@@QEAAPEAV1@PEAVGameData@@Vhand@@@Z endp

; MapItem::MapItem(class GameData *, class hand);
??0MapItem@@QEAA@PEAVGameData@@Vhand@@@Z proc EXPORT
jmp function_pointers[_MapItem_base+9*8]
??0MapItem@@QEAA@PEAVGameData@@Vhand@@@Z endp

?_DESTRUCTOR@MapItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MapItem@@QEAAXXZ endp

; MapItem::~MapItem();
??1MapItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_MapItem_base+10*8]
??1MapItem@@UEAA@XZ endp

; MapItem::copy(class MapItem *);
?copy@MapItem@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_MapItem_base+11*8]
?copy@MapItem@@QEAAXPEAV1@@Z endp
