
?_NV_getValueSingle@MoneyItem@@QEBAH_N@Z proc EXPORT
?_NV_getValueSingle@MoneyItem@@QEBAH_N@Z endp

; MoneyItem::getValueSingle(bool);
?getValueSingle@MoneyItem@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_MoneyItem_base+0*8]
?getValueSingle@MoneyItem@@UEBAH_N@Z endp

?_NV_getTooltipData1@MoneyItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@MoneyItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; MoneyItem::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@MoneyItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_MoneyItem_base+1*8]
?getTooltipData1@MoneyItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@MoneyItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@MoneyItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; MoneyItem::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@MoneyItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_MoneyItem_base+2*8]
?getTooltipData2@MoneyItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; MoneyItem::consume();
?consume@MoneyItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MoneyItem_base+3*8]
?consume@MoneyItem@@QEBA_NXZ endp

?_CONSTRUCTOR@MoneyItem@@QEAAPEAV1@PEAVGameData@@0AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@MoneyItem@@QEAAPEAV1@PEAVGameData@@0AEBVhand@@@Z endp

; MoneyItem::MoneyItem(class GameData *, class GameData *, const class hand &);
??0MoneyItem@@QEAA@PEAVGameData@@0AEBVhand@@@Z proc EXPORT
jmp function_pointers[_MoneyItem_base+4*8]
??0MoneyItem@@QEAA@PEAVGameData@@0AEBVhand@@@Z endp

?_DESTRUCTOR@MoneyItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MoneyItem@@QEAAXXZ endp

; MoneyItem::~MoneyItem();
??1MoneyItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_MoneyItem_base+5*8]
??1MoneyItem@@UEAA@XZ endp
