
?_NV_getClassType@NestItem@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@NestItem@@QEBA?AW4itemType@@XZ endp

; NestItem::getClassType();
?getClassType@NestItem@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_NestItem_base+0*8]
?getClassType@NestItem@@UEBA?AW4itemType@@XZ endp

?_NV_getModelName@NestItem@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getModelName@NestItem@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; NestItem::getModelName();
?getModelName@NestItem@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_NestItem_base+1*8]
?getModelName@NestItem@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_CONSTRUCTOR@NestItem@@QEAAPEAV1@PEAVGameData@@00Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@NestItem@@QEAAPEAV1@PEAVGameData@@00Vhand@@@Z endp

; NestItem::NestItem(class GameData *, class GameData *, class GameData *, class hand);
??0NestItem@@QEAA@PEAVGameData@@00Vhand@@@Z proc EXPORT
jmp function_pointers[_NestItem_base+2*8]
??0NestItem@@QEAA@PEAVGameData@@00Vhand@@@Z endp

?_DESTRUCTOR@NestItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NestItem@@QEAAXXZ endp

; NestItem::~NestItem();
??1NestItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_NestItem_base+3*8]
??1NestItem@@UEAA@XZ endp
