
?_CONSTRUCTOR@PlatoonHandleContainerList@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@PlatoonHandleContainerList@@QEAAPEAV1@H@Z endp

; PlatoonHandleContainerList::PlatoonHandleContainerList(int);
??0PlatoonHandleContainerList@@QEAA@H@Z proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+0*8]
??0PlatoonHandleContainerList@@QEAA@H@Z endp

; PlatoonHandleContainerList::getCharacterOrZero(const class hand &);
?getCharacterOrZero@PlatoonHandleContainerList@@QEBAPEAVRootObject@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+1*8]
?getCharacterOrZero@PlatoonHandleContainerList@@QEBAPEAVRootObject@@AEBVhand@@@Z endp

; PlatoonHandleContainerList::getCharacterOrPlatoon(const class hand &);
?getCharacterOrPlatoon@PlatoonHandleContainerList@@QEBAPEAVRootObjectBase@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+2*8]
?getCharacterOrPlatoon@PlatoonHandleContainerList@@QEBAPEAVRootObjectBase@@AEBVhand@@@Z endp

; PlatoonHandleContainerList::getActivePlatoon(const class hand &);
?getActivePlatoon@PlatoonHandleContainerList@@QEBAPEAVActivePlatoon@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+3*8]
?getActivePlatoon@PlatoonHandleContainerList@@QEBAPEAVActivePlatoon@@AEBVhand@@@Z endp

?_NV_setUnloaded@PlatoonHandleContainerList@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setUnloaded@PlatoonHandleContainerList@@QEAAXAEBVhand@@@Z endp

; PlatoonHandleContainerList::setUnloaded(const class hand &);
?setUnloaded@PlatoonHandleContainerList@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+4*8]
?setUnloaded@PlatoonHandleContainerList@@UEAAXAEBVhand@@@Z endp

?_NV_destroy@PlatoonHandleContainerList@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_destroy@PlatoonHandleContainerList@@QEAAXAEBVhand@@@Z endp

; PlatoonHandleContainerList::destroy(const class hand &);
?destroy@PlatoonHandleContainerList@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+5*8]
?destroy@PlatoonHandleContainerList@@UEAAXAEBVhand@@@Z endp

?_DESTRUCTOR@PlatoonHandleContainerList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PlatoonHandleContainerList@@QEAAXXZ endp

; PlatoonHandleContainerList::~PlatoonHandleContainerList();
??1PlatoonHandleContainerList@@UEAA@XZ proc EXPORT
jmp function_pointers[_PlatoonHandleContainerList_base+6*8]
??1PlatoonHandleContainerList@@UEAA@XZ endp
