
?_CONSTRUCTOR@FootprintNode@PreviewBuilding@@QEAAPEAV12@PEAV2@PEAVEntity@Ogre@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@FootprintNode@PreviewBuilding@@QEAAPEAV12@PEAV2@PEAVEntity@Ogre@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; PreviewBuilding::FootprintNode::FootprintNode(class PreviewBuilding *, class Ogre::Entity *, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0FootprintNode@PreviewBuilding@@QEAA@PEAV1@PEAVEntity@Ogre@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+0*8]
??0FootprintNode@PreviewBuilding@@QEAA@PEAV1@PEAVEntity@Ogre@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@FootprintNode@PreviewBuilding@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@FootprintNode@PreviewBuilding@@QEAAPEAV12@XZ endp

; PreviewBuilding::FootprintNode::FootprintNode();
??0FootprintNode@PreviewBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+1*8]
??0FootprintNode@PreviewBuilding@@QEAA@XZ endp

?_NV_getWorldAABB@FootprintNode@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ proc EXPORT
?_NV_getWorldAABB@FootprintNode@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ endp

; PreviewBuilding::FootprintNode::getWorldAABB();
?getWorldAABB@FootprintNode@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+2*8]
?getWorldAABB@FootprintNode@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ endp

?_NV_getLocalAABB@FootprintNode@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ proc EXPORT
?_NV_getLocalAABB@FootprintNode@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ endp

; PreviewBuilding::FootprintNode::getLocalAABB();
?getLocalAABB@FootprintNode@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+3*8]
?getLocalAABB@FootprintNode@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ endp

?_NV_updateBox@FootprintNode@PreviewBuilding@@QEAAXXZ proc EXPORT
?_NV_updateBox@FootprintNode@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::FootprintNode::updateBox();
?updateBox@FootprintNode@PreviewBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+4*8]
?updateBox@FootprintNode@PreviewBuilding@@UEAAXXZ endp

; PreviewBuilding::FootprintNode::getNodeId();
?getNodeId@FootprintNode@PreviewBuilding@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+5*8]
?getNodeId@FootprintNode@PreviewBuilding@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; symbol is too long
; ?collisionTestOK@FootprintNode@PreviewBuilding@@UEAA_N_NPEAVBuilding@@PEBV?$map@Vhand@@V?$vector@PEAVUsageNode@@V?$STLAllocator@PEAVUsageNode@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@U?$less@Vhand@@@3@V?$STLAllocator@U?$pair@$$CBVhand@@V?$vector@PEAVUsageNode@@V?$STLAllocator@PEAVUsageNode@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z
; PreviewBuilding::FootprintNode::collisionTestOK(bool, class Building *, const class std::map<hand,std::vector<UsageNode *,Ogre::STLAllocator<UsageNode *,Ogre::CategorisedAllocPolicy<0> > >,std::less<hand>,Ogre::STLAllocator<std::pair<hand const ,std::vector<UsageNode *,Ogre::STLAllocator<UsageNode *,Ogre::CategorisedAllocPolicy<0> > > >,Ogre::CategorisedAllocPolicy<0> > > *);
PreviewBuilding_FootprintNode_collisionTestOK_PLACEHOLDER proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+6*8]
PreviewBuilding_FootprintNode_collisionTestOK_PLACEHOLDER endp

; PreviewBuilding::FootprintNode::setEnabled(bool);
?setEnabled@FootprintNode@PreviewBuilding@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+7*8]
?setEnabled@FootprintNode@PreviewBuilding@@QEAAX_N@Z endp

?_DESTRUCTOR@FootprintNode@PreviewBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FootprintNode@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::FootprintNode::~FootprintNode();
??1FootprintNode@PreviewBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+8*8]
??1FootprintNode@PreviewBuilding@@QEAA@XZ endp

; PreviewBuilding::FootprintNode::operator=(const class PreviewBuilding::FootprintNode &);
??4FootprintNode@PreviewBuilding@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_FootprintNode_base+9*8]
??4FootprintNode@PreviewBuilding@@QEAAAEAV01@AEBV01@@Z endp
