
?_CONSTRUCTOR@Footprint@PreviewBuilding@@QEAAPEAV12@PEAV2@PEAVEntity@Ogre@@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@Footprint@PreviewBuilding@@QEAAPEAV12@PEAV2@PEAVEntity@Ogre@@PEAVGameData@@@Z endp

; PreviewBuilding::Footprint::Footprint(class PreviewBuilding *, class Ogre::Entity *, class GameData *);
??0Footprint@PreviewBuilding@@QEAA@PEAV1@PEAVEntity@Ogre@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+0*8]
??0Footprint@PreviewBuilding@@QEAA@PEAV1@PEAVEntity@Ogre@@PEAVGameData@@@Z endp

?_CONSTRUCTOR@Footprint@PreviewBuilding@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Footprint@PreviewBuilding@@QEAAPEAV12@XZ endp

; PreviewBuilding::Footprint::Footprint();
??0Footprint@PreviewBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+1*8]
??0Footprint@PreviewBuilding@@QEAA@XZ endp

?_DESTRUCTOR@Footprint@PreviewBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Footprint@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::Footprint::~Footprint();
??1Footprint@PreviewBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+2*8]
??1Footprint@PreviewBuilding@@QEAA@XZ endp

?_NV_getWorldAABB@Footprint@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ proc EXPORT
?_NV_getWorldAABB@Footprint@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ endp

; PreviewBuilding::Footprint::getWorldAABB();
?getWorldAABB@Footprint@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+3*8]
?getWorldAABB@Footprint@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ endp

?_NV_getLocalAABB@Footprint@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ proc EXPORT
?_NV_getLocalAABB@Footprint@PreviewBuilding@@QEBA?BUAabb@Ogre@@XZ endp

; PreviewBuilding::Footprint::getLocalAABB();
?getLocalAABB@Footprint@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+4*8]
?getLocalAABB@Footprint@PreviewBuilding@@UEBA?BUAabb@Ogre@@XZ endp

; PreviewBuilding::Footprint::getSpace();
?getSpace@Footprint@PreviewBuilding@@QEBAMXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+5*8]
?getSpace@Footprint@PreviewBuilding@@QEBAMXZ endp

; PreviewBuilding::Footprint::getMarker();
?getMarker@Footprint@PreviewBuilding@@QEBAMXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+6*8]
?getMarker@Footprint@PreviewBuilding@@QEBAMXZ endp

; PreviewBuilding::Footprint::setValid(bool);
?setValid@Footprint@PreviewBuilding@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+7*8]
?setValid@Footprint@PreviewBuilding@@QEAAX_N@Z endp

; PreviewBuilding::Footprint::getValid();
?getValid@Footprint@PreviewBuilding@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+8*8]
?getValid@Footprint@PreviewBuilding@@QEBA_NXZ endp

; PreviewBuilding::Footprint::validate();
?validate@Footprint@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+9*8]
?validate@Footprint@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::Footprint::fakeOppositeValidate(float);
?fakeOppositeValidate@Footprint@PreviewBuilding@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+10*8]
?fakeOppositeValidate@Footprint@PreviewBuilding@@QEAA_NM@Z endp

; symbol is too long
; ?collisionTestOK@Footprint@PreviewBuilding@@UEAA_N_NPEAVBuilding@@PEBV?$map@Vhand@@V?$vector@PEAVUsageNode@@V?$STLAllocator@PEAVUsageNode@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@U?$less@Vhand@@@3@V?$STLAllocator@U?$pair@$$CBVhand@@V?$vector@PEAVUsageNode@@V?$STLAllocator@PEAVUsageNode@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z
; PreviewBuilding::Footprint::collisionTestOK(bool, class Building *, const class std::map<hand,std::vector<UsageNode *,Ogre::STLAllocator<UsageNode *,Ogre::CategorisedAllocPolicy<0> > >,std::less<hand>,Ogre::STLAllocator<std::pair<hand const ,std::vector<UsageNode *,Ogre::STLAllocator<UsageNode *,Ogre::CategorisedAllocPolicy<0> > > >,Ogre::CategorisedAllocPolicy<0> > > *);
PreviewBuilding_Footprint_collisionTestOK_PLACEHOLDER proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+11*8]
PreviewBuilding_Footprint_collisionTestOK_PLACEHOLDER endp

; PreviewBuilding::Footprint::collisionTestBuildings(bool, class Building *, int);
?collisionTestBuildings@Footprint@PreviewBuilding@@QEAA_N_NPEAVBuilding@@H@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+12*8]
?collisionTestBuildings@Footprint@PreviewBuilding@@QEAA_N_NPEAVBuilding@@H@Z endp

; PreviewBuilding::Footprint::collisionTestCharacters();
?collisionTestCharacters@Footprint@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+13*8]
?collisionTestCharacters@Footprint@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::Footprint::validFloorTest();
?validFloorTest@Footprint@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+14*8]
?validFloorTest@Footprint@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::Footprint::isIndoorsOK(bool, class Building * *, class Town *);
?isIndoorsOK@Footprint@PreviewBuilding@@QEAA_N_NPEAPEAVBuilding@@PEAVTown@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+15*8]
?isIndoorsOK@Footprint@PreviewBuilding@@QEAA_N_NPEAPEAVBuilding@@PEAVTown@@@Z endp

; symbol is too long
; ?blocksAnyBuildingTest@Footprint@PreviewBuilding@@QEAA_NAEBV?$map@Vhand@@V?$vector@PEAVUsageNode@@V?$STLAllocator@PEAVUsageNode@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@U?$less@Vhand@@@3@V?$STLAllocator@U?$pair@$$CBVhand@@V?$vector@PEAVUsageNode@@V?$STLAllocator@PEAVUsageNode@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z
; PreviewBuilding::Footprint::blocksAnyBuildingTest(const class std::map<hand,std::vector<UsageNode *,Ogre::STLAllocator<UsageNode *,Ogre::CategorisedAllocPolicy<0> > >,std::less<hand>,Ogre::STLAllocator<std::pair<hand const ,std::vector<UsageNode *,Ogre::STLAllocator<UsageNode *,Ogre::CategorisedAllocPolicy<0> > > >,Ogre::CategorisedAllocPolicy<0> > > &);
PreviewBuilding_Footprint_blocksAnyBuildingTest_PLACEHOLDER proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+16*8]
PreviewBuilding_Footprint_blocksAnyBuildingTest_PLACEHOLDER endp

; PreviewBuilding::Footprint::isGroundValid();
?isGroundValid@Footprint@PreviewBuilding@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+17*8]
?isGroundValid@Footprint@PreviewBuilding@@QEBA_NXZ endp

; PreviewBuilding::Footprint::getWorldCorner(int);
?getWorldCorner@Footprint@PreviewBuilding@@QEBA?AVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+18*8]
?getWorldCorner@Footprint@PreviewBuilding@@QEBA?AVVector3@Ogre@@H@Z endp

?_NV_updateBox@Footprint@PreviewBuilding@@QEAAXXZ proc EXPORT
?_NV_updateBox@Footprint@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::Footprint::updateBox();
?updateBox@Footprint@PreviewBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+19*8]
?updateBox@Footprint@PreviewBuilding@@UEAAXXZ endp

; PreviewBuilding::Footprint::getGroundHeight(const class Ogre::Vector3 &);
?getGroundHeight@Footprint@PreviewBuilding@@QEBAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+20*8]
?getGroundHeight@Footprint@PreviewBuilding@@QEBAMAEBVVector3@Ogre@@@Z endp

; PreviewBuilding::Footprint::operator=(const class PreviewBuilding::Footprint &);
??4Footprint@PreviewBuilding@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_Footprint_base+21*8]
??4Footprint@PreviewBuilding@@QEAAAEAV01@AEBV01@@Z endp
