
; PreviewBuilding::getPlacementResultMaterialName(enum PreviewBuilding::PlacementResult);
?getPlacementResultMaterialName@PreviewBuilding@@SAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4PlacementResult@1@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+0*8]
?getPlacementResultMaterialName@PreviewBuilding@@SAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4PlacementResult@1@@Z endp

?_CONSTRUCTOR@PreviewBuilding@@QEAAPEAV1@PEAVGameData@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@PreviewBuilding@@QEAAPEAV1@PEAVGameData@@PEAVBuilding@@@Z endp

; PreviewBuilding::PreviewBuilding(class GameData *, class Building *);
??0PreviewBuilding@@QEAA@PEAVGameData@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+1*8]
??0PreviewBuilding@@QEAA@PEAVGameData@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@PreviewBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::~PreviewBuilding();
??1PreviewBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+2*8]
??1PreviewBuilding@@UEAA@XZ endp

?_NV_type@PreviewBuilding@@QEBA?AW4PreviewBuildingClassType@1@XZ proc EXPORT
?_NV_type@PreviewBuilding@@QEBA?AW4PreviewBuildingClassType@1@XZ endp

; PreviewBuilding::type();
?type@PreviewBuilding@@UEBA?AW4PreviewBuildingClassType@1@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+3*8]
?type@PreviewBuilding@@UEBA?AW4PreviewBuildingClassType@1@XZ endp

?_NV_checkProspectingIsNotZero@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_checkProspectingIsNotZero@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::checkProspectingIsNotZero();
?checkProspectingIsNotZero@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+4*8]
?checkProspectingIsNotZero@PreviewBuilding@@UEAA_NXZ endp

?_NV_isASnapToBuilding@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isASnapToBuilding@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isASnapToBuilding();
?isASnapToBuilding@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+5*8]
?isASnapToBuilding@PreviewBuilding@@UEAA_NXZ endp

?_NV_isACeilingBuilding@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isACeilingBuilding@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isACeilingBuilding();
?isACeilingBuilding@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+6*8]
?isACeilingBuilding@PreviewBuilding@@UEAA_NXZ endp

?_NV_snappingOk@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_snappingOk@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::snappingOk();
?snappingOk@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+7*8]
?snappingOk@PreviewBuilding@@UEAA_NXZ endp

?_NV_isInteriorBuilding@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isInteriorBuilding@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isInteriorBuilding();
?isInteriorBuilding@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+8*8]
?isInteriorBuilding@PreviewBuilding@@UEAA_NXZ endp

; PreviewBuilding::isCurrent();
?isCurrent@PreviewBuilding@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+9*8]
?isCurrent@PreviewBuilding@@QEBA_NXZ endp

?_NV_setup@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_setup@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::setup();
?setup@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+10*8]
?setup@PreviewBuilding@@UEAA_NXZ endp

?_NV__destroyEnts@PreviewBuilding@@QEAAXXZ proc EXPORT
?_NV__destroyEnts@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::_destroyEnts();
?_destroyEnts@PreviewBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+11*8]
?_destroyEnts@PreviewBuilding@@UEAAXXZ endp

?_NV_update@PreviewBuilding@@QEAAXXZ proc EXPORT
?_NV_update@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::update();
?update@PreviewBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+12*8]
?update@PreviewBuilding@@UEAAXXZ endp

?_NV_buildingPlacementUpdate@PreviewBuilding@@QEAAXAEAVphysHit@@AEA_N1@Z proc EXPORT
?_NV_buildingPlacementUpdate@PreviewBuilding@@QEAAXAEAVphysHit@@AEA_N1@Z endp

; PreviewBuilding::buildingPlacementUpdate(class physHit &, bool &, bool &);
?buildingPlacementUpdate@PreviewBuilding@@UEAAXAEAVphysHit@@AEA_N1@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+13*8]
?buildingPlacementUpdate@PreviewBuilding@@UEAAXAEAVphysHit@@AEA_N1@Z endp

; PreviewBuilding::figureOutWhichTown();
?figureOutWhichTown@PreviewBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+14*8]
?figureOutWhichTown@PreviewBuilding@@QEAAXXZ endp

?_NV_setVisualPosition@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_setVisualPosition@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@@Z endp

; PreviewBuilding::setVisualPosition(const class Ogre::Vector3 &);
?setVisualPosition@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+15*8]
?setVisualPosition@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@@Z endp

; PreviewBuilding::yawBy(float);
?yawBy@PreviewBuilding@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+16*8]
?yawBy@PreviewBuilding@@QEAAXM@Z endp

; PreviewBuilding::yawSet(float);
?yawSet@PreviewBuilding@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+17*8]
?yawSet@PreviewBuilding@@QEAAXM@Z endp

; PreviewBuilding::rotateBy(const class Ogre::Quaternion &);
?rotateBy@PreviewBuilding@@QEAAXAEBVQuaternion@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+18*8]
?rotateBy@PreviewBuilding@@QEAAXAEBVQuaternion@Ogre@@@Z endp

; PreviewBuilding::tilt(float);
?tilt@PreviewBuilding@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+19*8]
?tilt@PreviewBuilding@@QEAAXM@Z endp

; PreviewBuilding::roll(float);
?roll@PreviewBuilding@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+20*8]
?roll@PreviewBuilding@@QEAAXM@Z endp

; PreviewBuilding::setRotation(const class Ogre::Quaternion &);
?setRotation@PreviewBuilding@@QEAAXAEBVQuaternion@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+21*8]
?setRotation@PreviewBuilding@@QEAAXAEBVQuaternion@Ogre@@@Z endp

; PreviewBuilding::allFootprintsWantBelowGround();
?allFootprintsWantBelowGround@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+22*8]
?allFootprintsWantBelowGround@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::allFootprintsWantAboveGround();
?allFootprintsWantAboveGround@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+23*8]
?allFootprintsWantAboveGround@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::updateFootprintHeights();
?updateFootprintHeights@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+24*8]
?updateFootprintHeights@PreviewBuilding@@QEAA_NXZ endp

?_NV_isCollisionOK@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isCollisionOK@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isCollisionOK();
?isCollisionOK@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+25*8]
?isCollisionOK@PreviewBuilding@@UEAA_NXZ endp

?_NV_isFloorOk@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isFloorOk@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isFloorOk();
?isFloorOk@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+26*8]
?isFloorOk@PreviewBuilding@@UEAA_NXZ endp

?_NV_isIndoorsOk@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isIndoorsOk@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isIndoorsOk();
?isIndoorsOk@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+27*8]
?isIndoorsOk@PreviewBuilding@@UEAA_NXZ endp

?_NV_isNodesOk@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isNodesOk@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isNodesOk();
?isNodesOk@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+28*8]
?isNodesOk@PreviewBuilding@@UEAA_NXZ endp

?_NV_isBlockingBuildingsNodes@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isBlockingBuildingsNodes@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isBlockingBuildingsNodes();
?isBlockingBuildingsNodes@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+29*8]
?isBlockingBuildingsNodes@PreviewBuilding@@UEAA_NXZ endp

?_NV_isGoodAboveAndBelow@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_isGoodAboveAndBelow@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::isGoodAboveAndBelow();
?isGoodAboveAndBelow@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+30*8]
?isGoodAboveAndBelow@PreviewBuilding@@UEAA_NXZ endp

?_NV_isOnValidGround@PreviewBuilding@@QEBA_NXZ proc EXPORT
?_NV_isOnValidGround@PreviewBuilding@@QEBA_NXZ endp

; PreviewBuilding::isOnValidGround();
?isOnValidGround@PreviewBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+31*8]
?isOnValidGround@PreviewBuilding@@UEBA_NXZ endp

?_NV_isLinked@PreviewBuilding@@QEBA_NXZ proc EXPORT
?_NV_isLinked@PreviewBuilding@@QEBA_NXZ endp

; PreviewBuilding::isLinked();
?isLinked@PreviewBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+32*8]
?isLinked@PreviewBuilding@@UEBA_NXZ endp

; PreviewBuilding::moveHeightOffset(float);
?moveHeightOffset@PreviewBuilding@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+33*8]
?moveHeightOffset@PreviewBuilding@@QEAAXM@Z endp

; PreviewBuilding::resetHeightOffset();
?resetHeightOffset@PreviewBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+34*8]
?resetHeightOffset@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::getFootprintShift();
?getFootprintShift@PreviewBuilding@@QEBAMXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+35*8]
?getFootprintShift@PreviewBuilding@@QEBAMXZ endp

; PreviewBuilding::getOrientation();
?getOrientation@PreviewBuilding@@QEAAAEBVQuaternion@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+36*8]
?getOrientation@PreviewBuilding@@QEAAAEBVQuaternion@Ogre@@XZ endp

; PreviewBuilding::setOrientation(const class Ogre::Quaternion &);
?setOrientation@PreviewBuilding@@QEAAXAEBVQuaternion@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+37*8]
?setOrientation@PreviewBuilding@@QEAAXAEBVQuaternion@Ogre@@@Z endp

; PreviewBuilding::getPosition();
?getPosition@PreviewBuilding@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+38*8]
?getPosition@PreviewBuilding@@QEBA?BVVector3@Ogre@@XZ endp

; PreviewBuilding::getCentreOffset();
?getCentreOffset@PreviewBuilding@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+39*8]
?getCentreOffset@PreviewBuilding@@QEBAAEBVVector3@Ogre@@XZ endp

; PreviewBuilding::getFloor();
?getFloor@PreviewBuilding@@QEBAHXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+40*8]
?getFloor@PreviewBuilding@@QEBAHXZ endp

?_NV_setStartPosition@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_setStartPosition@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@@Z endp

; PreviewBuilding::setStartPosition(const class Ogre::Vector3 &);
?setStartPosition@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+41*8]
?setStartPosition@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_setEndPosition@PreviewBuilding@@QEAAXVVector3@Ogre@@@Z proc EXPORT
?_NV_setEndPosition@PreviewBuilding@@QEAAXVVector3@Ogre@@@Z endp

; PreviewBuilding::setEndPosition(class Ogre::Vector3);
?setEndPosition@PreviewBuilding@@UEAAXVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+42*8]
?setEndPosition@PreviewBuilding@@UEAAXVVector3@Ogre@@@Z endp

?_NV_getEndPos@PreviewBuilding@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getEndPos@PreviewBuilding@@QEBA?AVVector3@Ogre@@XZ endp

; PreviewBuilding::getEndPos();
?getEndPos@PreviewBuilding@@UEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+43*8]
?getEndPos@PreviewBuilding@@UEBA?AVVector3@Ogre@@XZ endp

?_NV_clearPointersTo@PreviewBuilding@@QEAAXPEAV1@@Z proc EXPORT
?_NV_clearPointersTo@PreviewBuilding@@QEAAXPEAV1@@Z endp

; PreviewBuilding::clearPointersTo(class PreviewBuilding *);
?clearPointersTo@PreviewBuilding@@UEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+44*8]
?clearPointersTo@PreviewBuilding@@UEAAXPEAV1@@Z endp

?_NV_placeFinalPreviewBuilding@PreviewBuilding@@QEAAXXZ proc EXPORT
?_NV_placeFinalPreviewBuilding@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::placeFinalPreviewBuilding();
?placeFinalPreviewBuilding@PreviewBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+45*8]
?placeFinalPreviewBuilding@PreviewBuilding@@UEAAXXZ endp

; PreviewBuilding::insideBuilding();
?insideBuilding@PreviewBuilding@@QEBAPEAVBuilding@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+46*8]
?insideBuilding@PreviewBuilding@@QEBAPEAVBuilding@@XZ endp

?_NV_placementVerification@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_placementVerification@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::placementVerification();
?placementVerification@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+47*8]
?placementVerification@PreviewBuilding@@UEAA_NXZ endp

; PreviewBuilding::getWorldAABB();
?getWorldAABB@PreviewBuilding@@QEBAAEBUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+48*8]
?getWorldAABB@PreviewBuilding@@QEBAAEBUAabb@Ogre@@XZ endp

?_NV_isNoCollideWithThisBuilding@PreviewBuilding@@QEAA_NPEAV1@@Z proc EXPORT
?_NV_isNoCollideWithThisBuilding@PreviewBuilding@@QEAA_NPEAV1@@Z endp

; PreviewBuilding::isNoCollideWithThisBuilding(class PreviewBuilding *);
?isNoCollideWithThisBuilding@PreviewBuilding@@UEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+49*8]
?isNoCollideWithThisBuilding@PreviewBuilding@@UEAA_NPEAV1@@Z endp

?_NV_isNoCollideWithThisBuilding@PreviewBuilding@@QEAA_NPEAVRootObject@@PEAVNxShape@@_N@Z proc EXPORT
?_NV_isNoCollideWithThisBuilding@PreviewBuilding@@QEAA_NPEAVRootObject@@PEAVNxShape@@_N@Z endp

; PreviewBuilding::isNoCollideWithThisBuilding(class RootObject *, class NxShape *, bool);
?isNoCollideWithThisBuilding@PreviewBuilding@@UEAA_NPEAVRootObject@@PEAVNxShape@@_N@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+50*8]
?isNoCollideWithThisBuilding@PreviewBuilding@@UEAA_NPEAVRootObject@@PEAVNxShape@@_N@Z endp

; PreviewBuilding::getGameData();
?getGameData@PreviewBuilding@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+51*8]
?getGameData@PreviewBuilding@@QEAAPEAVGameData@@XZ endp

?_NV_noAltitude@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_noAltitude@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::noAltitude();
?noAltitude@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+52*8]
?noAltitude@PreviewBuilding@@UEAA_NXZ endp

?_NV_noPathfindingNeeded@PreviewBuilding@@QEAA_NXZ proc EXPORT
?_NV_noPathfindingNeeded@PreviewBuilding@@QEAA_NXZ endp

; PreviewBuilding::noPathfindingNeeded();
?noPathfindingNeeded@PreviewBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+53*8]
?noPathfindingNeeded@PreviewBuilding@@UEAA_NXZ endp

?_NV_placePreview@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@H@Z proc EXPORT
?_NV_placePreview@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@H@Z endp

; PreviewBuilding::placePreview(const class Ogre::Vector3 &, const class Ogre::Quaternion &, int);
?placePreview@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@H@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+54*8]
?placePreview@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@H@Z endp

; PreviewBuilding::resetUseageNodes();
?resetUseageNodes@PreviewBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+55*8]
?resetUseageNodes@PreviewBuilding@@QEAAXXZ endp

?_NV_calculateRotationsAndStuff@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_calculateRotationsAndStuff@PreviewBuilding@@QEAAXAEBVVector3@Ogre@@@Z endp

; PreviewBuilding::calculateRotationsAndStuff(const class Ogre::Vector3 &);
?calculateRotationsAndStuff@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PreviewBuilding_base+56*8]
?calculateRotationsAndStuff@PreviewBuilding@@UEAAXAEBVVector3@Ogre@@@Z endp

; PreviewBuilding::placementVerification_recurse();
?placementVerification_recurse@PreviewBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+57*8]
?placementVerification_recurse@PreviewBuilding@@QEAA_NXZ endp

?_NV_getTerrainHeightAtCenter@PreviewBuilding@@QEAAMXZ proc EXPORT
?_NV_getTerrainHeightAtCenter@PreviewBuilding@@QEAAMXZ endp

; PreviewBuilding::getTerrainHeightAtCenter();
?getTerrainHeightAtCenter@PreviewBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+58*8]
?getTerrainHeightAtCenter@PreviewBuilding@@UEAAMXZ endp

; PreviewBuilding::recalculateWorldAABB();
?recalculateWorldAABB@PreviewBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+59*8]
?recalculateWorldAABB@PreviewBuilding@@QEAAXXZ endp

; PreviewBuilding::validateUsageNodes();
?validateUsageNodes@PreviewBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_PreviewBuilding_base+60*8]
?validateUsageNodes@PreviewBuilding@@QEAAXXZ endp
