
?_CONSTRUCTOR@RagdollAnimationTrack@RagdollAnimation@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@RagdollAnimationTrack@RagdollAnimation@@QEAAPEAV12@XZ endp

; RagdollAnimation::RagdollAnimationTrack::RagdollAnimationTrack();
??0RagdollAnimationTrack@RagdollAnimation@@QEAA@XZ proc EXPORT
jmp function_pointers[_RagdollAnimation_RagdollAnimationTrack_base+0*8]
??0RagdollAnimationTrack@RagdollAnimation@@QEAA@XZ endp

; RagdollAnimation::RagdollAnimationTrack::operator=(const class RagdollAnimation::RagdollAnimationTrack &);
??4RagdollAnimationTrack@RagdollAnimation@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_RagdollAnimation_RagdollAnimationTrack_base+1*8]
??4RagdollAnimationTrack@RagdollAnimation@@QEAAAEAV01@AEBV01@@Z endp
