
?_CONSTRUCTOR@RagdollAnimation@@QEAAPEAV1@PEAVAnimationClass@@@Z proc EXPORT
?_CONSTRUCTOR@RagdollAnimation@@QEAAPEAV1@PEAVAnimationClass@@@Z endp

; RagdollAnimation::RagdollAnimation(class AnimationClass *);
??0RagdollAnimation@@QEAA@PEAVAnimationClass@@@Z proc EXPORT
jmp function_pointers[_RagdollAnimation_base+0*8]
??0RagdollAnimation@@QEAA@PEAVAnimationClass@@@Z endp

; RagdollAnimation::isAnimating();
?isAnimating@RagdollAnimation@@QEBA_NXZ proc EXPORT
jmp function_pointers[_RagdollAnimation_base+1*8]
?isAnimating@RagdollAnimation@@QEBA_NXZ endp

; RagdollAnimation::update();
?update@RagdollAnimation@@QEAAXXZ proc EXPORT
jmp function_pointers[_RagdollAnimation_base+2*8]
?update@RagdollAnimation@@QEAAXXZ endp

; RagdollAnimation::setTargetAnimation(class Ogre::Entity *, class Ogre::OldSkeletonInstance *, class Ogre::Animation *, float);
?setTargetAnimation@RagdollAnimation@@QEAAXPEAVEntity@Ogre@@PEAVOldSkeletonInstance@3@PEAVAnimation@3@M@Z proc EXPORT
jmp function_pointers[_RagdollAnimation_base+3*8]
?setTargetAnimation@RagdollAnimation@@QEAAXPEAVEntity@Ogre@@PEAVOldSkeletonInstance@3@PEAVAnimation@3@M@Z endp

; RagdollAnimation::getTargetAnimation();
?getTargetAnimation@RagdollAnimation@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_RagdollAnimation_base+4*8]
?getTargetAnimation@RagdollAnimation@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; RagdollAnimation::getAnimationTime();
?getAnimationTime@RagdollAnimation@@QEBAMXZ proc EXPORT
jmp function_pointers[_RagdollAnimation_base+5*8]
?getAnimationTime@RagdollAnimation@@QEBAMXZ endp

?_DESTRUCTOR@RagdollAnimation@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RagdollAnimation@@QEAAXXZ endp

; RagdollAnimation::~RagdollAnimation();
??1RagdollAnimation@@QEAA@XZ proc EXPORT
jmp function_pointers[_RagdollAnimation_base+6*8]
??1RagdollAnimation@@QEAA@XZ endp
