
?_DESTRUCTOR@RendererT@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RendererT@@QEAAXXZ endp

; RendererT::~RendererT();
??1RendererT@@UEAA@XZ proc EXPORT
jmp function_pointers[_RendererT_base+0*8]
??1RendererT@@UEAA@XZ endp

?_CONSTRUCTOR@RendererT@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@RendererT@@QEAAPEAV1@XZ endp

; RendererT::RendererT();
??0RendererT@@QEAA@XZ proc EXPORT
jmp function_pointers[_RendererT_base+1*8]
??0RendererT@@QEAA@XZ endp
