
?_CONSTRUCTOR@Renderer@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Renderer@@QEAAPEAV1@XZ endp

; Renderer::Renderer();
??0Renderer@@QEAA@XZ proc EXPORT
jmp function_pointers[_Renderer_base+0*8]
??0Renderer@@QEAA@XZ endp

?_DESTRUCTOR@Renderer@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Renderer@@QEAAXXZ endp

; Renderer::~Renderer();
??1Renderer@@UEAA@XZ proc EXPORT
jmp function_pointers[_Renderer_base+1*8]
??1Renderer@@UEAA@XZ endp

; Renderer::shutDown();
?shutDown@Renderer@@QEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+2*8]
?shutDown@Renderer@@QEAAXXZ endp

?_NV_update@Renderer@@QEAAXXZ proc EXPORT
?_NV_update@Renderer@@QEAAXXZ endp

; Renderer::update();
?update@Renderer@@UEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+3*8]
?update@Renderer@@UEAAXXZ endp

; Renderer::createLight(class GameData *, bool, int);
?createLight@Renderer@@QEAAPEAVLight@Ogre@@PEAVGameData@@_NH@Z proc EXPORT
jmp function_pointers[_Renderer_base+4*8]
?createLight@Renderer@@QEAAPEAVLight@Ogre@@PEAVGameData@@_NH@Z endp

; Renderer::initialiseRoot(struct HWND__ *);
?initialiseRoot@Renderer@@QEAAPEAVCamera@Ogre@@PEAUHWND__@@@Z proc EXPORT
jmp function_pointers[_Renderer_base+5*8]
?initialiseRoot@Renderer@@QEAAPEAVCamera@Ogre@@PEAUHWND__@@@Z endp

; Renderer::go();
?go@Renderer@@QEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+6*8]
?go@Renderer@@QEAAXXZ endp

; Renderer::initialiseScene();
?initialiseScene@Renderer@@QEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+7*8]
?initialiseScene@Renderer@@QEAAXXZ endp

; Renderer::createDebugBox(class Ogre::Vector3, class Ogre::Vector3);
?createDebugBox@Renderer@@QEAAPEAVEntity@Ogre@@VVector3@3@0@Z proc EXPORT
jmp function_pointers[_Renderer_base+8*8]
?createDebugBox@Renderer@@QEAAPEAVEntity@Ogre@@VVector3@3@0@Z endp

; Renderer::destroy(class Ogre::SceneNode *, bool);
?destroy@Renderer@@QEAAXPEAVSceneNode@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_Renderer_base+9*8]
?destroy@Renderer@@QEAAXPEAVSceneNode@Ogre@@_N@Z endp

; Renderer::destroy(class Ogre::Light *);
?destroy@Renderer@@QEAAXPEAVLight@Ogre@@@Z proc EXPORT
jmp function_pointers[_Renderer_base+10*8]
?destroy@Renderer@@QEAAXPEAVLight@Ogre@@@Z endp

; Renderer::getSceneManager();
?getSceneManager@Renderer@@QEBAPEAVSceneManager@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+11*8]
?getSceneManager@Renderer@@QEBAPEAVSceneManager@Ogre@@XZ endp

; Renderer::getRenderSystem();
?getRenderSystem@Renderer@@QEBAPEAVRenderSystem@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+12*8]
?getRenderSystem@Renderer@@QEBAPEAVRenderSystem@Ogre@@XZ endp

; Renderer::getRootSceneNode();
?getRootSceneNode@Renderer@@QEBAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+13*8]
?getRootSceneNode@Renderer@@QEBAPEAVSceneNode@Ogre@@XZ endp

; Renderer::getCamera();
?getCamera@Renderer@@QEBAPEAVCamera@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+14*8]
?getCamera@Renderer@@QEBAPEAVCamera@Ogre@@XZ endp

; Renderer::getViewport();
?getViewport@Renderer@@QEBAPEAVViewport@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+15*8]
?getViewport@Renderer@@QEBAPEAVViewport@Ogre@@XZ endp

; Renderer::getRoot();
?getRoot@Renderer@@QEBAPEAVRoot@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+16*8]
?getRoot@Renderer@@QEBAPEAVRoot@Ogre@@XZ endp

; Renderer::getScreenWidth();
?getScreenWidth@Renderer@@QEBAMXZ proc EXPORT
jmp function_pointers[_Renderer_base+17*8]
?getScreenWidth@Renderer@@QEBAMXZ endp

; Renderer::getScreenHeight();
?getScreenHeight@Renderer@@QEBAMXZ proc EXPORT
jmp function_pointers[_Renderer_base+18*8]
?getScreenHeight@Renderer@@QEBAMXZ endp

; Renderer::getWorkspace();
?getWorkspace@Renderer@@QEBAPEAVCompositorWorkspace@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+19*8]
?getWorkspace@Renderer@@QEBAPEAVCompositorWorkspace@Ogre@@XZ endp

; Renderer::getSceneRelativeOrigin();
?getSceneRelativeOrigin@Renderer@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Renderer_base+20*8]
?getSceneRelativeOrigin@Renderer@@QEBA?AVVector3@Ogre@@XZ endp

; Renderer::validateCompositor(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?validateCompositor@Renderer@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Renderer_base+21*8]
?validateCompositor@Renderer@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Renderer::setupPostProcessing(const struct Ogre::IdString &);
?setupPostProcessing@Renderer@@QEAAXAEBUIdString@Ogre@@@Z proc EXPORT
jmp function_pointers[_Renderer_base+22*8]
?setupPostProcessing@Renderer@@QEAAXAEBUIdString@Ogre@@@Z endp

; Renderer::refreshActiveCompositor();
?refreshActiveCompositor@Renderer@@QEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+23*8]
?refreshActiveCompositor@Renderer@@QEAAXXZ endp

; Renderer::getMeshInformation(const class Ogre::SubMesh * const, unsigned __int64 &, class Ogre::Vector3 * &, class Ogre::Vector2 * &, const class Ogre::Vector3 &, const class Ogre::Quaternion &, const class Ogre::Vector3 &);
?getMeshInformation@Renderer@@SAXQEBVSubMesh@Ogre@@AEA_KAEAPEAVVector3@3@AEAPEAVVector2@3@AEBV43@AEBVQuaternion@3@4@Z proc EXPORT
jmp function_pointers[_Renderer_base+24*8]
?getMeshInformation@Renderer@@SAXQEBVSubMesh@Ogre@@AEA_KAEAPEAVVector3@3@AEAPEAVVector2@3@AEBV43@AEBVQuaternion@3@4@Z endp

; Renderer::paintImageOnTexture(class Ogre::SharedPtr<Ogre::Texture>, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, int, int, float, bool, bool);
?paintImageOnTexture@Renderer@@QEAA_NV?$SharedPtr@VTexture@Ogre@@@Ogre@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHM_N2@Z proc EXPORT
jmp function_pointers[_Renderer_base+25*8]
?paintImageOnTexture@Renderer@@QEAA_NV?$SharedPtr@VTexture@Ogre@@@Ogre@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHM_N2@Z endp

; Renderer::setupConfig();
?setupConfig@Renderer@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Renderer_base+26*8]
?setupConfig@Renderer@@QEAA_NXZ endp

; Renderer::initPaintTextures();
?initPaintTextures@Renderer@@QEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+27*8]
?initPaintTextures@Renderer@@QEAAXXZ endp

; Renderer::setupResources();
?setupResources@Renderer@@QEAAXXZ proc EXPORT
jmp function_pointers[_Renderer_base+28*8]
?setupResources@Renderer@@QEAAXXZ endp
