
?_CONSTRUCTOR@RenderToTextureotron@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@RenderToTextureotron@@QEAAPEAV1@XZ endp

; RenderToTextureotron::RenderToTextureotron();
??0RenderToTextureotron@@QEAA@XZ proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+0*8]
??0RenderToTextureotron@@QEAA@XZ endp

?_DESTRUCTOR@RenderToTextureotron@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RenderToTextureotron@@QEAAXXZ endp

; RenderToTextureotron::~RenderToTextureotron();
??1RenderToTextureotron@@QEAA@XZ proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+1*8]
??1RenderToTextureotron@@QEAA@XZ endp

; RenderToTextureotron::createTexture(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class iVector2 &, bool);
?createTexture@RenderToTextureotron@@QEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBViVector2@@_N@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+2*8]
?createTexture@RenderToTextureotron@@QEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBViVector2@@_N@Z endp

; RenderToTextureotron::renderItem(class Item *, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class iVector2 &, const class iVector2 &, float, float, float, float);
?renderItem@RenderToTextureotron@@QEAA_NPEAVItem@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBViVector2@@3MMMM@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+3*8]
?renderItem@RenderToTextureotron@@QEAA_NPEAVItem@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBViVector2@@3MMMM@Z endp

; RenderToTextureotron::renderItem(class Item *, class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class iVector2 &);
?renderItem@RenderToTextureotron@@QEAAXPEAVItem@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAViVector2@@@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+4*8]
?renderItem@RenderToTextureotron@@QEAAXPEAVItem@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAViVector2@@@Z endp

; RenderToTextureotron::renderBuilding(class GameData *, class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class iVector2 &, float, float);
?renderBuilding@RenderToTextureotron@@QEAAXPEAVGameData@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBViVector2@@MM@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+5*8]
?renderBuilding@RenderToTextureotron@@QEAAXPEAVGameData@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBViVector2@@MM@Z endp

; symbol is too long
; ?createBuilding@RenderToTextureotron@@QEAAXPEAVSceneNode@Ogre@@PEAVGameData@@AEAV?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@boost@@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z
RenderToTextureotron_createBuilding_PLACEHOLDER proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+6*8]
RenderToTextureotron_createBuilding_PLACEHOLDER endp

; RenderToTextureotron::renderCharacter(class Character *, class Ogre::SharedPtr<Ogre::Texture>, const class iVector2 &, const struct Ogre::TRect<float> &);
?renderCharacter@RenderToTextureotron@@QEAAXPEAVCharacter@@V?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBViVector2@@AEBU?$TRect@M@4@@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+7*8]
?renderCharacter@RenderToTextureotron@@QEAAXPEAVCharacter@@V?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBViVector2@@AEBU?$TRect@M@4@@Z endp

; RenderToTextureotron::renderCharacterNPC(class Character *, const class iVector2 &, float);
?renderCharacterNPC@RenderToTextureotron@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@AEBViVector2@@M@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+8*8]
?renderCharacterNPC@RenderToTextureotron@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@AEBViVector2@@M@Z endp

; RenderToTextureotron::saveTexture(class Ogre::SharedPtr<Ogre::Texture>, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveTexture@RenderToTextureotron@@QEAAXV?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+9*8]
?saveTexture@RenderToTextureotron@@QEAAXV?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RenderToTextureotron::loadOrCreateTexture(class Ogre::SharedPtr<Ogre::Texture> &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class iVector2 &);
?loadOrCreateTexture@RenderToTextureotron@@QEAAXAEAV?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1AEBViVector2@@@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+10*8]
?loadOrCreateTexture@RenderToTextureotron@@QEAAXAEAV?$SharedPtr@VTexture@Ogre@@@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1AEBViVector2@@@Z endp

; RenderToTextureotron::buildAllItemsIcons();
?buildAllItemsIcons@RenderToTextureotron@@QEAAXXZ proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+11*8]
?buildAllItemsIcons@RenderToTextureotron@@QEAAXXZ endp

; RenderToTextureotron::setupSceneManager();
?setupSceneManager@RenderToTextureotron@@QEAAXXZ proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+12*8]
?setupSceneManager@RenderToTextureotron@@QEAAXXZ endp

; RenderToTextureotron::setupCamera(const class iVector2 &, float, float);
?setupCamera@RenderToTextureotron@@QEAAPEAVCamera@Ogre@@AEBViVector2@@MM@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+13*8]
?setupCamera@RenderToTextureotron@@QEAAPEAVCamera@Ogre@@AEBViVector2@@MM@Z endp

; RenderToTextureotron::getItemName(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class GameData *, class GameData *, class GameData *);
?getItemName@RenderToTextureotron@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@11@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+14*8]
?getItemName@RenderToTextureotron@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@11@Z endp

; RenderToTextureotron::createItemModel(class Item *, class GameData *);
?createItemModel@RenderToTextureotron@@QEAAPEAVEntity@Ogre@@PEAVItem@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RenderToTextureotron_base+15*8]
?createItemModel@RenderToTextureotron@@QEAAPEAVEntity@Ogre@@PEAVItem@@PEAVGameData@@@Z endp
