
?_CONSTRUCTOR@ResearchItem@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@ResearchItem@@QEAAPEAV1@PEAVGameData@@@Z endp

; ResearchItem::ResearchItem(class GameData *);
??0ResearchItem@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ResearchItem_base+0*8]
??0ResearchItem@@QEAA@PEAVGameData@@@Z endp

?_CONSTRUCTOR@ResearchItem@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ResearchItem@@QEAAPEAV1@XZ endp

; ResearchItem::ResearchItem();
??0ResearchItem@@QEAA@XZ proc EXPORT
jmp function_pointers[_ResearchItem_base+1*8]
??0ResearchItem@@QEAA@XZ endp

; ResearchItem::getCostItem(int);
?getCostItem@ResearchItem@@QEAAPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_ResearchItem_base+2*8]
?getCostItem@ResearchItem@@QEAAPEAVGameData@@H@Z endp

; ResearchItem::getCostItemQuantity(int);
?getCostItemQuantity@ResearchItem@@QEAAHH@Z proc EXPORT
jmp function_pointers[_ResearchItem_base+3*8]
?getCostItemQuantity@ResearchItem@@QEAAHH@Z endp

; ResearchItem::getNumDifferentCostItems();
?getNumDifferentCostItems@ResearchItem@@QEAAHXZ proc EXPORT
jmp function_pointers[_ResearchItem_base+4*8]
?getNumDifferentCostItems@ResearchItem@@QEAAHXZ endp
