
?_CONSTRUCTOR@Research@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Research@@QEAAPEAV1@XZ endp

; Research::Research();
??0Research@@QEAA@XZ proc EXPORT
jmp function_pointers[_Research_base+0*8]
??0Research@@QEAA@XZ endp

; Research::_reset();
?_reset@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+1*8]
?_reset@Research@@QEAAXXZ endp

; Research::_setup();
?_setup@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+2*8]
?_setup@Research@@QEAAXXZ endp

; Research::getAvailableCrafts(class lektor<GameDataGroup> &, enum itemType, enum itemType);
?getAvailableCrafts@Research@@QEAAXAEAV?$lektor@VGameDataGroup@@@@W4itemType@@1@Z proc EXPORT
jmp function_pointers[_Research_base+3*8]
?getAvailableCrafts@Research@@QEAAXAEAV?$lektor@VGameDataGroup@@@@W4itemType@@1@Z endp

; Research::getArmourCraftLevel(class GameData *, int, bool);
?getArmourCraftLevel@Research@@QEAAHPEAVGameData@@H_N@Z proc EXPORT
jmp function_pointers[_Research_base+4*8]
?getArmourCraftLevel@Research@@QEAAHPEAVGameData@@H_N@Z endp

; Research::getAvailableResearch(class lektor<GameData *> &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAvailableResearch@Research@@QEAAXAEAV?$lektor@PEAVGameData@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Research_base+5*8]
?getAvailableResearch@Research@@QEAAXAEAV?$lektor@PEAVGameData@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Research::getCategories();
?getCategories@Research@@QEBAAEBV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@XZ proc EXPORT
jmp function_pointers[_Research_base+6*8]
?getCategories@Research@@QEBAAEBV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@XZ endp

; Research::startResearch(class GameData *);
?startResearch@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+7*8]
?startResearch@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::stopResearch(class GameData *);
?stopResearch@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+8*8]
?stopResearch@Research@@QEAAXPEAVGameData@@@Z endp

; Research::getResearchProgress(class GameData *);
?getResearchProgress@Research@@QEAAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+9*8]
?getResearchProgress@Research@@QEAAMPEAVGameData@@@Z endp

; Research::getResearchProgress(const class ResearchItem *);
?getResearchProgress@Research@@QEBAMPEBVResearchItem@@@Z proc EXPORT
jmp function_pointers[_Research_base+10*8]
?getResearchProgress@Research@@QEBAMPEBVResearchItem@@@Z endp

; Research::completeResearch(class GameData *);
?completeResearch@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+11*8]
?completeResearch@Research@@QEAAXPEAVGameData@@@Z endp

; Research::isFinished(class GameData *);
?isFinished@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+12*8]
?isFinished@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::isBuildingResearched(class GameData *);
?isBuildingResearched@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+13*8]
?isBuildingResearched@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::getETA(class GameData *, bool);
?getETA@Research@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_Research_base+14*8]
?getETA@Research@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@_N@Z endp

; Research::payCosts(class GameData *);
?payCosts@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+15*8]
?payCosts@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::canPayCosts(class GameData *);
?canPayCosts@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+16*8]
?canPayCosts@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::getBlueprintsFor(class GameData *);
?getBlueprintsFor@Research@@QEAAPEAVGameData@@PEAV2@@Z proc EXPORT
jmp function_pointers[_Research_base+17*8]
?getBlueprintsFor@Research@@QEAAPEAVGameData@@PEAV2@@Z endp

; Research::staticUpdate();
?staticUpdate@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+18*8]
?staticUpdate@Research@@QEAAXXZ endp

; Research::getCurrentResearchRate();
?getCurrentResearchRate@Research@@QEBAMXZ proc EXPORT
jmp function_pointers[_Research_base+19*8]
?getCurrentResearchRate@Research@@QEBAMXZ endp

; Research::serialise(class GameData *);
?serialise@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+20*8]
?serialise@Research@@QEAAXPEAVGameData@@@Z endp

; Research::load(class GameData *);
?load@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+21*8]
?load@Research@@QEAAXPEAVGameData@@@Z endp

; Research::progressResearch(float);
?progressResearch@Research@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Research_base+22*8]
?progressResearch@Research@@QEAAXM@Z endp

; Research::checkRequirementsForInvisibility(class GameData *, bool);
?checkRequirementsForInvisibility@Research@@QEAA_NPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_Research_base+23*8]
?checkRequirementsForInvisibility@Research@@QEAA_NPEAVGameData@@_N@Z endp

; Research::checkRequirements(class GameData *, bool, bool);
?checkRequirements@Research@@QEAA_NPEAVGameData@@_N1@Z proc EXPORT
jmp function_pointers[_Research_base+24*8]
?checkRequirements@Research@@QEAA_NPEAVGameData@@_N1@Z endp

; Research::checkRequirements_andQueue(class GameData *);
?checkRequirements_andQueue@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+25*8]
?checkRequirements_andQueue@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::isInQueue(class GameData *);
?isInQueue@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+26*8]
?isInQueue@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::_updateTheAllList();
?_updateTheAllList@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+27*8]
?_updateTheAllList@Research@@QEAAXXZ endp

; Research::getResearchQueue();
?getResearchQueue@Research@@QEAAAEAV?$deque@VResearchItem@@V?$STLAllocator@VResearchItem@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@XZ proc EXPORT
jmp function_pointers[_Research_base+28*8]
?getResearchQueue@Research@@QEAAAEAV?$deque@VResearchItem@@V?$STLAllocator@VResearchItem@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@XZ endp

; Research::setResearchDeskLevel(int);
?setResearchDeskLevel@Research@@QEAAXH@Z proc EXPORT
jmp function_pointers[_Research_base+29*8]
?setResearchDeskLevel@Research@@QEAAXH@Z endp

; Research::refreshTheoreticalTechLevel();
?refreshTheoreticalTechLevel@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+30*8]
?refreshTheoreticalTechLevel@Research@@QEAAXXZ endp

; Research::needsATechBench(class GameData *);
?needsATechBench@Research@@QEAAHPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+31*8]
?needsATechBench@Research@@QEAAHPEAVGameData@@@Z endp

; Research::getUpgrades(const class Building *);
?getUpgrades@Research@@QEBAAEBVBuildingUpgrades@1@PEBVBuilding@@@Z proc EXPORT
jmp function_pointers[_Research_base+32*8]
?getUpgrades@Research@@QEBAAEBVBuildingUpgrades@1@PEBVBuilding@@@Z endp

; Research::hasPaidFor(class GameData *);
?hasPaidFor@Research@@QEBA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+33*8]
?hasPaidFor@Research@@QEBA_NPEAVGameData@@@Z endp

; Research::getResearchDeskLevel();
?getResearchDeskLevel@Research@@QEBAHXZ proc EXPORT
jmp function_pointers[_Research_base+34*8]
?getResearchDeskLevel@Research@@QEBAHXZ endp

; Research::hasArtifact(class GameData *, int);
?hasArtifact@Research@@QEAA_NPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_Research_base+35*8]
?hasArtifact@Research@@QEAA_NPEAVGameData@@H@Z endp

; Research::getResearchItem(class GameData *);
?getResearchItem@Research@@QEAA?AVResearchItem@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+36*8]
?getResearchItem@Research@@QEAA?AVResearchItem@@PEAVGameData@@@Z endp

; Research::getAllResearchBenches(class lektor<Building *> &);
?getAllResearchBenches@Research@@QEAAXAEAV?$lektor@PEAVBuilding@@@@@Z proc EXPORT
jmp function_pointers[_Research_base+37*8]
?getAllResearchBenches@Research@@QEAAXAEAV?$lektor@PEAVBuilding@@@@@Z endp

; Research::_deleteArtifact(class GameData *, int);
?_deleteArtifact@Research@@QEAAXPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_Research_base+38*8]
?_deleteArtifact@Research@@QEAAXPEAVGameData@@H@Z endp

; Research::deleteAllArtifactsFor(class GameData *);
?deleteAllArtifactsFor@Research@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+39*8]
?deleteAllArtifactsFor@Research@@QEAA_NPEAVGameData@@@Z endp

; Research::_updateTheEnabledItemsList();
?_updateTheEnabledItemsList@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+40*8]
?_updateTheEnabledItemsList@Research@@QEAAXXZ endp

; Research::cleanupQueue();
?cleanupQueue@Research@@QEAAXXZ proc EXPORT
jmp function_pointers[_Research_base+41*8]
?cleanupQueue@Research@@QEAAXXZ endp

; Research::removeFromQueue(class GameData *);
?removeFromQueue@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+42*8]
?removeFromQueue@Research@@QEAAXPEAVGameData@@@Z endp

; Research::upgradeShit(class GameData *);
?upgradeShit@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+43*8]
?upgradeShit@Research@@QEAAXPEAVGameData@@@Z endp

; Research::_createBlueprintsFor(class GameData *);
?_createBlueprintsFor@Research@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Research_base+44*8]
?_createBlueprintsFor@Research@@QEAAXPEAVGameData@@@Z endp

?_DESTRUCTOR@Research@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Research@@QEAAXXZ endp

; Research::~Research();
??1Research@@QEAA@XZ proc EXPORT
jmp function_pointers[_Research_base+45*8]
??1Research@@QEAA@XZ endp
