
?_CONSTRUCTOR@RobotLimbItem@@QEAAPEAV1@PEAVGameData@@0Vhand@@H@Z proc EXPORT
?_CONSTRUCTOR@RobotLimbItem@@QEAAPEAV1@PEAVGameData@@0Vhand@@H@Z endp

; RobotLimbItem::RobotLimbItem(class GameData *, class GameData *, class hand, int);
??0RobotLimbItem@@QEAA@PEAVGameData@@0Vhand@@H@Z proc EXPORT
jmp function_pointers[_RobotLimbItem_base+0*8]
??0RobotLimbItem@@QEAA@PEAVGameData@@0Vhand@@H@Z endp

; RobotLimbItem::getStatMult(enum StatsEnumerated);
?getStatMult@RobotLimbItem@@QEAAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_RobotLimbItem_base+1*8]
?getStatMult@RobotLimbItem@@QEAAMW4StatsEnumerated@@@Z endp

?_NV__serialise@RobotLimbItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@RobotLimbItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; RobotLimbItem::_serialise(class GameDataContainer *, enum itemType);
?_serialise@RobotLimbItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_RobotLimbItem_base+2*8]
?_serialise@RobotLimbItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_NV__loadFromSerialise@RobotLimbItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@RobotLimbItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; RobotLimbItem::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@RobotLimbItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RobotLimbItem_base+3*8]
?_loadFromSerialise@RobotLimbItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_getCraftTime@RobotLimbItem@@QEAAMXZ proc EXPORT
?_NV_getCraftTime@RobotLimbItem@@QEAAMXZ endp

; RobotLimbItem::getCraftTime();
?getCraftTime@RobotLimbItem@@UEAAMXZ proc EXPORT
jmp function_pointers[_RobotLimbItem_base+4*8]
?getCraftTime@RobotLimbItem@@UEAAMXZ endp

?_NV_getTooltipData1@RobotLimbItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@RobotLimbItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; RobotLimbItem::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@RobotLimbItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_RobotLimbItem_base+5*8]
?getTooltipData1@RobotLimbItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@RobotLimbItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@RobotLimbItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; RobotLimbItem::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@RobotLimbItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_RobotLimbItem_base+6*8]
?getTooltipData2@RobotLimbItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_DESTRUCTOR@RobotLimbItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RobotLimbItem@@QEAAXXZ endp

; RobotLimbItem::~RobotLimbItem();
??1RobotLimbItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_RobotLimbItem_base+7*8]
??1RobotLimbItem@@UEAA@XZ endp
