
?_CONSTRUCTOR@Season@@QEAAPEAV1@PEAVWeatherRegion@@PEAVGameData@@H@Z proc EXPORT
?_CONSTRUCTOR@Season@@QEAAPEAV1@PEAVWeatherRegion@@PEAVGameData@@H@Z endp

; Season::Season(class WeatherRegion *, class GameData *, int);
??0Season@@QEAA@PEAVWeatherRegion@@PEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_Season_base+0*8]
??0Season@@QEAA@PEAVWeatherRegion@@PEAVGameData@@H@Z endp

?_DESTRUCTOR@Season@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Season@@QEAAXXZ endp

; Season::~Season();
??1Season@@QEAA@XZ proc EXPORT
jmp function_pointers[_Season_base+1*8]
??1Season@@QEAA@XZ endp

; Season::getName();
?getName@Season@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Season_base+2*8]
?getName@Season@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Season::getNewWeather();
?getNewWeather@Season@@QEAAXXZ proc EXPORT
jmp function_pointers[_Season_base+3*8]
?getNewWeather@Season@@QEAAXXZ endp
