
?_CONSTRUCTOR@SeveredLimbItem@@QEAAPEAV1@PEAVGameData@@AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@SeveredLimbItem@@QEAAPEAV1@PEAVGameData@@AEBVhand@@@Z endp

; SeveredLimbItem::SeveredLimbItem(class GameData *, const class hand &);
??0SeveredLimbItem@@QEAA@PEAVGameData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+0*8]
??0SeveredLimbItem@@QEAA@PEAVGameData@@AEBVhand@@@Z endp

; SeveredLimbItem::setupFromCharacter(class Character *, int, const class Ogre::Vector3 &);
?setupFromCharacter@SeveredLimbItem@@QEAAXPEAVCharacter@@HAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+1*8]
?setupFromCharacter@SeveredLimbItem@@QEAAXPEAVCharacter@@HAEBVVector3@Ogre@@@Z endp

?_NV__serialise@SeveredLimbItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@SeveredLimbItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; SeveredLimbItem::_serialise(class GameDataContainer *, enum itemType);
?_serialise@SeveredLimbItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+2*8]
?_serialise@SeveredLimbItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_NV__loadFromSerialise@SeveredLimbItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@SeveredLimbItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; SeveredLimbItem::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@SeveredLimbItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+3*8]
?_loadFromSerialise@SeveredLimbItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_getTimeout@SeveredLimbItem@@QEBA?AVTimeOfDay@@XZ proc EXPORT
?_NV_getTimeout@SeveredLimbItem@@QEBA?AVTimeOfDay@@XZ endp

; SeveredLimbItem::getTimeout();
?getTimeout@SeveredLimbItem@@UEBA?AVTimeOfDay@@XZ proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+4*8]
?getTimeout@SeveredLimbItem@@UEBA?AVTimeOfDay@@XZ endp

?_NV_destroyPhysical@SeveredLimbItem@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@SeveredLimbItem@@QEAAXXZ endp

; SeveredLimbItem::destroyPhysical();
?destroyPhysical@SeveredLimbItem@@UEAAXXZ proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+5*8]
?destroyPhysical@SeveredLimbItem@@UEAAXXZ endp

?_NV_itemEntityCreated@SeveredLimbItem@@QEAAXPEAVEntity@Ogre@@@Z proc EXPORT
?_NV_itemEntityCreated@SeveredLimbItem@@QEAAXPEAVEntity@Ogre@@@Z endp

; SeveredLimbItem::itemEntityCreated(class Ogre::Entity *);
?itemEntityCreated@SeveredLimbItem@@UEAAXPEAVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+6*8]
?itemEntityCreated@SeveredLimbItem@@UEAAXPEAVEntity@Ogre@@@Z endp

?_DESTRUCTOR@SeveredLimbItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SeveredLimbItem@@QEAAXXZ endp

; SeveredLimbItem::~SeveredLimbItem();
??1SeveredLimbItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_SeveredLimbItem_base+7*8]
??1SeveredLimbItem@@UEAA@XZ endp
