
?_CONSTRUCTOR@SharedKing@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SharedKing@@QEAAPEAV1@XZ endp

; SharedKing::SharedKing();
??0SharedKing@@QEAA@XZ proc EXPORT
jmp function_pointers[_SharedKing_base+0*8]
??0SharedKing@@QEAA@XZ endp

?_DESTRUCTOR@SharedKing@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SharedKing@@QEAAXXZ endp

; SharedKing::~SharedKing();
??1SharedKing@@QEAA@XZ proc EXPORT
jmp function_pointers[_SharedKing_base+1*8]
??1SharedKing@@QEAA@XZ endp

; SharedKing::isLevelEditMode();
?isLevelEditMode@SharedKing@@QEAA_NXZ proc EXPORT
jmp function_pointers[_SharedKing_base+2*8]
?isLevelEditMode@SharedKing@@QEAA_NXZ endp
