
?_CONSTRUCTOR@StateBroadcastData@@QEAAPEAV1@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@StateBroadcastData@@QEAAPEAV1@PEAVCharacter@@@Z endp

; StateBroadcastData::StateBroadcastData(class Character *);
??0StateBroadcastData@@QEAA@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_StateBroadcastData_base+0*8]
??0StateBroadcastData@@QEAA@PEAVCharacter@@@Z endp

; StateBroadcastData::save(class GameData *);
?save@StateBroadcastData@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_StateBroadcastData_base+1*8]
?save@StateBroadcastData@@QEAAXPEAVGameData@@@Z endp

; StateBroadcastData::load(class GameData *);
?load@StateBroadcastData@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_StateBroadcastData_base+2*8]
?load@StateBroadcastData@@QEAAXPEAVGameData@@@Z endp

; StateBroadcastData::periodicUpdate();
?periodicUpdate@StateBroadcastData@@QEAAXXZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+3*8]
?periodicUpdate@StateBroadcastData@@QEAAXXZ endp

; StateBroadcastData::setSlaveState(enum SlaveStateEnum);
?setSlaveState@StateBroadcastData@@QEAAXW4SlaveStateEnum@@@Z proc EXPORT
jmp function_pointers[_StateBroadcastData_base+4*8]
?setSlaveState@StateBroadcastData@@QEAAXW4SlaveStateEnum@@@Z endp

; StateBroadcastData::getSlaveState();
?getSlaveState@StateBroadcastData@@QEBA?AW4SlaveStateEnum@@XZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+5*8]
?getSlaveState@StateBroadcastData@@QEBA?AW4SlaveStateEnum@@XZ endp

; StateBroadcastData::getSlaveStateHoursRemaining();
?getSlaveStateHoursRemaining@StateBroadcastData@@QEAAHXZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+6*8]
?getSlaveStateHoursRemaining@StateBroadcastData@@QEAAHXZ endp

; StateBroadcastData::notifyDisguiseBlown();
?notifyDisguiseBlown@StateBroadcastData@@QEAAXXZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+7*8]
?notifyDisguiseBlown@StateBroadcastData@@QEAAXXZ endp

; StateBroadcastData::isDisguiseBlown();
?isDisguiseBlown@StateBroadcastData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+8*8]
?isDisguiseBlown@StateBroadcastData@@QEAA_NXZ endp

; StateBroadcastData::isDisguised();
?isDisguised@StateBroadcastData@@QEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+9*8]
?isDisguised@StateBroadcastData@@QEAAPEAVFaction@@XZ endp

; StateBroadcastData::isHiddenIdentitySlave();
?isHiddenIdentitySlave@StateBroadcastData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+10*8]
?isHiddenIdentitySlave@StateBroadcastData@@QEBA_NXZ endp

; StateBroadcastData::getApparentFaction();
?getApparentFaction@StateBroadcastData@@QEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_StateBroadcastData_base+11*8]
?getApparentFaction@StateBroadcastData@@QEAAPEAVFaction@@XZ endp
