
?_CONSTRUCTOR@StateStringInfos@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@StateStringInfos@@QEAAPEAV1@XZ endp

; StateStringInfos::StateStringInfos();
??0StateStringInfos@@QEAA@XZ proc EXPORT
jmp function_pointers[_StateStringInfos_base+0*8]
??0StateStringInfos@@QEAA@XZ endp

; StateStringInfos::operator=(class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
??4StateStringInfos@@QEAAAEAV0@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_StateStringInfos_base+1*8]
??4StateStringInfos@@QEAAAEAV0@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@StateStringInfos@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@StateStringInfos@@QEAAXXZ endp

; StateStringInfos::~StateStringInfos();
??1StateStringInfos@@QEAA@XZ proc EXPORT
jmp function_pointers[_StateStringInfos_base+2*8]
??1StateStringInfos@@QEAA@XZ endp
