
; StateFunctionList::add(enum StateType, function  *);
?add@StateFunctionList@@QEAAXW4StateType@@P8AI@@EAA_NAEBVhand@@AEBVVector3@Ogre@@@Z@Z proc EXPORT
jmp function_pointers[_StateFunctionList_base+0*8]
?add@StateFunctionList@@QEAAXW4StateType@@P8AI@@EAA_NAEBVhand@@AEBVVector3@Ogre@@@Z@Z endp

; StateFunctionList::isTrue(class AI *, enum StateType, const class hand &, const class Ogre::Vector3 &, bool);
?isTrue@StateFunctionList@@QEAA_NPEAVAI@@W4StateType@@AEBVhand@@AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_StateFunctionList_base+1*8]
?isTrue@StateFunctionList@@QEAA_NPEAVAI@@W4StateType@@AEBVhand@@AEBVVector3@Ogre@@_N@Z endp

; StateFunctionList::hasState(enum StateType);
?hasState@StateFunctionList@@QEAA_NW4StateType@@@Z proc EXPORT
jmp function_pointers[_StateFunctionList_base+2*8]
?hasState@StateFunctionList@@QEAA_NW4StateType@@@Z endp

?_CONSTRUCTOR@StateFunctionList@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@StateFunctionList@@QEAAPEAV1@XZ endp

; StateFunctionList::StateFunctionList();
??0StateFunctionList@@QEAA@XZ proc EXPORT
jmp function_pointers[_StateFunctionList_base+3*8]
??0StateFunctionList@@QEAA@XZ endp

?_DESTRUCTOR@StateFunctionList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@StateFunctionList@@QEAAXXZ endp

; StateFunctionList::~StateFunctionList();
??1StateFunctionList@@QEAA@XZ proc EXPORT
jmp function_pointers[_StateFunctionList_base+4*8]
??1StateFunctionList@@QEAA@XZ endp
