
; TargetInfo::setupType();
?setupType@TargetInfo@@QEAAXXZ proc EXPORT
jmp function_pointers[_TargetInfo_base+0*8]
?setupType@TargetInfo@@QEAAXXZ endp

?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@AEBV1@@Z endp

; TargetInfo::TargetInfo(const class TargetInfo &);
??0TargetInfo@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_TargetInfo_base+1*8]
??0TargetInfo@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@AEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@AEBVhand@@AEBVVector3@Ogre@@@Z endp

; TargetInfo::TargetInfo(const class hand &, const class Ogre::Vector3 &);
??0TargetInfo@@QEAA@AEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TargetInfo_base+2*8]
??0TargetInfo@@QEAA@AEBVhand@@AEBVVector3@Ogre@@@Z endp

?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@AEBVhand@@@Z endp

; TargetInfo::TargetInfo(const class hand &);
??0TargetInfo@@QEAA@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_TargetInfo_base+3*8]
??0TargetInfo@@QEAA@AEBVhand@@@Z endp

?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@H@Z endp

; TargetInfo::TargetInfo(int);
??0TargetInfo@@QEAA@H@Z proc EXPORT
jmp function_pointers[_TargetInfo_base+4*8]
??0TargetInfo@@QEAA@H@Z endp

?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TargetInfo@@QEAAPEAV1@XZ endp

; TargetInfo::TargetInfo();
??0TargetInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_TargetInfo_base+5*8]
??0TargetInfo@@QEAA@XZ endp

; TargetInfo::operator=(const class hand &);
??4TargetInfo@@QEAAAEBV0@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_TargetInfo_base+6*8]
??4TargetInfo@@QEAAAEBV0@AEBVhand@@@Z endp

; TargetInfo::operator bool();
??BTargetInfo@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TargetInfo_base+7*8]
??BTargetInfo@@QEBA_NXZ endp

; TargetInfo::isTown();
?isTown@TargetInfo@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TargetInfo_base+8*8]
?isTown@TargetInfo@@QEBA_NXZ endp

; TargetInfo::isCharacter();
?isCharacter@TargetInfo@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TargetInfo_base+9*8]
?isCharacter@TargetInfo@@QEBA_NXZ endp

; TargetInfo::getTown();
?getTown@TargetInfo@@QEBAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_TargetInfo_base+10*8]
?getTown@TargetInfo@@QEBAPEAVTownBase@@XZ endp

; TargetInfo::getCharacter();
?getCharacter@TargetInfo@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_TargetInfo_base+11*8]
?getCharacter@TargetInfo@@QEBAPEAVCharacter@@XZ endp

; TargetInfo::getPositionForWaypoint(const class Ogre::Vector3 &);
?getPositionForWaypoint@TargetInfo@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_TargetInfo_base+12*8]
?getPositionForWaypoint@TargetInfo@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp
