
?_CONSTRUCTOR@TargetWithScore@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@TargetWithScore@@QEAAPEAV1@AEBV1@@Z endp

; TargetWithScore::TargetWithScore(const class TargetWithScore &);
??0TargetWithScore@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_TargetWithScore_base+0*8]
??0TargetWithScore@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@TargetWithScore@@QEAAPEAV1@AEBVhand@@M@Z proc EXPORT
?_CONSTRUCTOR@TargetWithScore@@QEAAPEAV1@AEBVhand@@M@Z endp

; TargetWithScore::TargetWithScore(const class hand &, float);
??0TargetWithScore@@QEAA@AEBVhand@@M@Z proc EXPORT
jmp function_pointers[_TargetWithScore_base+1*8]
??0TargetWithScore@@QEAA@AEBVhand@@M@Z endp

; TargetWithScore::operator=(const class TargetWithScore &);
??4TargetWithScore@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_TargetWithScore_base+2*8]
??4TargetWithScore@@QEAAAEAV0@AEBV0@@Z endp
