
?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@AEBV1@@Z endp

; TaskMatch::TaskMatch(const class TaskMatch &);
??0TaskMatch@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+0*8]
??0TaskMatch@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@PEAVTasker@@@Z proc EXPORT
?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@PEAVTasker@@@Z endp

; TaskMatch::TaskMatch(class Tasker *);
??0TaskMatch@@QEAA@PEAVTasker@@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+1*8]
??0TaskMatch@@QEAA@PEAVTasker@@@Z endp

?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@PEBVTaskData@@AEBVhand@@1@Z proc EXPORT
?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@PEBVTaskData@@AEBVhand@@1@Z endp

; TaskMatch::TaskMatch(const class TaskData *, const class hand &, const class hand &);
??0TaskMatch@@QEAA@PEBVTaskData@@AEBVhand@@1@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+2*8]
??0TaskMatch@@QEAA@PEBVTaskData@@AEBVhand@@1@Z endp

?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TaskMatch@@QEAAPEAV1@XZ endp

; TaskMatch::TaskMatch();
??0TaskMatch@@QEAA@XZ proc EXPORT
jmp function_pointers[_TaskMatch_base+3*8]
??0TaskMatch@@QEAA@XZ endp

; TaskMatch::getTaskData();
?getTaskData@TaskMatch@@QEBAPEBVTaskData@@XZ proc EXPORT
jmp function_pointers[_TaskMatch_base+4*8]
?getTaskData@TaskMatch@@QEBAPEBVTaskData@@XZ endp

; TaskMatch::key();
?key@TaskMatch@@QEBA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_TaskMatch_base+5*8]
?key@TaskMatch@@QEBA?AW4TaskType@@XZ endp

; TaskMatch::operator=(class Tasker *);
??4TaskMatch@@QEAAAEAV0@PEAVTasker@@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+6*8]
??4TaskMatch@@QEAAAEAV0@PEAVTasker@@@Z endp

; TaskMatch::operator=(int);
??4TaskMatch@@QEAAAEAV0@H@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+7*8]
??4TaskMatch@@QEAAAEAV0@H@Z endp

; TaskMatch::reset();
?reset@TaskMatch@@QEAAXXZ proc EXPORT
jmp function_pointers[_TaskMatch_base+8*8]
?reset@TaskMatch@@QEAAXXZ endp

; TaskMatch::operator==(const class Tasker *);
??8TaskMatch@@QEBA_NPEBVTasker@@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+9*8]
??8TaskMatch@@QEBA_NPEBVTasker@@@Z endp

; TaskMatch::operator!=(const class Tasker *);
??9TaskMatch@@QEBA_NPEBVTasker@@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+10*8]
??9TaskMatch@@QEBA_NPEBVTasker@@@Z endp

; TaskMatch::sameAs(const class Tasker *);
?sameAs@TaskMatch@@QEBA_NPEBVTasker@@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+11*8]
?sameAs@TaskMatch@@QEBA_NPEBVTasker@@@Z endp

; TaskMatch::operator<(const class TaskMatch &);
??MTaskMatch@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TaskMatch_base+12*8]
??MTaskMatch@@QEBA_NAEBV0@@Z endp

; TaskMatch::operator bool();
??BTaskMatch@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TaskMatch_base+13*8]
??BTaskMatch@@QEBA_NXZ endp
