
?_CONSTRUCTOR@Node@TaskPathfinder@@QEAAPEAV12@W4TaskType@@AEBVhand@@AEBVVector3@Ogre@@_NPEAV2@@Z proc EXPORT
?_CONSTRUCTOR@Node@TaskPathfinder@@QEAAPEAV12@W4TaskType@@AEBVhand@@AEBVVector3@Ogre@@_NPEAV2@@Z endp

; TaskPathfinder::Node::Node(enum TaskType, const class hand &, const class Ogre::Vector3 &, bool, class TaskPathfinder *);
??0Node@TaskPathfinder@@QEAA@W4TaskType@@AEBVhand@@AEBVVector3@Ogre@@_NPEAV1@@Z proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+0*8]
??0Node@TaskPathfinder@@QEAA@W4TaskType@@AEBVhand@@AEBVVector3@Ogre@@_NPEAV1@@Z endp

; TaskPathfinder::Node::getFirstSuccessorList();
?getFirstSuccessorList@Node@TaskPathfinder@@QEAAAEAV?$lektor@PEAVNode@TaskPathfinder@@@@XZ proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+1*8]
?getFirstSuccessorList@Node@TaskPathfinder@@QEAAAEAV?$lektor@PEAVNode@TaskPathfinder@@@@XZ endp

; TaskPathfinder::Node::satisfiesState(class TaskStateData *);
?satisfiesState@Node@TaskPathfinder@@QEAA_NPEAVTaskStateData@@@Z proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+2*8]
?satisfiesState@Node@TaskPathfinder@@QEAA_NPEAVTaskStateData@@@Z endp

; TaskPathfinder::Node::getScore(const class hand &, class Ogre::Vector3 &);
?getScore@Node@TaskPathfinder@@QEAAMAEBVhand@@AEAVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+3*8]
?getScore@Node@TaskPathfinder@@QEAAMAEBVhand@@AEAVVector3@Ogre@@@Z endp

; TaskPathfinder::Node::calculateSuccessorNodes();
?calculateSuccessorNodes@Node@TaskPathfinder@@QEAA_NXZ proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+4*8]
?calculateSuccessorNodes@Node@TaskPathfinder@@QEAA_NXZ endp

; TaskPathfinder::Node::queryScoreSoFar(class TaskPathfinder::Node *);
?queryScoreSoFar@Node@TaskPathfinder@@QEAAMPEAV12@@Z proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+5*8]
?queryScoreSoFar@Node@TaskPathfinder@@QEAAMPEAV12@@Z endp

; TaskPathfinder::Node::setParent(class TaskPathfinder::Node *);
?setParent@Node@TaskPathfinder@@QEAAXPEAV12@@Z proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+6*8]
?setParent@Node@TaskPathfinder@@QEAAXPEAV12@@Z endp

; TaskPathfinder::Node::getTask();
?getTask@Node@TaskPathfinder@@QEAAPEAVTaskData@@XZ proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+7*8]
?getTask@Node@TaskPathfinder@@QEAAPEAVTaskData@@XZ endp

; TaskPathfinder::Node::sameAs(const class TaskPathfinder::Node &);
?sameAs@Node@TaskPathfinder@@QEBA_NAEBV12@@Z proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+8*8]
?sameAs@Node@TaskPathfinder@@QEBA_NAEBV12@@Z endp

?_DESTRUCTOR@Node@TaskPathfinder@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Node@TaskPathfinder@@QEAAXXZ endp

; TaskPathfinder::Node::~Node();
??1Node@TaskPathfinder@@QEAA@XZ proc EXPORT
jmp function_pointers[_TaskPathfinder_Node_base+9*8]
??1Node@TaskPathfinder@@QEAA@XZ endp
