
?_CONSTRUCTOR@TaskRepertoire@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@TaskRepertoire@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; TaskRepertoire::TaskRepertoire(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0TaskRepertoire@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_TaskRepertoire_base+0*8]
??0TaskRepertoire@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@TaskRepertoire@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TaskRepertoire@@QEAAXXZ endp

; TaskRepertoire::~TaskRepertoire();
??1TaskRepertoire@@UEAA@XZ proc EXPORT
jmp function_pointers[_TaskRepertoire_base+1*8]
??1TaskRepertoire@@UEAA@XZ endp

; TaskRepertoire::getTaskData(enum TaskType);
?getTaskData@TaskRepertoire@@QEAAPEAVTaskData@@W4TaskType@@@Z proc EXPORT
jmp function_pointers[_TaskRepertoire_base+2*8]
?getTaskData@TaskRepertoire@@QEAAPEAVTaskData@@W4TaskType@@@Z endp

?_NV_hasTask@TaskRepertoire@@QEAA_NW4TaskType@@@Z proc EXPORT
?_NV_hasTask@TaskRepertoire@@QEAA_NW4TaskType@@@Z endp

; TaskRepertoire::hasTask(enum TaskType);
?hasTask@TaskRepertoire@@UEAA_NW4TaskType@@@Z proc EXPORT
jmp function_pointers[_TaskRepertoire_base+3*8]
?hasTask@TaskRepertoire@@UEAA_NW4TaskType@@@Z endp

; TaskRepertoire::getTasksWithResult(class TaskStateData *);
?getTasksWithResult@TaskRepertoire@@QEAAPEBV?$vector@PEAVTaskData@@V?$STLAllocator@PEAVTaskData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVTaskStateData@@@Z proc EXPORT
jmp function_pointers[_TaskRepertoire_base+4*8]
?getTasksWithResult@TaskRepertoire@@QEAAPEBV?$vector@PEAVTaskData@@V?$STLAllocator@PEAVTaskData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVTaskStateData@@@Z endp

; TaskRepertoire::initialiseOnceEverythingIsAdded();
?initialiseOnceEverythingIsAdded@TaskRepertoire@@QEAAXXZ proc EXPORT
jmp function_pointers[_TaskRepertoire_base+5*8]
?initialiseOnceEverythingIsAdded@TaskRepertoire@@QEAAXXZ endp
