
; TaskRequest::sameAs(class Tasker *);
?sameAs@TaskRequest@@QEBA_NPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_TaskRequest_base+0*8]
?sameAs@TaskRequest@@QEBA_NPEAVTasker@@@Z endp

; TaskRequest::operator==(const class TaskRequest &);
??8TaskRequest@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TaskRequest_base+1*8]
??8TaskRequest@@QEBA_NAEBV0@@Z endp

?_CONSTRUCTOR@TaskRequest@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@TaskRequest@@QEAAPEAV1@AEBV1@@Z endp

; TaskRequest::TaskRequest(const class TaskRequest &);
??0TaskRequest@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_TaskRequest_base+2*8]
??0TaskRequest@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@TaskRequest@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TaskRequest@@QEAAPEAV1@XZ endp

; TaskRequest::TaskRequest();
??0TaskRequest@@QEAA@XZ proc EXPORT
jmp function_pointers[_TaskRequest_base+3*8]
??0TaskRequest@@QEAA@XZ endp

; TaskRequest::operator=(const class TaskRequest &);
??4TaskRequest@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_TaskRequest_base+4*8]
??4TaskRequest@@QEAAAEAV0@AEBV0@@Z endp
