
?_CONSTRUCTOR@TownHandleContainerList@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@TownHandleContainerList@@QEAAPEAV1@H@Z endp

; TownHandleContainerList::TownHandleContainerList(int);
??0TownHandleContainerList@@QEAA@H@Z proc EXPORT
jmp function_pointers[_TownHandleContainerList_base+0*8]
??0TownHandleContainerList@@QEAA@H@Z endp

?_NV_compareSerials@TownHandleContainerList@@QEBA_NAEBVhand@@0@Z proc EXPORT
?_NV_compareSerials@TownHandleContainerList@@QEBA_NAEBVhand@@0@Z endp

; TownHandleContainerList::compareSerials(const class hand &, const class hand &);
?compareSerials@TownHandleContainerList@@UEBA_NAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_TownHandleContainerList_base+1*8]
?compareSerials@TownHandleContainerList@@UEBA_NAEBVhand@@0@Z endp

?_DESTRUCTOR@TownHandleContainerList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TownHandleContainerList@@QEAAXXZ endp

; TownHandleContainerList::~TownHandleContainerList();
??1TownHandleContainerList@@UEAA@XZ proc EXPORT
jmp function_pointers[_TownHandleContainerList_base+2*8]
??1TownHandleContainerList@@UEAA@XZ endp
