
?_CONSTRUCTOR@WaitingStateAI@@QEAAPEAV1@PEAVCombatClass@@@Z proc EXPORT
?_CONSTRUCTOR@WaitingStateAI@@QEAAPEAV1@PEAVCombatClass@@@Z endp

; WaitingStateAI::WaitingStateAI(class CombatClass *);
??0WaitingStateAI@@QEAA@PEAVCombatClass@@@Z proc EXPORT
jmp function_pointers[_WaitingStateAI_base+0*8]
??0WaitingStateAI@@QEAA@PEAVCombatClass@@@Z endp

?_NV_validate@WaitingStateAI@@QEAA_NXZ proc EXPORT
?_NV_validate@WaitingStateAI@@QEAA_NXZ endp

; WaitingStateAI::validate();
?validate@WaitingStateAI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_WaitingStateAI_base+1*8]
?validate@WaitingStateAI@@UEAA_NXZ endp

?_NV_initialise@WaitingStateAI@@QEAA_NXZ proc EXPORT
?_NV_initialise@WaitingStateAI@@QEAA_NXZ endp

; WaitingStateAI::initialise();
?initialise@WaitingStateAI@@UEAA_NXZ proc EXPORT
jmp function_pointers[_WaitingStateAI_base+2*8]
?initialise@WaitingStateAI@@UEAA_NXZ endp

?_NV_update@WaitingStateAI@@QEAAXM@Z proc EXPORT
?_NV_update@WaitingStateAI@@QEAAXM@Z endp

; WaitingStateAI::update(float);
?update@WaitingStateAI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_WaitingStateAI_base+3*8]
?update@WaitingStateAI@@UEAAXM@Z endp

?_NV_end@WaitingStateAI@@QEAAXXZ proc EXPORT
?_NV_end@WaitingStateAI@@QEAAXXZ endp

; WaitingStateAI::end();
?end@WaitingStateAI@@UEAAXXZ proc EXPORT
jmp function_pointers[_WaitingStateAI_base+4*8]
?end@WaitingStateAI@@UEAAXXZ endp
