
?_CONSTRUCTOR@FogValues@WeatherSystem@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@FogValues@WeatherSystem@@QEAAPEAV12@XZ endp

; WeatherSystem::FogValues::FogValues();
??0FogValues@WeatherSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_WeatherSystem_FogValues_base+0*8]
??0FogValues@WeatherSystem@@QEAA@XZ endp

; WeatherSystem::FogValues::lerp(const struct WeatherSystem::FogValues &, const struct WeatherSystem::FogValues &, const float);
?lerp@FogValues@WeatherSystem@@SA?AU12@AEBU12@0M@Z proc EXPORT
jmp function_pointers[_WeatherSystem_FogValues_base+1*8]
?lerp@FogValues@WeatherSystem@@SA?AU12@AEBU12@0M@Z endp
