
?_CONSTRUCTOR@ZoneFog@WeatherSystem@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ZoneFog@WeatherSystem@@QEAAPEAV12@XZ endp

; WeatherSystem::ZoneFog::ZoneFog();
??0ZoneFog@WeatherSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_WeatherSystem_ZoneFog_base+0*8]
??0ZoneFog@WeatherSystem@@QEAA@XZ endp

; WeatherSystem::ZoneFog::clear();
?clear@ZoneFog@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_ZoneFog_base+1*8]
?clear@ZoneFog@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::ZoneFog::set(class AreaBiomeGroup *, const class MainFog *);
?set@ZoneFog@WeatherSystem@@QEAAXPEAVAreaBiomeGroup@@PEBVMainFog@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_ZoneFog_base+2*8]
?set@ZoneFog@WeatherSystem@@QEAAXPEAVAreaBiomeGroup@@PEBVMainFog@@@Z endp

; WeatherSystem::ZoneFog::getCurrentValues();
?getCurrentValues@ZoneFog@WeatherSystem@@QEBA?AUFogValues@2@XZ proc EXPORT
jmp function_pointers[_WeatherSystem_ZoneFog_base+3*8]
?getCurrentValues@ZoneFog@WeatherSystem@@QEBA?AUFogValues@2@XZ endp

; WeatherSystem::ZoneFog::update();
?update@ZoneFog@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_ZoneFog_base+4*8]
?update@ZoneFog@WeatherSystem@@QEAAXXZ endp
