
?_DESTRUCTOR@WeatherSystem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::~WeatherSystem();
??1WeatherSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+0*8]
??1WeatherSystem@@QEAA@XZ endp

; WeatherSystem::getInstance();
?getInstance@WeatherSystem@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+1*8]
?getInstance@WeatherSystem@@SAPEAV1@XZ endp

; WeatherSystem::destroy();
?destroy@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+2*8]
?destroy@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::reset();
?reset@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+3*8]
?reset@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::updateMT();
?updateMT@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+4*8]
?updateMT@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::updateBT();
?updateBT@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+5*8]
?updateBT@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::updateUT();
?updateUT@WeatherSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+6*8]
?updateUT@WeatherSystem@@QEAAXXZ endp

; WeatherSystem::addWeatherListener(const class Ogre::Vector3 &, class WeatherRegion::Listener *);
?addWeatherListener@WeatherSystem@@QEAAXAEBVVector3@Ogre@@PEAVListener@WeatherRegion@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+7*8]
?addWeatherListener@WeatherSystem@@QEAAXAEBVVector3@Ogre@@PEAVListener@WeatherRegion@@@Z endp

; WeatherSystem::addWeatherListener(class GameData *, class WeatherRegion::Listener *);
?addWeatherListener@WeatherSystem@@QEAAXPEAVGameData@@PEAVListener@WeatherRegion@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+8*8]
?addWeatherListener@WeatherSystem@@QEAAXPEAVGameData@@PEAVListener@WeatherRegion@@@Z endp

; WeatherSystem::removeWeatherListener(class WeatherRegion::Listener *);
?removeWeatherListener@WeatherSystem@@QEAAXPEAVListener@WeatherRegion@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+9*8]
?removeWeatherListener@WeatherSystem@@QEAAXPEAVListener@WeatherRegion@@@Z endp

; WeatherSystem::getPositionGlobalEffects(const class Ogre::Vector3 &);
?getPositionGlobalEffects@WeatherSystem@@QEBAAEBV?$vector@U?$pair@W4Enum@EffectType@@M@std@@V?$STLAllocator@U?$pair@W4Enum@EffectType@@M@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+10*8]
?getPositionGlobalEffects@WeatherSystem@@QEBAAEBV?$vector@U?$pair@W4Enum@EffectType@@M@std@@V?$STLAllocator@U?$pair@W4Enum@EffectType@@M@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEBVVector3@Ogre@@@Z endp

; WeatherSystem::addWeatherEffect(class EffectHandler *);
?addWeatherEffect@WeatherSystem@@QEAAXPEAVEffectHandler@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+11*8]
?addWeatherEffect@WeatherSystem@@QEAAXPEAVEffectHandler@@@Z endp

; WeatherSystem::removeWeatherEffect(class EffectHandler *);
?removeWeatherEffect@WeatherSystem@@QEAAXPEAVEffectHandler@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+12*8]
?removeWeatherEffect@WeatherSystem@@QEAAXPEAVEffectHandler@@@Z endp

; WeatherSystem::setDustShaderValue(const class Ogre::Vector3 &);
?setDustShaderValue@WeatherSystem@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_WeatherSystem_base+13*8]
?setDustShaderValue@WeatherSystem@@QEAAXAEBVVector3@Ogre@@@Z endp

?_CONSTRUCTOR@WeatherSystem@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@WeatherSystem@@QEAAPEAV1@XZ endp

; WeatherSystem::WeatherSystem();
??0WeatherSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_WeatherSystem_base+14*8]
??0WeatherSystem@@QEAA@XZ endp
