
?_CONSTRUCTOR@Smell@ZoneSmell@@QEAAPEAV12@MM@Z proc EXPORT
?_CONSTRUCTOR@Smell@ZoneSmell@@QEAAPEAV12@MM@Z endp

; ZoneSmell::Smell::Smell(float, float);
??0Smell@ZoneSmell@@QEAA@MM@Z proc EXPORT
jmp function_pointers[_ZoneSmell_Smell_base+0*8]
??0Smell@ZoneSmell@@QEAA@MM@Z endp

?_NV_update@Smell@ZoneSmell@@QEAAXM@Z proc EXPORT
?_NV_update@Smell@ZoneSmell@@QEAAXM@Z endp

; ZoneSmell::Smell::update(float);
?update@Smell@ZoneSmell@@UEAAXM@Z proc EXPORT
jmp function_pointers[_ZoneSmell_Smell_base+1*8]
?update@Smell@ZoneSmell@@UEAAXM@Z endp
