
?_CONSTRUCTOR@ZoneMapHandleContainerList@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@ZoneMapHandleContainerList@@QEAAPEAV1@H@Z endp

; ZoneMapHandleContainerList::ZoneMapHandleContainerList(int);
??0ZoneMapHandleContainerList@@QEAA@H@Z proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+0*8]
??0ZoneMapHandleContainerList@@QEAA@H@Z endp

; ZoneMapHandleContainerList::getZoneMap(const class hand &);
?getZoneMap@ZoneMapHandleContainerList@@QEBAPEAVZoneMapContent@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+1*8]
?getZoneMap@ZoneMapHandleContainerList@@QEBAPEAVZoneMapContent@@AEBVhand@@@Z endp

; ZoneMapHandleContainerList::getObject(const class hand &);
?getObject@ZoneMapHandleContainerList@@QEBAPEAVRootObject@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+2*8]
?getObject@ZoneMapHandleContainerList@@QEBAPEAVRootObject@@AEBVhand@@@Z endp

?_NV_setUnloaded@ZoneMapHandleContainerList@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setUnloaded@ZoneMapHandleContainerList@@QEAAXAEBVhand@@@Z endp

; ZoneMapHandleContainerList::setUnloaded(const class hand &);
?setUnloaded@ZoneMapHandleContainerList@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+3*8]
?setUnloaded@ZoneMapHandleContainerList@@UEAAXAEBVhand@@@Z endp

?_NV_destroy@ZoneMapHandleContainerList@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_destroy@ZoneMapHandleContainerList@@QEAAXAEBVhand@@@Z endp

; ZoneMapHandleContainerList::destroy(const class hand &);
?destroy@ZoneMapHandleContainerList@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+4*8]
?destroy@ZoneMapHandleContainerList@@UEAAXAEBVhand@@@Z endp

; ZoneMapHandleContainerList::getCorrectHandleList(const class hand &);
?getCorrectHandleList@ZoneMapHandleContainerList@@QEBAPEAVHandleList@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+5*8]
?getCorrectHandleList@ZoneMapHandleContainerList@@QEBAPEAVHandleList@@AEBVhand@@@Z endp

?_DESTRUCTOR@ZoneMapHandleContainerList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ZoneMapHandleContainerList@@QEAAXXZ endp

; ZoneMapHandleContainerList::~ZoneMapHandleContainerList();
??1ZoneMapHandleContainerList@@UEAA@XZ proc EXPORT
jmp function_pointers[_ZoneMapHandleContainerList_base+6*8]
??1ZoneMapHandleContainerList@@UEAA@XZ endp
