
?_CONSTRUCTOR@HandleDummy@ZoneMapContent@@QEAAPEAV12@PEAV2@@Z proc EXPORT
?_CONSTRUCTOR@HandleDummy@ZoneMapContent@@QEAAPEAV12@PEAV2@@Z endp

; ZoneMapContent::HandleDummy::HandleDummy(class ZoneMapContent *);
??0HandleDummy@ZoneMapContent@@QEAA@PEAV1@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_HandleDummy_base+0*8]
??0HandleDummy@ZoneMapContent@@QEAA@PEAV1@@Z endp

?_NV_getDataType@HandleDummy@ZoneMapContent@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@HandleDummy@ZoneMapContent@@QEBA?AW4itemType@@XZ endp

; ZoneMapContent::HandleDummy::getDataType();
?getDataType@HandleDummy@ZoneMapContent@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_HandleDummy_base+1*8]
?getDataType@HandleDummy@ZoneMapContent@@UEBA?AW4itemType@@XZ endp

?_NV_serialise@HandleDummy@ZoneMapContent@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@HandleDummy@ZoneMapContent@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; ZoneMapContent::HandleDummy::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@HandleDummy@ZoneMapContent@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_HandleDummy_base+2*8]
?serialise@HandleDummy@ZoneMapContent@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@HandleDummy@ZoneMapContent@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@HandleDummy@ZoneMapContent@@QEAAXPEAVGameSaveState@@@Z endp

; ZoneMapContent::HandleDummy::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@HandleDummy@ZoneMapContent@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_HandleDummy_base+3*8]
?loadFromSerialise@HandleDummy@ZoneMapContent@@UEAAXPEAVGameSaveState@@@Z endp

?_DESTRUCTOR@HandleDummy@ZoneMapContent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@HandleDummy@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::HandleDummy::~HandleDummy();
??1HandleDummy@ZoneMapContent@@UEAA@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_HandleDummy_base+4*8]
??1HandleDummy@ZoneMapContent@@UEAA@XZ endp
