
?_CONSTRUCTOR@ZoneMapContentOrderLoader@ZoneMapContent@@QEAAPEAV12@_N@Z proc EXPORT
?_CONSTRUCTOR@ZoneMapContentOrderLoader@ZoneMapContent@@QEAAPEAV12@_N@Z endp

; ZoneMapContent::ZoneMapContentOrderLoader::ZoneMapContentOrderLoader(bool);
??0ZoneMapContentOrderLoader@ZoneMapContent@@QEAA@_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_ZoneMapContentOrderLoader_base+0*8]
??0ZoneMapContentOrderLoader@ZoneMapContent@@QEAA@_N@Z endp

?_NV_shouldSkip@ZoneMapContentOrderLoader@ZoneMapContent@@QEAA_NPEAVGameSaveState@@@Z proc EXPORT
?_NV_shouldSkip@ZoneMapContentOrderLoader@ZoneMapContent@@QEAA_NPEAVGameSaveState@@@Z endp

; ZoneMapContent::ZoneMapContentOrderLoader::shouldSkip(class GameSaveState *);
?shouldSkip@ZoneMapContentOrderLoader@ZoneMapContent@@UEAA_NPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_ZoneMapContentOrderLoader_base+1*8]
?shouldSkip@ZoneMapContentOrderLoader@ZoneMapContent@@UEAA_NPEAVGameSaveState@@@Z endp

?_DESTRUCTOR@ZoneMapContentOrderLoader@ZoneMapContent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ZoneMapContentOrderLoader@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::ZoneMapContentOrderLoader::~ZoneMapContentOrderLoader();
??1ZoneMapContentOrderLoader@ZoneMapContent@@QEAA@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_ZoneMapContentOrderLoader_base+2*8]
??1ZoneMapContentOrderLoader@ZoneMapContent@@QEAA@XZ endp
