
?_CONSTRUCTOR@ZoneSmell@@QEAAPEAV1@PEAVZoneMap@@@Z proc EXPORT
?_CONSTRUCTOR@ZoneSmell@@QEAAPEAV1@PEAVZoneMap@@@Z endp

; ZoneSmell::ZoneSmell(class ZoneMap *);
??0ZoneSmell@@QEAA@PEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_ZoneSmell_base+0*8]
??0ZoneSmell@@QEAA@PEAVZoneMap@@@Z endp

; ZoneSmell::_getSmell(enum SmellType);
?_getSmell@ZoneSmell@@QEAAPEAVSmell@1@W4SmellType@@@Z proc EXPORT
jmp function_pointers[_ZoneSmell_base+1*8]
?_getSmell@ZoneSmell@@QEAAPEAVSmell@1@W4SmellType@@@Z endp

; ZoneSmell::isEmpty();
?isEmpty@ZoneSmell@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ZoneSmell_base+2*8]
?isEmpty@ZoneSmell@@QEAA_NXZ endp

; ZoneSmell::addSmell(enum ZoneSmell::SmellMessageType, void *, const class Ogre::Vector3 &);
?addSmell@ZoneSmell@@QEAAXW4SmellMessageType@1@PEAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ZoneSmell_base+3*8]
?addSmell@ZoneSmell@@QEAAXW4SmellMessageType@1@PEAXAEBVVector3@Ogre@@@Z endp

; ZoneSmell::getSmell(class Ogre::Vector3 &, enum SmellType);
?getSmell@ZoneSmell@@QEAAMAEAVVector3@Ogre@@W4SmellType@@@Z proc EXPORT
jmp function_pointers[_ZoneSmell_base+4*8]
?getSmell@ZoneSmell@@QEAAMAEAVVector3@Ogre@@W4SmellType@@@Z endp

; ZoneSmell::getGeneralSmellLevel(enum SmellType);
?getGeneralSmellLevel@ZoneSmell@@QEAAMW4SmellType@@@Z proc EXPORT
jmp function_pointers[_ZoneSmell_base+5*8]
?getGeneralSmellLevel@ZoneSmell@@QEAAMW4SmellType@@@Z endp

; ZoneSmell::periodicUpdate(float);
?periodicUpdate@ZoneSmell@@QEAAXM@Z proc EXPORT
jmp function_pointers[_ZoneSmell_base+6*8]
?periodicUpdate@ZoneSmell@@QEAAXM@Z endp

?_DESTRUCTOR@ZoneSmell@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ZoneSmell@@QEAAXXZ endp

; ZoneSmell::~ZoneSmell();
??1ZoneSmell@@QEAA@XZ proc EXPORT
jmp function_pointers[_ZoneSmell_base+7*8]
??1ZoneSmell@@QEAA@XZ endp
