
?_CONSTRUCTOR@ZoneMapContent@@QEAAPEAV1@PEAVZoneMap@@@Z proc EXPORT
?_CONSTRUCTOR@ZoneMapContent@@QEAAPEAV1@PEAVZoneMap@@@Z endp

; ZoneMapContent::ZoneMapContent(class ZoneMap *);
??0ZoneMapContent@@QEAA@PEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+0*8]
??0ZoneMapContent@@QEAA@PEAVZoneMap@@@Z endp

?_DESTRUCTOR@ZoneMapContent@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::~ZoneMapContent();
??1ZoneMapContent@@UEAA@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+1*8]
??1ZoneMapContent@@UEAA@XZ endp

; ZoneMapContent::isLoadedT();
?isLoadedT@ZoneMapContent@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+2*8]
?isLoadedT@ZoneMapContent@@QEAA_NXZ endp

?_NV_update@ZoneMapContent@@QEAA_NXZ proc EXPORT
?_NV_update@ZoneMapContent@@QEAA_NXZ endp

; ZoneMapContent::update();
?update@ZoneMapContent@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+3*8]
?update@ZoneMapContent@@UEAA_NXZ endp

; ZoneMapContent::threadedUpdate();
?threadedUpdate@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+4*8]
?threadedUpdate@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::addToUpdateList(class RootObject *);
?addToUpdateList@ZoneMapContent@@QEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+5*8]
?addToUpdateList@ZoneMapContent@@QEAAXPEAVRootObject@@@Z endp

; ZoneMapContent::_reloadAllFoliage();
?_reloadAllFoliage@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+6*8]
?_reloadAllFoliage@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::getOverlayData();
?getOverlayData@ZoneMapContent@@QEBAPEAVRealWorldEditableImage@@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+7*8]
?getOverlayData@ZoneMapContent@@QEBAPEAVRealWorldEditableImage@@XZ endp

; ZoneMapContent::getOverlayPixelCoord();
?getOverlayPixelCoord@ZoneMapContent@@QEBA?AViVector2@@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+8*8]
?getOverlayPixelCoord@ZoneMapContent@@QEBA?AViVector2@@XZ endp

; ZoneMapContent::clearOverlay(int);
?clearOverlay@ZoneMapContent@@QEBAXH@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+9*8]
?clearOverlay@ZoneMapContent@@QEBAXH@Z endp

; ZoneMapContent::generateDirtMap(int);
?generateDirtMap@ZoneMapContent@@QEBAHH@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+10*8]
?generateDirtMap@ZoneMapContent@@QEBAHH@Z endp

; ZoneMapContent::addLoadedBuilding(class GameSaveState *, bool);
?addLoadedBuilding@ZoneMapContent@@QEAAXPEAVGameSaveState@@_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+11*8]
?addLoadedBuilding@ZoneMapContent@@QEAAXPEAVGameSaveState@@_N@Z endp

; ZoneMapContent::loadItems(class GameDataContainer *);
?loadItems@ZoneMapContent@@QEAA_NPEAVGameDataContainer@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+12*8]
?loadItems@ZoneMapContent@@QEAA_NPEAVGameDataContainer@@@Z endp

; ZoneMapContent::saveItems(class GameDataContainer *, bool);
?saveItems@ZoneMapContent@@QEAAXPEAVGameDataContainer@@_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+13*8]
?saveItems@ZoneMapContent@@QEAAXPEAVGameDataContainer@@_N@Z endp

; ZoneMapContent::saveLevelData(bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveLevelData@ZoneMapContent@@QEAAX_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+14*8]
?saveLevelData@ZoneMapContent@@QEAAX_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; ZoneMapContent::saveToDisk(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveToDisk@ZoneMapContent@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+15*8]
?saveToDisk@ZoneMapContent@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ZoneMapContent::activate();
?activate@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+16*8]
?activate@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::deactivate(bool);
?deactivate@ZoneMapContent@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+17*8]
?deactivate@ZoneMapContent@@QEAAX_N@Z endp

; ZoneMapContent::reFactionBuildingsFromTown();
?reFactionBuildingsFromTown@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+18*8]
?reFactionBuildingsFromTown@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::updateItemsVisibility();
?updateItemsVisibility@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+19*8]
?updateItemsVisibility@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::_setEnabledStaticGeometry(bool);
?_setEnabledStaticGeometry@ZoneMapContent@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+20*8]
?_setEnabledStaticGeometry@ZoneMapContent@@QEAAX_N@Z endp

; ZoneMapContent::findBuildingTypePublic(class Town *);
?findBuildingTypePublic@ZoneMapContent@@QEAAPEAVBuilding@@PEAVTown@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+21*8]
?findBuildingTypePublic@ZoneMapContent@@QEAAPEAVBuilding@@PEAVTown@@@Z endp

; ZoneMapContent::findAllBuildingTypePublics(class lektor<Building *> &, class Town *, enum ItemFunction);
?findAllBuildingTypePublics@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVTown@@W4ItemFunction@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+22*8]
?findAllBuildingTypePublics@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVTown@@W4ItemFunction@@@Z endp

; ZoneMapContent::findAllBuildingTypePublics(class lektor<Building *> &, class Town *);
?findAllBuildingTypePublics@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVTown@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+23*8]
?findAllBuildingTypePublics@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVTown@@@Z endp

; ZoneMapContent::findAllBuildings(class TownBase *, class Faction *, class BuildingFinderClass *, bool);
?findAllBuildings@ZoneMapContent@@QEAAXPEAVTownBase@@PEAVFaction@@PEAVBuildingFinderClass@@_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+24*8]
?findAllBuildings@ZoneMapContent@@QEAAXPEAVTownBase@@PEAVFaction@@PEAVBuildingFinderClass@@_N@Z endp

; ZoneMapContent::findAllBuildings(class lektor<Building *> &, class TownBase *, class Faction *, bool, unsigned int, class Ownerships *);
?findAllBuildings@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVTownBase@@PEAVFaction@@_NIPEAVOwnerships@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+25*8]
?findAllBuildings@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVTownBase@@PEAVFaction@@_NIPEAVOwnerships@@@Z endp

; ZoneMapContent::findAllBuildingsThatLinkTo(class lektor<Building *> &, class GameData *);
?findAllBuildingsThatLinkTo@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+26*8]
?findAllBuildingsThatLinkTo@ZoneMapContent@@QEAAXAEAV?$lektor@PEAVBuilding@@@@PEAVGameData@@@Z endp

; ZoneMapContent::findBuildingByDataPosition(class GameData *, float, float);
?findBuildingByDataPosition@ZoneMapContent@@QEAAPEAVBuilding@@PEAVGameData@@MM@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+27*8]
?findBuildingByDataPosition@ZoneMapContent@@QEAAPEAVBuilding@@PEAVGameData@@MM@Z endp

; ZoneMapContent::_populateTownsOnNewGame();
?_populateTownsOnNewGame@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+28*8]
?_populateTownsOnNewGame@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::forceLoadAllTheBuildingInteriorVisuals();
?forceLoadAllTheBuildingInteriorVisuals@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+29*8]
?forceLoadAllTheBuildingInteriorVisuals@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::addItem(class Item *);
?addItem@ZoneMapContent@@QEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+30*8]
?addItem@ZoneMapContent@@QEAAXPEAVItem@@@Z endp

; ZoneMapContent::removeItem(class Item *);
?removeItem@ZoneMapContent@@QEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+31*8]
?removeItem@ZoneMapContent@@QEAAXPEAVItem@@@Z endp

; ZoneMapContent::changeItemZone(class Item *, class ZoneMap *);
?changeItemZone@ZoneMapContent@@QEAA_NPEAVItem@@PEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+32*8]
?changeItemZone@ZoneMapContent@@QEAA_NPEAVItem@@PEAVZoneMap@@@Z endp

; ZoneMapContent::_getItems();
?_getItems@ZoneMapContent@@QEBAAEBV?$unordered_set@Vhand@@U?$hash@Vhand@@@boost@@U?$equal_to@Vhand@@@std@@V?$STLAllocator@Vhand@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+33*8]
?_getItems@ZoneMapContent@@QEBAAEBV?$unordered_set@Vhand@@U?$hash@Vhand@@@boost@@U?$equal_to@Vhand@@@std@@V?$STLAllocator@Vhand@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ endp

?_NV_removeObject@ZoneMapContent@@QEAA_NPEAVRootObject@@@Z proc EXPORT
?_NV_removeObject@ZoneMapContent@@QEAA_NPEAVRootObject@@@Z endp

; ZoneMapContent::removeObject(class RootObject *);
?removeObject@ZoneMapContent@@UEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+34*8]
?removeObject@ZoneMapContent@@UEAA_NPEAVRootObject@@@Z endp

; ZoneMapContent::_addDeletedThing(const class InstanceID &);
?_addDeletedThing@ZoneMapContent@@QEAAXAEBVInstanceID@@@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+35*8]
?_addDeletedThing@ZoneMapContent@@QEAAXAEBVInstanceID@@@Z endp

; ZoneMapContent::getFoliageSystem();
?getFoliageSystem@ZoneMapContent@@QEBAPEBVFoliageSystem@@XZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+36*8]
?getFoliageSystem@ZoneMapContent@@QEBAPEBVFoliageSystem@@XZ endp

; ZoneMapContent::_activate();
?_activate@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+37*8]
?_activate@ZoneMapContent@@QEAAXXZ endp

; symbol is too long
; ?populateAllTheBuildings@ZoneMapContent@@QEAAXPEAV?$unordered_set@PEAVTown@@U?$hash@PEAVTown@@@boost@@U?$equal_to@PEAVTown@@@std@@V?$STLAllocator@PEAVTown@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@PEAV?$lektor@PEAVBuilding@@@@@Z
; ZoneMapContent::populateAllTheBuildings(class boost::unordered::unordered_set<Town *,boost::hash<Town *>,std::equal_to<Town *>,Ogre::STLAllocator<Town *,Ogre::CategorisedAllocPolicy<0> > > *, class lektor<Building *> *);
ZoneMapContent_populateAllTheBuildings_PLACEHOLDER proc EXPORT
jmp function_pointers[_ZoneMapContent_base+38*8]
ZoneMapContent_populateAllTheBuildings_PLACEHOLDER endp

; ZoneMapContent::createLoadedItems();
?createLoadedItems@ZoneMapContent@@QEAAXXZ proc EXPORT
jmp function_pointers[_ZoneMapContent_base+39*8]
?createLoadedItems@ZoneMapContent@@QEAAXXZ endp

; ZoneMapContent::setLoadedT(bool);
?setLoadedT@ZoneMapContent@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ZoneMapContent_base+40*8]
?setLoadedT@ZoneMapContent@@QEAAX_N@Z endp
